### ISSUE TITLE
Telegraf ZFS request

### ISSUE THREAD

**Issue by JRGTH** [opnsense/tools#102]
Hi, it would be nice to have Telegraf: Input options for inputs.zfs, poolMetrics , so we can monitor ZFS ARC, ZFS pool(if poolMetrics on) etc. for Root On ZFS installations.

For now, my workaround is to add it manually to telegraf.conf

```
[[inputs.zfs]]
  poolMetrics = true
```

Regards

**Comment by mimugmail** [comment]
I'll add it to next version :)

**Comment by JRGTH** [comment]
Awesome, thanks for the prompt response.

Regards
