### ISSUE TITLE
logrotate

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/tools#104]
port makes sense to be used by any plugin that has to manage the logs of the daemon.

For example nginx may create lots of work so I want to be able to create a configurable task which rotates the logs via cron.

**Comment by fichtner** [comment]
Newsyslog is used in other components already. I do not like adding the daemon to core dependencies and also adding it to a plugin that depends on it directly is a bit weird.

**Comment by juliocbc** [comment]
@fichtner @franz 

https://github.com/opnsense/plugins/pull/982

**Comment by fabianfrz** [comment]
@fichtner I got a pull request for newsyslog so this case is closed. BTW: this is not a daemon, it is a simple tool which is usually called via cron.
