### ISSUE TITLE
sysutils/burp

### ISSUE THREAD

**Issue by fprina** [opnsense/tools#106]
I use BPUR as network backup so i would like to use it also with OPNsense
So could you please add this package to the ones available

Thanks

Related to the forum [BURP FreeBSD port](https://forum.opnsense.org/index.php?topic=10364.0) topic

**Comment by fprina** [comment]
Thanks  @fichtner 

I know that it's old version :-\ 

Also EPEL updated the 1.4.40 package to a current stable in the last summer

Anyway the Freebsd port doesn't look like completely unmaintained
https://svnweb.freebsd.org/ports/head/sysutils/burp/?view=log

Cheers,
Fabio

**Comment by fichtner** [comment]
I think it's just framework noise that the port needs. how about asking over at https://bugs.freebsd.org/bugzilla/ or writing the port maintainer? if there's no reaction maybe we can work on the port update together...

**Comment by fprina** [comment]
[Ticket opened](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233758)

We will see ...

**Comment by fichtner** [comment]
thanks! small issue though, ticket subject should be "sysutils/burp: etcetc" with a ":" so that maintainer is automatically assigned. in this case it was not.

**Comment by fprina** [comment]
You right !!! I didn't noticed the ":" in the template.
I've fixed the subject but I suppose it will not be re-assigned to right maintainer: "Maintained by: ports@FreeBSD.org".

Do you think it's better close/open a new one ?

**Comment by fprina** [comment]
The FreeBSD package was update to [2.2.28](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236963)

Could you please add now the package to OPNsense

**Comment by fichtner** [comment]
okay, sure. thanks for prodding
