### ISSUE TITLE
[core] make upgrade fails

### ISSUE THREAD

**Issue by reza-ebrahimi** [opnsense/tools#107]
`make upgrade` fails:

```console
root@OPNsense:/usr/core # make upgrade
pkg: No package(s) matching radvd1
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        radvd1: 1.15

Number of packages to be installed: 1

98 KiB to be downloaded.
[1/1] Fetching radvd1-1.15.txz: 100%   98 KiB 100.0kB/s    00:01    
pkg: cached package radvd1-1.15: size mismatch, fetching from remote
Fetching radvd1-1.15.txz: 100%   98 KiB 100.0kB/s    00:01    
pkg: cached package radvd1-1.15: size mismatch, cannot continue
*** Error code 3

Stop.
make: stopped in /usr/core
```

**Comment by fichtner** [comment]
There's not enough information here. What installation, what version? Do you use /var MFS?

Likely candidate: your package database has been damaged / deleted.

**Comment by reza-ebrahimi** [comment]
OPNsense version: 18.7
I don't know what do you mean about /var MFS, That's what I do:

```
# pkg install git
# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools
# make update
# make dvd
```
After `make dvd` I have error about building `zabbix-agent` port, so I fixed error with following command:
```
# make ports-zabbix
# make dvd 
```

And `make dvd` successfully finished build with an `iso`, After that I've making some changes into core repository and `make upgrade` and it throws an error reported above:

```
# cd /usr/core
# make upgrade
```

**Comment by reza-ebrahimi** [comment]
Removed `core` and clone it again, error still exists:
```console
root@OPNsense:/usr/core # make upgrade
pkg: No package(s) matching radvd1
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        radvd1: 1.15

Number of packages to be installed: 1

98 KiB to be downloaded.
[1/1] Fetching radvd1-1.15.txz: 100%   98 KiB 100.0kB/s    00:01    
pkg: cached package radvd1-1.15: size mismatch, fetching from remote
Fetching radvd1-1.15.txz: 100%   98 KiB 100.0kB/s    00:01    
pkg: cached package radvd1-1.15: size mismatch, cannot continue
*** Error code 3

Stop.
make: stopped in /usr/core
root@OPNsense:/usr/core # 
```

**Comment by fichtner** [comment]
> And make dvd successfully finished build with an iso, After that I've making some changes into core repository and make upgrade and it throws an error reported above:

Are you trying to run "make upgrade" on the build system? oO

What's

    # uname -a

**Comment by reza-ebrahimi** [comment]
> > And make dvd successfully finished build with an iso, After that I've making some changes into core repository and make upgrade and it throws an error reported above:
> 
> Are you trying to run "make upgrade" on the build system? oO

Build system? how to do that?


> 
> What's
> 
> ```
> # uname -a
> ```
> ?

```console
root@OPNsense:/usr/core # uname -a
FreeBSD OPNsense.localdomain 11.1-RELEASE-p11 FreeBSD 11.1-RELEASE-p11  21b4c8ea1d5(stable/18.7)  amd64

```

**Comment by reza-ebrahimi** [comment]
>  ```
> # pkg clean -ya 
> # pkg update -f
> # make upgrade
> ```

```console
root@OPNsense:/usr/tools # pkg clean -ya
The following package files will be deleted:
        /var/cache/pkg/git-2.19.1-339842fe9e.txz
        /var/cache/pkg/git-2.19.1.txz
        /var/cache/pkg/p5-Error-0.17027-b46c1a02a8.txz
        /var/cache/pkg/cvsps-2.1_2-6d3128cfee.txz
        /var/cache/pkg/p5-Error-0.17027.txz
        /var/cache/pkg/cvsps-2.1_2.txz
        /var/cache/pkg/tmux-2.8-a74043ae3f.txz
        /var/cache/pkg/tmux-2.8.txz
The cleanup will free 5 MiB
Deleting files: 100%
All done
root@OPNsense:/usr/tools # pkg update -f
Updating OPNsense repository catalogue...
Fetching meta.txz: 100%    1 KiB   1.5kB/s    00:01    
Fetching packagesite.txz: 100%  149 KiB 152.3kB/s    00:01    
Processing entries: 100%
OPNsense repository update completed. 587 packages processed.
All repositories are up to date.
root@OPNsense:/usr/tools # cd /usr/core
root@OPNsense:/usr/core # make upgrade
```

`make upgrade` has done without error, Thanks a lot, please tell me why this mismatch happens?

**Comment by fichtner** [comment]
You're building your own packages, which signatures do not necessarily match ours. Please don't open more tickets. You are on your own now.

**Comment by reza-ebrahimi** [comment]
> You're building your own packages, which signatures do not necessarily match ours. Please don't open more tickets. You are on your own now.

It's OK but I don't understand this phrase `Please don't open more tickets`, I've opening issues for the problems I've faced with `opnsense`. What is the problem with them?

**Comment by fichtner** [comment]
I cannot support you in an open source capacity anymore. Other users have the same right to attention. I'm only trying to be fair.

**Comment by reza-ebrahimi** [comment]
I know about that and thanks before for your contribution, but for resolving this in a fairly manner, the right solution is being a mature documentation for development purposes that I think doesn't exists anymore.

**Comment by fichtner** [comment]
Help create it? :)

**Comment by reza-ebrahimi** [comment]
Hmmmm, it's hard question :) , so Yes! I'm ready for that in case of your contribution too.

**Comment by fichtner** [comment]
Great, thank you.

**Comment by reza-ebrahimi** [comment]
Where and how to start?
