### ISSUE TITLE
Question about build steps

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#109]
Does "make packages" is same as "make ports, plugins, core"? I mean, does "packages" include all those "ports, plugins, core" or I need to build all of them?

**Comment by fichtner** [comment]
Hi @nekoprog,

Yes, we use a Makefile dependency chain to ensure the correct targets are built before the one that was specified:

https://github.com/opnsense/tools/blob/afd7383b5c400e51f074f6e7b025456c80c08bb5/Makefile#L109

"packages" implies "core", which implies "plugins", etc.

But if you want to rebuild you need to force the step you already built previously...

E.g. if you have a new plugin, you need to rerun plugins. But it heavily depends on what you want to redo. For most purposes "refresh" deletes plugins and core, and then rebuilds them without having to redo "ports".


Cheers
Franco

**Comment by nekoprog** [comment]
thanks for the clarifications.
