### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#111]
Hello, is there any error log to read when running `make base`? I stumbled some error when running `make base kernel ARCH=arm:armv6 KERNEL=SMP-RPI2` on freebsd 11.2 i386, I have successfully installed qemu-user-static from ports. Here are the errors:

```
===> usr.sbin/bsnmpd/modules/snmp_mibII (all)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- clang ---
*** [clang] Error code 1


make[5]: stopped in /usr/src/usr.bin/clang/clang
1 error
```

**Comment by fichtner** [comment]
unfortunately I can't help with that build failure in base because it eludes our project scope...

**Comment by nekoprog** [comment]
That's fine. Is there any build option to change if I want to build 19.1 source?

**Comment by nekoprog** [comment]
just found it, SETTINGS=19.1

**Comment by fichtner** [comment]
Oh, that may be it since it tries to build 11.1 in 11.2 which has been known to break quickly.

Best to set SETTINGS=19.1 in tools.git/Makefile because all commands need it and this way it's always implied.

**Comment by nekoprog** [comment]
Thanks for the reply, I find it very helpful to set it directly on Makefile.
