### ISSUE TITLE
Port Request - Wazuh agent

### ISSUE THREAD

**Issue by juliocbc** [opnsense/tools#112]
Is it possible to create wazuh-agent (ossec fork) port?

security/wazuh-agent 

> Some of the most important features made by the Wazuh team are:
> 
> A kibana app to show all information and work with the manager.
> A RESTful API to retrieve information about the manager.
> Integration with OpenSCAP.
> An improved ruleset.
> Improved some components like log analysis and FIM capabilities.
> And bug fixes.
> 

ref.:https://github.com/wazuh/wazuh/issues/270

**Comment by mimugmail** [comment]
Just want  to build the port from my build-env, but there is no port yet. Where did you see that there's already a port in security/ ?

**Comment by juliocbc** [comment]
Hi @mimugmail ! Actually the existing port is the ossec-agent and the wazuh is a Ossec's fork.

**Comment by mimugmail** [comment]
Yes, but wazuh itself has no port. Is ossec agent compatible to wazuh?

**Comment by juliocbc** [comment]
Yes, it is compatible, but not with all the features(as a wrote in my first comment).

**Comment by fichtner** [comment]
all done thanks to @mimugmail \o/
