### ISSUE TITLE
obsolete file generation issue

### ISSUE THREAD

**Issue by evbevz** [opnsense/tools#115]
https://github.com/opnsense/tools/blob/0eb37037bbe29ffb864c58e794c66baad987aceb/config/19.1/plist.base.amd64#L476

Which collate you use when sorting base plist during base obsolete file generation?
In my case en_US.UTF-8:
/lib/libz.so.6
/lib/libzfs_core.so.2
/lib/libzfs.so.2

In your pkg:
/lib/libz.so.6
/lib/libzfs.so.2
/lib/libzfs_core.so.2
 
As result I have /lib/libzfs.so.2 in my base.obsolete file. It is problem for me.

**Comment by fichtner** [comment]
Hmm, I haven't set up anything that would change the default sorting behaviour... whatever sort(1) defaults to then...

**Comment by evbevz** [comment]
Maybe some special locale is set on build machine?

**Comment by evbevz** [comment]
https://github.com/opnsense/tools/blob/8d5f94880df51d54fed3dd6c7c47b227bb88db84/config/18.7/plist.base.amd64#L512
Here is other sort order.

**Comment by fichtner** [comment]
Not that I'm aware of. I cannot reproduce.

**Comment by fichtner** [comment]
"." is 46, "_" is 95 in ASCII so the sort order seems correct with what we have...
