### ISSUE TITLE
ports request: net/luasocket[-51]

### ISSUE THREAD

**Issue by ppmathis** [opnsense/tools#116]
I would like to request `net/luasocket` to be added to ports.conf - while this might seem like a strange request at first, being able to use the Lua module `socket.http` is highly useful when working with custom Lua scripts in HAProxy. For completeness sake, `net/luasocket-51` could be added as well, even though HAProxy only uses Lua 5.3.

One example would be integrating a simple authentication provider backend into HAProxy, e.g. oauth2_proxy, to have some simplified global authentication mechanism in place for various virtual hosts.

**Comment by fabianfrz** [comment]
Sounds stupid but nginx already has this feature under Advanced Authentication where you can login using basic auth using any OPNsense authentication provider.

**Comment by ppmathis** [comment]
@fabianfrz Thank you for the response. I clearly prefer sticking to just using HAProxy which has excellent capabilities for both proxying HTTP and TCP with a vast amount of configuration settings.

Additionally, I am not talking about basic authentication I am looking for and actively using the above mentioned setup in production. You can imagine the authentication flow like this:

1. HAProxy receives a request to a domain specifically flagged as "protected"
2. HAProxy checks authentication against oauth2_proxy in a stateless manner (using Lua)
2.1. If authentication succeeded: Jump to 6
2.2. If authentication fails, continue with 3
3. HAProxy redirects to the authentication provider (oauth2_proxy) passing the original URL
4. The end user authorizes against oauth2_proxy
5. The end user gets redirected to the original URL
6. The end user can access the requested resource

Any incoming HTTP connections will automatically keep the token/session alive, even when it only features a short lifetime. Multiple domains can be easily protected by just expanding the header-match ACL, authentication is done through a single endpoint. No basic authentication involved, end user gets a friendly login page, supports external providers like Google, GitHub, etcetera. Also, the actual authentication provider does not have to proxy the request, which greatly simplifies the configuration.

Without having luasocket, one would have to completely re-implement the HTTP protocol in custom Lua scripts when any kind of external service should be queried.

**Comment by ppmathis** [comment]
@fabianfrz Thanks again for your previous response. Would you consider adding this Lua module for the reasons I've written above? I am sure that I could figure out how to build that package by myself, but having it in the official repositories would be more comfortable, especially due to the fact that Lua itself is already bundled for being used with HAProxy.

**Comment by fabianfrz** [comment]
You have to ask @fichtner for that.

**Comment by fichtner** [comment]
@ppmathis ok, I will add net/luasocket -- we don't want 51 as it is not installed now, see below.

What this would ideally mean is that we should have whatever you're building as a feature inside the HAProxy plugin and tie luasocket into it as a required dependency. This of course only if you are willing to contribute and @fraenki (HAProxy maintainer) agrees.

    # pkg rquery %rn lua53
    haproxy
    # pkg rquery %rn lua52
    asterisk13
    # pkg rquery %rn lua51
    #

**Comment by fichtner** [comment]
One small tweak here, HAProxy uses Lua 5.3 and now the default is set to 5.3 (it is 5.2 in FreeBSD) and so luasocket will be the correct version and asterisk also follows that settings. 3248ce166f
