### ISSUE TITLE
build / dependencies

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/tools#117]
We could debate if this is a bug, a feature or something worthwhile to add to the readme (or me doing something very wrong here :) , but while trying to build some smaller branch containing less dependencies, we couldn't seem to build core.

The "issue" as I see it, is that when stripping dependencies from your ports config for your version, the master version is always build as well, which might have dependencies not in your build list.

https://github.com/opnsense/tools/blob/8b2469f596111d56a8377c8443a53b1570d50415/build/core.sh#L48-L64

When trying to build, it will crashes with `Could not find package:  XXXX`, which you thought wasn't anywhere in your work list (but was configured in master).

No rush here, just something not to forget :)

**Comment by fichtner** [comment]
It needs some sort of „single branch build“ mode where it ignores master. It’s part of the rewind.sh work that has not been finished:

https://github.com/opnsense/tools/blob/master/build/rewind.sh#L63-L67

Not sure what is better: ignoring development by default or having to set single build mode somewhere in the config. Or maybe it could be a global setting turning it off...

# make dvd DEVELBRANCH=

Probably 3 lines of changes.... 😊

**Comment by AdSchellevis** [comment]
no rush, really. at a first glance I would think that having it only build a single branch is better, more clean, less side affects. but I'm not sure how that reflects to the amount of work needed and overal nightly build times.

**Comment by fichtner** [comment]
nightly will know not to build single branches. Build time is marginally lower as we already reuse base, kernel, ports. But I agree it would be more straightforward for others. I’ll make the necessary changes next week.

**Comment by AdSchellevis** [comment]
Thanks!
