### ISSUE TITLE
net/py-speedtest-cli

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#126]
Really small python tool, should be easy to build a plugin :)

```
root@OPNsense:~ # speedtest-cli
Retrieving speedtest.net configuration...
Testing from m.a.x. it AG (81.24.66.162)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Net-D-Sign GmbH (Garching) [12.13 km]: 14.614 ms
Testing download speed................................................................................
Download: 546.57 Mbit/s
Testing upload speed................................................................................................
Upload: 486.76 Mbit/s
```

**Comment by mimugmail** [comment]
But iperf needs an iperf server and it's not quite accurate as it consumes plenty of CPU

**Comment by fabianfrz** [comment]
CPU is usually not the problem as the CPU is faster then the throughput of the network (this is one of the reasons why attacks like spectre are possible - the CPU can work while it is waiting for a response from memory or hardware). It would be different if an IPS is running on the interface but that's another topic.

If you just want a download stat, you can send a simple query from PHP using curl. It should deliver the download rate as well.

**Comment by mimugmail** [comment]
But it's also only working in server mode, how would you test connection speed to WAN? 

The speedtest tool measures upload/download in a nice way and I don't have to worry about remote end.

**Comment by fichtner** [comment]
Probably more time wasted discussing than pulling this in. Let's do it. :)
