### ISSUE TITLE
Port Request: osqueryd - osquery agent

### ISSUE THREAD

**Issue by gstuartj** [opnsense/tools#131]
osquery is the hot new(ish) host intelligence/monitoring/etc platform in the OSS world. It exposes host data as a pseudo relational database which makes it very versatile & powerful. It's getting more and more popular, so it would be handy if it were made available so an easy plugin could be written.

https://github.com/facebook/osquery
https://osquery.readthedocs.io/en/stable/installation/install-freebsd/

**Comment by gstuartj** [comment]
Forum thread: https://forum.opnsense.org/index.php?PHPSESSID=qjpugcs2t3ohac0pnn79cl5pb5&topic=12160.msg57298#new

**Comment by fichtner** [comment]
osquery requires 749 on the disk and 71 in zipped downloads. it is indeed very heavy for the purpose it's trying to fill in. not sure what @mimugmail thinks but it certainly does not qualify our policy "light footprint and no similar alternative available".

**Comment by mimugmail** [comment]
How much does it delay the build process? This tools seems to be highly advanced.

**Comment by fichtner** [comment]
No more feedback on forum  thread, closing for now.

**Comment by mimugmail** [comment]
Its also out of ports since it uses python2. I'm currently playing around maintaining a Python 3 variant. But let IT closed for now
