### ISSUE TITLE
Feature request: Port for librenms-agent

### ISSUE THREAD

**Issue by rkirmis** [opnsense/tools#132]
Hello,
i would be nice, if the librenms-agent could be included in the ports tree.
https://www.freshports.org/net-mgmt/librenms-agent/
The agent ist compatible with the monitoring solution check_mk, so
https://forum.opnsense.org/index.php?topic=11828.msg54083#msg54083
wouldn't require a external download.-

**Comment by fichtner** [comment]
Hi, I assume by port you mean binary package?

**Comment by rkirmis** [comment]
Hi,
yes.
So it could be installed via pkg install librenms-agent and requires now additional download.

**Comment by fichtner** [comment]
Ok, thanks. I've added it to the nightly build. If nothing bad happens it will be in 19.1.7. Dependency footprint looks ok.


Cheers,
Franco
