### ISSUE TITLE
support kernel sets with device names

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#137]
Previously we had an issue about kernel naming for arm devices. What if we add another device called generic, this will be used as default in config, replacing a10.

Thus on kernel name side, we can add something like this:
`kernel-*-${PRODUCT_ARCH}-${PRODUCT_DEVICE}.txz`

This will produce name consistency for all build.
Generic i386/amd64
`kernel-*-i386-generic.txz`
`kernel-*-amd64-generic.txz`

ARM
`kernel-*-armv6-bpi.txz`
`kernel-*-armv6-rpi2.txz`

ARM64
`kernel-*-aarch64-rpi3.txz`
`kernel-*-aarch64-orangepi-pc2.txz`

This topic is open for further discussion because arm devices will produce different kernel.txz which will affect on firmware updates and this will hinder the progress for arm-based production release.

**Comment by fichtner** [comment]
I like it, no discussion :)

The tricky part is figuring out which kernel we are currently running and adjusting the name accordingly to download the correct one. opnsense-version does a bit of this for other meta build info and some of it is stored in installable files, other things are not. Maybe it's important to make this fail-safe, some kind of kernel variable to read?

**Comment by nekoprog** [comment]
Need to place PRODUCT_DEVICE name somewhere like how we call `uname`.

**Comment by fichtner** [comment]
But all files can break. Isn't there a sysctl we could ask for the device/kernel name?

**Comment by fichtner** [comment]
It should be "uname -p" ?

**Comment by nekoprog** [comment]
I think `uname -p` could be used as arch identifier.
If arch==
`i386/amd64 -> generic`
`armv6 -> armv6`
`aarch64 -> aarch64`
 
Currently running `sysctl -a`, looking for something like raspberry pi or rpi2. If it's there, it could be used later.

**Comment by nekoprog** [comment]
got one `kern.ident: SMP-RPI2`. how about amd64 kernel? will they print something like SMP? if it does, it will be easy to classify them.

**Comment by fichtner** [comment]
ok nice catch. So I think we should only extrapolate device names after first "-" and if no "-" is set we don't append device (-generic). With this we only need to update opnsense-update and don't run the risk breaking i386 and amd64. ok?

**Comment by nekoprog** [comment]
Should works fine too, saves time to read codes with "kernel" to rename all of them.

**Comment by fichtner** [comment]
It's a little tricky but it should work https://github.com/opnsense/update/commit/a7c9bb323a -- you can rename the arm images if you want. We simply need to make sure that "SMP-XXX" corresponds with device name and we don't do it for amd64/i386.

**Comment by nekoprog** [comment]
Looks good will test it this weekend, if it works, I'll close this issue.

**Comment by nekoprog** [comment]
@fichtner I got this error
```
***GOT REQUEST TO REINSTALL: kernel***
Mirror read failed.
***DONE***
```
my mirror at `http://neko.progr.am/FreeBSD:11:armv6/`

my OPNsense.conf
```
OPNsense: {
  fingerprints: "/usr/local/etc/pkg/fingerprints/OPNsense",
  url: "http://neko.progr.am/pieSense/${ABI}/19.1/latest",
  signature_type: "NONE",
  mirror_type: "NONE",
  priority: 11,
  enabled: yes
}
```

**Comment by fichtner** [comment]
I get 404 on http://neko.progr.am/FreeBSD:11:armv6

**Comment by nekoprog** [comment]
sorry, i moved the files into different folder. Try 'http://neko.progr.am/pieSense/FreeBSD:11:armv6'. But still the same error.

**Comment by fichtner** [comment]
Can you try this on the command line?

    # opnsense-update -kfV

**Comment by nekoprog** [comment]
i got this output

```
+ [ '' '=' -T ]
+ [ -z -k ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -z -f ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -z '' ]
+ RELEASE=19.1.7
+ [ '' '=' -B ]
+ [ '' '=' -P ]
+ [ -n '' ]
+ [ '' '=' -p -a -z '' ]
+ FLAVOUR=Base
+ [ -n '' ]
+ [ -f /usr/local/bin/openssl ]
+ /usr/local/bin/openssl version
+ awk '{ print $1 }'
+ FLAVOUR=OpenSSL
+ PACKAGESSET=packages-19.1.7-OpenSSL-armv6.tar
+ KERNELSET=kernel-19.1.7-armv6.txz
+ BASESET=base-19.1.7-armv6.txz
+ mirror_abi
+ sed -n 's/^[[:space:]]*url:[[:space:]]*\"pkg\+\(.*\/${ABI}\/[^\/]*\)\/.*/\1/p' /usr/local/etc/pkg/repos/OPNsense.conf
+ MIRROR='http://neko.progr.am/pieSense/${ABI}/19.1'
+ [ -z 'http://neko.progr.am/pieSense/${ABI}/19.1' ]
+ opnsense-verify -a
+ ABI=FreeBSD:11:armv6
+ [ -n '' ]
+ eval 'MIRROR=http://neko.progr.am/pieSense/${ABI}/19.1'
+ MIRROR=http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1
+ echo http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1
+ MIRROR=http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1/sets
+ [ -n '' ]
+ [ -z -f ]
+ [ '' '=' -p ]
+ [ '' '=' -b ]
+ [ -k '=' -k ]
+ [ -z -f -o -n '' ]
+ fetch_set kernel-19.1.7-armv6.txz
+ STAGE1='opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/24721/kernel-19.1.7-armv6.txz.sig http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1/sets/kernel-19.1.7-armv6.txz.sig'
+ STAGE2='opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/24721/kernel-19.1.7-armv6.txz http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1/sets/kernel-19.1.7-armv6.txz'
+ STAGE3='opnsense-verify -q /var/cache/opnsense-update/24721/kernel-19.1.7-armv6.txz'
+ [ -n '' ]
+ [ -n '' ]
+ echo -n 'Fetching kernel-19.1.7-armv6.txz: .'
Fetching kernel-19.1.7-armv6.txz: .+ mkdir -p /var/cache/opnsense-update/24721
+ opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/24721/kernel-19.1.7-armv6.txz.sig http://neko.progr.am/pieSense/FreeBSD:11:armv6/19.1/sets/kernel-19.1.7-armv6.txz.sig
.......................................+ exit_msg ' failed, no signature found'
+ [ -n ' failed, no signature found' ]
+ echo ' failed, no signature found'
 failed, no signature found
+ exit 1
```

**Comment by fichtner** [comment]
I see, that is normal, because you're not using signatures. The invoke is

# opnsense-update -i -kf

We can patch up opnsense-update to honour if OPNsense.conf has a fingerprint and if not turn -i on automatically.

**Comment by fichtner** [comment]
I've changed a few things with 5dfee1c0411e6f6a and 5dfee1c0411

With this there's going to be some destructive element in arm testing / assembly, but hopefully when we hit 19.7 it won't change so much.

Still need to get Banana Pi up and running completely. So far no luck, but only a matter of time :)

**Comment by nekoprog** [comment]
i'll try another `make update` to test this new feature. will let you know later. thanks.

**Comment by fichtner** [comment]
This will fix your update issue https://github.com/opnsense/update/commit/4672fc1d9c8

BTW, we are going to use FreeBSD device names from now on so e.g. "bpi" is now "BANANAPI". It would create the least amount of confusion about which images are supported and how they translate to FreeBSD's used device names. For this reason the detection changes again...

https://github.com/opnsense/update/commit/25140d27e383ee

... but you can still use -D manually for the old device name.

**Comment by nekoprog** [comment]
thanks, running `make update` again. will test it soon after completed building sets.

**Comment by nekoprog** [comment]
@fichtner could you please delete odroid configs too? freebsd won't add any support, they refused to add u-boot slave port for this device.

**Comment by fichtner** [comment]
weird, ok :(

**Comment by nekoprog** [comment]
also delete configs for orangepi-pc2, because this is arm64 device, i think it also not supported in 11.2. can't wait for OPNsense to use 12.0 base.

**Comment by fichtner** [comment]
This is RPI2, but it currently only works with kernel from master branch:

<img width="529" alt="Screenshot 2019-05-08 at 11 04 36 AM" src="https://user-images.githubusercontent.com/1915288/57363431-61615780-7181-11e9-8424-bebb267c0184.png">

Image can be found here:

https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/OPNsense-19.1-test-OpenSSL-arm-armv6-RPI2.img.bz2

And the packages and plugins are available on the mirror (officially signed). We might do an update later on just for testing :)

**Comment by nekoprog** [comment]
nice, now i can have an official update for my RPI2 board. :)

**Comment by fichtner** [comment]
It's still a work in progress, but the image works and has all dev tools in it to test device name kernel and base sets now and we can do an update in a few weeks to see how that goes if you are satisfied with the test results on your end.

**Comment by nekoprog** [comment]
running a `opnsense-update -ibkf` right now, might be downgrading some packages, but everything looking fine. the update from 19.1.6 to 19.1.7 went well. thanks for your hard work.

```
root@OPNsense:~ # pkg install -f opnsense-update
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

Installed packages to be DOWNGRADED:
        opnsense-update: 19.1.7 -> 19.1.4

Number of packages to be downgraded: 1

28 KiB to be downloaded.

Proceed with this action? [y/N]: y
[1/1] Fetching opnsense-update-19.1.4.txz: 100%   28 KiB  28.4kB/s    00:01
Checking integrity... done (0 conflicting)
[1/1] Downgrading opnsense-update from 19.1.7 to 19.1.4...
[1/1] Extracting opnsense-update-19.1.4: 100%
root@OPNsense:~ # opnsense-update -ibkfV
+ [ '' '=' -T ]
+ [ -z -k-b ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -z -f ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -n '' ]
+ [ -z '' ]
+ RELEASE=19.1.4
+ [ -b '=' -B ]
+ [ '' '=' -P ]
+ [ -n '' ]
+ [ '' '=' -p -a -z '' ]
+ FLAVOUR=Base
+ [ -n '' ]
+ [ -f /usr/local/bin/openssl ]
+ /usr/local/bin/openssl version
+ awk '{ print $1 }'
+ FLAVOUR=OpenSSL
+ PACKAGESSET=packages-19.1.4-OpenSSL-armv6.tar
+ KERNELSET=kernel-19.1.4-armv6.txz
+ BASESET=base-19.1.4-armv6.txz
+ mirror_abi
+ sed -n 's/^[[:space:]]*url:[[:space:]]*\"pkg\+\(.*\/${ABI}\/[^\/]*\)\/.*/\1/p' /usr/local/etc/pkg/repos/OPNsense.conf
+ MIRROR='https://pkg.opnsense.org/${ABI}/19.1'
+ [ -z 'https://pkg.opnsense.org/${ABI}/19.1' ]
+ opnsense-verify -a
+ ABI=FreeBSD:11:armv6
+ [ -n '' ]
+ eval 'MIRROR=https://pkg.opnsense.org/${ABI}/19.1'
+ MIRROR=https://pkg.opnsense.org/FreeBSD:11:armv6/19.1
+ echo https://pkg.opnsense.org/FreeBSD:11:armv6/19.1
+ MIRROR=https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets
+ [ -n '' ]
+ [ -z -f ]
+ [ '' '=' -p ]
+ [ -b '=' -b ]
+ [ -z -f -o -n '' ]
+ fetch_set base-19.1.4-armv6.txz
+ STAGE1='opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/38478/base-19.1.4-armv6.txz.sig https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets/base-19.1.4-armv6.txz.sig'
+ STAGE2='opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/38478/base-19.1.4-armv6.txz https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets/base-19.1.4-armv6.txz'
+ STAGE3='opnsense-verify -q /var/cache/opnsense-update/38478/base-19.1.4-armv6.txz'
+ [ -n '' ]
+ [ -n -i ]
+ STAGE1=:
+ STAGE3=:
+ echo -n 'Fetching base-19.1.4-armv6.txz: .'
Fetching base-19.1.4-armv6.txz: .+ mkdir -p /var/cache/opnsense-update/38478
+ :
+ opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/38478/base-19.1.4-armv6.txz https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets/base-19.1.4-armv6.txz
..........................................................+ [ -n -V ]
+ :
+ echo ' done'
 done
+ [ -k '=' -k ]
+ [ -z -f -o -n '' ]
+ fetch_set kernel-19.1.4-armv6.txz
+ STAGE1='opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/38478/kernel-19.1.4-armv6.txz.sig https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets/kernel-19.1.4-armv6.txz.sig'
+ STAGE2='opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/38478/kernel-19.1.4-armv6.txz https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets/kernel-19.1.4-armv6.txz'
+ STAGE3='opnsense-verify -q /var/cache/opnsense-update/38478/kernel-19.1.4-armv6.txz'
+ [ -n '' ]
+ [ -n -i ]
+ STAGE1=:
+ STAGE3=:
+ echo -n 'Fetching kernel-19.1.4-armv6.txz: .'
Fetching kernel-19.1.4-armv6.txz: .+ mkdir -p /var/cache/opnsense-update/38478
+ :
+ opnsense-fetch -a -T 30 -q -o /var/cache/opnsense-update/38478/kernel-19.1.4-armv6.txz https://pkg.opnsense.org/FreeBSD:11:armv6/19.1/sets/kernel-19.1.4-armv6.txz
.........................+ [ -n -V ]
+ :
+ echo ' done'
 done
+ [ -k '=' -k ]
+ echo '!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!'
!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!
+ echo '! A critical upgrade is in progress. !'
! A critical upgrade is in progress. !
+ echo '! Please do not turn off the system. !'
! Please do not turn off the system. !
+ echo !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
+ [ '' '=' -p -a -n '' ]
+ [ -b '=' -b -a -n '' ]
+ [ -k '=' -k ]
+ install_kernel
+ KLDXREF='kldxref /boot/kernel'
+ [ -n '' ]
+ echo -n 'Installing kernel-19.1.4-armv6.txz...'
Installing kernel-19.1.4-armv6.txz...+ mkdir -p /boot/kernel /boot/kernel.old /usr/lib/debug/boot/kernel
+ rm -r /boot/kernel.old /usr/lib/debug/boot/kernel
+ mv /boot/kernel /boot/kernel.old
+ tar -C / -xpf /var/cache/opnsense-update/38478/kernel-19.1.4-armv6.txz
+ kldxref /boot/kernel
+ echo ' done'
 done
+ [ -n -b -a -z '' ]
+ [ -b '=' -B ]
+ install_base
+ NOSCHGDIRS='/bin /sbin /lib /libexec /usr/bin /usr/sbin /usr/lib /var/empty'
+ echo -n 'Installing base-19.1.4-armv6.txz...'
Installing base-19.1.4-armv6.txz...+ mkdir -p /bin /sbin /lib /libexec /usr/bin /usr/sbin /usr/lib /var/empty
+ chflags -R noschg /bin /sbin /lib /libexec /usr/bin /usr/sbin /usr/lib /var/empty
+ tar -C / -xpf /var/cache/opnsense-update/38478/base-19.1.4-armv6.txz '--exclude=^etc/group' '--exclude=^etc/master.passwd' '--exclude=^etc/passwd' '--exclude=^etc/pwd.db' '--exclude=^etc/rc' '--exclude=^etc/rc.shutdown' '--exclude=^etc/shells' '--exclude=^etc/spwd.db' '--exclude=^etc/ttys' '--exclude=^proc' '--exclude=^var/cache/pkg' '--exclude=^var/crash' '--exclude=^var/db/pkg'
+ kldxref /boot/kernel
+ [ ! -f /usr/local/opnsense/version/base.obsolete ]
+ read FILE
+ echo ' done'
 done
+ rm -rf '/var/cache/opnsense-update/.sets.pending/base-*'
+ [ '' '=' -P -a -z '' ]
+ [ -z '' ]
+ rm -rf /var/cache/opnsense-update/10649 /var/cache/opnsense-update/16840 /var/cache/opnsense-update/24721 /var/cache/opnsense-update/38478 /var/cache/opnsense-update/56635 /var/cache/opnsense-update/94442
+ echo 'Please reboot.'
Please reboot.
```

![opnsense-before](https://user-images.githubusercontent.com/2550618/57368431-b91db400-71bd-11e9-8a38-34d5eed3a470.jpg)
![opnsense-after](https://user-images.githubusercontent.com/2550618/57368441-be7afe80-71bd-11e9-8a95-56133b9499a9.jpg)

**Comment by fichtner** [comment]
Neat, ok. You don't need -i in this case anymore. Thank you for your hard work, too 👍

**Comment by nekoprog** [comment]
it's ok to close this issue right?

**Comment by fichtner** [comment]
I don't think there are any loose ends except for shipping the changes in the next weeks. Feel free to close if that is your impression as well.
