### ISSUE TITLE
update to vnstat2

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#140]
Reminder for pkg to test :)

**Comment by mimugmail** [comment]
No need to build an extra pkg, was able to build from ports update.
Testing now ... thx

**Comment by fichtner** [comment]
wow, you're quick. PS: we also have this issue to track https://github.com/opnsense/ports/issues/70

**Comment by mimugmail** [comment]
I think we need 2.2:
https://github.com/vergoh/vnstat/blob/master/CHANGES#L27-L28

In the output only default interface is listed no matter if I choose different.
But when query database it can also list others.

**Comment by fichtner** [comment]
that means revert for now, try to update FreeBSD first?

**Comment by mimugmail** [comment]
Yep
