### ISSUE TITLE
remove darkstat

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#143]
Last update 4 years old:
https://unix4lyfe.org/darkstat/

Quite sure this is a legacy pkg from pf. We have quite a few alternatives like Insight or netdata or ntopng.

**Comment by fichtner** [comment]
Yes and no, it was an early request when we did not have plugins yet 5a6fdde274204d

**Comment by fabianfrz** [comment]
darkstat / vnstat are there because they are quite small (also have a small memory footprint) and have been requested at the forum.

**Comment by fichtner** [comment]
Nevertheless, @mimugmail is right... we should try without. Very happy about getting rid of packages. Mostly we just add them and slow down the build further :(

**Comment by fabianfrz** [comment]
@fichtner I would have delayed that at least to the next major version.

**Comment by fichtner** [comment]
We can always bring it back, there's no real harm associated.

**Comment by mimugmail** [comment]
For me it's a bit of concern to offer unmaintained software on a Firewall.

**Comment by AdSchellevis** [comment]
I think we had a customer for it back in the day, but there are better alternatives now. no harm done indeed.
