### ISSUE TITLE
Discussion: integrate samba?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#144]
With Samba we could allow domain join for freeradius and probably also other daemons. I'm open for both ... 

https://www.unixmen.com/freeradius-active-directory-integration-with-ntlm-mschap/

**Comment by AdSchellevis** [comment]
It will likely complicate things a lot, samba is quite an extensive package which probably has quite some security implications when installed on your primary firewall.
What should be the goals to reach to add this? Maybe there are more lightweight alternatives available for specific use-cases.

**Comment by AdSchellevis** [comment]
did a quick scan online, if a domain join is needed there don't seem to be a lot of other options.
@fichtner knows better what the impact on the build is. 

If a samba plugin is added, it's likely a good idea to make sure some basic test tools are integrated as well in the ui (domain join status, auth tester, etc). Things tend to get complicated pretty quick there (which could just be my opinion).

**Comment by fabianfrz** [comment]
@mimugmail I see the biggest advantage in SMB (CIFS) support ;)

**Comment by mimugmail** [comment]
I'm not really interested in hosting a domain or shares. But ntlm_auth needs Samba. And you cant do MSCHAP within EAP against LDAP. E.g. when using LDAP connector in Freeradius Plugin only works for Openvpn but EAP requires a secured connection. Perhaps Squid plugins could also benefit or kerberos join? As I said, I dont insist on it, just wanted to start a discussion.

**Comment by fichtner** [comment]
Can't this be implemented with https://linux.die.net/man/1/msktutil as usual? I agree that we will have samba eventually, but it's going to be a big impact on our packages ecosystem to be carried out some time into 19.7.x.

**Comment by mimugmail** [comment]
I dont think msktutil will work as most implementations depend on ntlm_auth tool. Maybe this one will also fit but I havent tested it yet:

https://www.freshports.org/security/py-ntlm-auth

**Comment by juliocbc** [comment]
Just to share our experience with Samba: 
We have samba 4 implemented on OPNsense to work with our Web Filter plugin (ntlm auth) and it's working very well for the last 3 years without any issue.

**Comment by mimugmail** [comment]
Cool, maybe you can check If it works with the Python lightweight Version too?

**Comment by juliocbc** [comment]
Good ideia @mimugmail, I'll include in my TODO list.

**Comment by mimugmail** [comment]
@juliocbc did already find the time to test it? :)

**Comment by juliocbc** [comment]
Hi @mimugmail! Unfortunately not. For this kind of task I don't have any backup here, I expect to do it until the end of this month.

**Comment by mimugmail** [comment]
Closing this one, maybe I find something easier to handle this

**Comment by bradleeedmondson** [comment]
Setting aside actual file sharing (CIFS/SMB), there could be a benefit/rationale to packaging Samba purely as a WINS server for proxying WINS queries to DNS. Shouldn't be needed in most cases (regular DNS should be fine), but some embedded devices expect to see a WINS server and won't query DNS for the hostname in a \\hostname\share_name scenario. Adding a Samba plugin with no options, just a WINS proxy to DNS, would extend LAN-side DNS without (necessarily) implicating security and performance of CIFS/SMB shares.
