### ISSUE TITLE
add e2guardian as squidguard alternative

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#148]
http://e2guardian.org/cms/index.php

Same features as squidguard which is often requested but active developed. 

I'd build a plugin around it.

The compilation breaks via ports, not sure how it impacts build time.

**Comment by fichtner** [comment]
seems to be active https://github.com/e2guardian/e2guardian/releases so it is worth a try

**Comment by mimugmail** [comment]
ping :)
