### ISSUE TITLE
make update on ZFS root fails to remove a directory that is in fact a dataset : /usr/ports

### ISSUE THREAD

**Issue by johnr14** [opnsense/tools#149]
Opnsense bootstraped from Freebsd so I can have a rootfs in ZFS.

That means that /usr/ports is a ZFS dataset and can't be deleted !

So I get this error for `make update` : 
>>> Removing /usr/ports... rm: /usr/ports: Device busy
*** Error code 1

I decided to  fix it by destroying the datasets
```
zfs destroy /usr/ports
zfs destroy /usr/src
```

It's also mentioned here : https://forum.opnsense.org/index.php?topic=7934.0

Could it be fixed it so it can just make the directory empty ? 
Will ZFS root install be a goal for next release ?
Thanks

**Comment by fichtner** [comment]
As we don't do ZFS builders (which seemed to decrease build performance) we're currently not looking into extending support to these special mount points.
