### ISSUE TITLE
enable LibreSSL build for os-sunnyvalley

### ISSUE THREAD

**Issue by muratbalaban43** [opnsense/tools#151]
I suggest we enable the LibreSSL build for os-sensei; since os-sensei does not specifically depend on OpenSSL/LibreSSL for now. The same holds true for elasticsearch5.

Pull request: https://github.com/opnsense/tools/pull/150

**Comment by AdSchellevis** [comment]
@muratbalaban43 I'm not sure we want to enable elasticsearch5 on LibreSSL, if I'm not mistaken it costs quite some time to build and I don't know what the overall quality is with LibreSSL (if if breaks often, it costs us quite some time to fix)

I'll leave the issue for @fichtner to decide, personally I favour OpenSSL (don't mind skipping some support for LibreSSL) and most of the issues land on Franco's plate...

**Comment by muratbalaban43** [comment]
@AdSchellevis we're building & shipping the elasticsearch5 packages along with os-sensei.

**Comment by AdSchellevis** [comment]
@muratbalaban43 my mistake, I totally overlooked the # in front of our package... 

```
#textproc/elasticsearch5			arm,arm64,i386,LibreSSL
```

If your building for both variants, I don't mind adding it to the list.

**Comment by muratbalaban43** [comment]
@AdSchellevis , correct. People have been using os-sensei on amd64/LibreSSL for some time now.

**Comment by AdSchellevis** [comment]
done.

**Comment by muratbalaban43** [comment]
Thanks 👍

**Comment by fichtner** [comment]
IMO Ad‘s initial reservations were correct and this can’t be fixed by simply overlaying an OpenSSL build over LibreSSL unless you use the OpenSSL base version maybe (this is what we have for FreeBSD package compat anyway).

**Comment by muratbalaban43** [comment]
Let's start the process for a separate build here. Will keep you updated.
