### ISSUE TITLE
arm support for 20.1

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#153]
Hello, what is the status for arm development in 20.1? Will the support for arm 32 bit dropped from this version or users can still use opnsense/tools to build 32 bit image for arm? 

[Bananapi R2](http://www.banana-pi.org/r2.html) uses arm 32 bit, so I bought one with almost the same specs, [NanoPi R1](https://www.friendlyarm.com/index.php?route=product/product&path=69&product_id=248) and hope to continue contributing in arm tools.

**Comment by cioby23** [comment]
I would love to see Opnsense running on BananaPi R2.

**Comment by fichtner** [comment]
We've decided to move to releng/12.1 of HardenedBSD/FreeBSD now that is has been created a few days ago, which means OPNsense 20.1 should be on the actual 12.1 when it comes out. This will create more ARM work, but I'm sure we can figure this out together. I'll close this ticket as questio has been answered an no immediate work is needed at the moment.
