### ISSUE TITLE
Saving current build progress state

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#154]
I would like to ask a new feature. Can the script remember what was the last packages were successfully build, in case of power failure, it can resume the build without the need to start from the beginning.

Maybe this can be use to cut the time needed to build the future releases where there's no version update for the packages, thus skipping the build and proceeds to next packages that has new version and needed to be build.

**Comment by fichtner** [comment]
Sorry for late reply. Basically: a crash is a crash is a crash. :)

Between base, kernel, ports, plugins, core and sets caching works fine.

If you hit CTRL+C it will retain your progress for "ports". But this is a manual choice, not implicit. All other scripts will abort.

Another thing to keep in mind is the resulting file system corruption itself: even if you could use partial progress you don't know which files were damaged after crash so it's not wise to try and continue.


Cheers,
Franco

**Comment by nekoprog** [comment]
Understood. Will try that next time.
