### ISSUE TITLE
Include py37-pip and dns-lexicon

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/tools#156]
Related to https://github.com/opnsense/plugins/pull/1524 about acme-client, I was wondering if py37-pip and dns-lexicon can be added to the main distribution?

It would be better to avoid manual installation as this will likely make a restore more complicated. Also, I think manual additions are to be avoided in favor of a smooth OPNsense upgrade procedure.

**Comment by jpawlowski** [comment]
Sure, dns-lexicon can be added standalone. Packaging would need to be done manually though, not sure you do it anyway.

**Comment by AdSchellevis** [comment]
which python packages do you need? maybe there is already a port package for it

**Comment by AdSchellevis** [comment]
which python packages do you need? maybe there is already a port package for it

**Comment by jpawlowski** [comment]
It should be called dns-lexicon

**Comment by AdSchellevis** [comment]
this https://github.com/opnsense/ports/blob/master/dns/py-dns-lexicon ?

**Comment by jpawlowski** [comment]
Yes, this seems right. However, it does not seem to be installed by default. Also, it is not available from the index it seems:

````
shell
root@gwsch03:~ # pkg search py-dns-lexicon
root@gwsch03:~ #
````

This is why I had to install it via `pip`. Maybe there is something I didn't look for?
As the intended functionality of acme-client won't be complete without this package, can it be made a required dependency of the acme-client package?

**Comment by AdSchellevis** [comment]
you need to install it via the ports tree, best check the readme of this repository on how to checkout sources, then go to /usr/ports/.... and a `make install` should probably lead to the correct result. When acme-client will depend on it, we do indeed need to add it as a dependency there.

**Comment by AdSchellevis** [comment]
(by the way, no need to worry to much about this, if this is the only extra dependancy, it shouldn't be too much of a hassle to build a package for you)

**Comment by jpawlowski** [comment]
I tried to build the package on that particular machine. However, I did interrupt the process because it seems that it would actually also build Python version 3.6 as a dependency while the system actually comes with Python 3.7. The dependency comes from Python setuptools which is already installed as `py37-setuptools-41.2.0` so obviously the dependencies are not correct here.

Also, it would give me some warnings where I'm not sure how to react on it:

````shell
/!\ WARNING /!\

You have security/openssl installed but do not have
DEFAULT_VERSIONS+=ssl=openssl set in your make.conf
````

**Comment by AdSchellevis** [comment]
better leave it for now then, link this issue in your PR, so we know it's being blocked by this.

**Comment by fichtner** [comment]
Try again after this:

    # opnsense-code tools

Cheers,
Franco

**Comment by jpawlowski** [comment]
Thanks, Franco! This would do the trick.

**Comment by fraenki** [comment]
Are we going to add `dns/py-dns-lexicon` to `ports.conf` for 19.7 and beyond? It's small enough that it could then be added as a dependency to our os-acme-client plugin (I'll take care of it).

Otherwise Lexicon support in acme.sh would be nonfunctional and should probably be removed completely instead of merging PR https://github.com/opnsense/plugins/pull/1524. Apparently, I wasn't aware when merging the first Lexicon additions back then... :-/
