### ISSUE TITLE
make packages went idle, rust as culprit?

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#157]
I have removed lang/rust from config, but it still tries to make rust packages and then CPU went idle. How to skip it? And why is Rust being compiled even it's not on config?

This is where the compiling begin
`/usr/obj/usr/ports/lang/rust/work/rustc-1.38.0-src`

**Comment by fichtner** [comment]
rust is required by suricata. remove suricata-devel from ports.conf and add RUST to OPTIONS_UNSET in make.conf

**Comment by nekoprog** [comment]
Thanks, will try it again.

**Comment by DarkSunOne** [comment]
Same problem here, any success with removing suricata?
But i think thats the wrong way ... any ideas why rust gets stuck?

One time i got an "LLVM out of memory" ... Build VM hat 12GB Ram, currently retrying with 20GB

**Comment by nekoprog** [comment]
Yes, after commenting out suricata-devel, make packages run successfully.

**Comment by fichtner** [comment]
This is solved  then. We have to find a proper solution at some point but for now that's not important and it gets worse with suricata 5 where rust will be a requirement...

**Comment by nekoprog** [comment]
For future reference: [emulators/qemu-user-static: fails to run lang/rust](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221185)
