### ISSUE TITLE
[Cross build ARM] 20.1 config ready to be use?

### ISSUE THREAD

**Issue by nekoprog** [opnsense/tools#158]
Just wondering if it's okay to build using 20.1 config, because I encounter some error when running `make base SETTINGS=20.1` with FreeBSD 12.0. Looks like the base.txz not found, but the script was looking at wrong directory where it supposed to look at `STAGEDIR/usr/src`, but it went to host `/usr/src`.

Will update the error with log later, I just close my VM.

**Comment by fichtner** [comment]
src.git master is 12.1 and I haven't seen that issue so yes you can use 20.1, but please use our src.git

**Comment by nekoprog** [comment]
this is the error that i found

![20 1-error](https://user-images.githubusercontent.com/2550618/66701531-9f196c00-ed2f-11e9-9396-c39f459140f7.jpg)

**Comment by fichtner** [comment]
Hmmm, maybe it's different now for cross vs. native builds?

**Comment by nekoprog** [comment]
I can confirm that the error occurs only when using FreeBSD 12.1 BETA release as host, error for both 19.7 and 20.1

No such error when using FreeBSD 11.2 as host.

**Comment by DarkSunOne** [comment]
Same here on a fresh installed 20.1 ... 19.7 worked fine on bsd 11.2 

![image](https://user-images.githubusercontent.com/11734245/67159671-270eff80-f348-11e9-8a20-d7e00b364d2c.png)

**Comment by fichtner** [comment]
This is also a cross build, isn't it? If you can reproduce you can fix. I'm not at the point to look at this yet.

**Comment by nekoprog** [comment]
Yes, cross build issue. Maybe there are some changes in chroot, buildworld, buildkernel, etc. But don't have spare time to debug yet.

**Comment by DarkSunOne** [comment]
Thanks for the hint, i think i fixed it ...
first compile looks good so far, but need some time to test, if it actually works (boot and so on)

Will create a pr when finished

**Comment by fichtner** [comment]
very nice, thanks in advance! ❤️

**Comment by nekoprog** [comment]
Nice, looking forward for a fix.

**Comment by DarkSunOne** [comment]
base and kernel looks good so far, but didn't tested with 19.7 settings a.t.m ...

struggling around with xtools and packages now ... i think i'll try to add native cross compiler support, without all that qemu stuff... as far i found out, this should be possible with bsd12 :-) but still facing strange toolchain errors :-(

**Comment by DarkSunOne** [comment]
Little update: compiling base, kernel and xtools works ... trying to fix packages now

**Comment by DarkSunOne** [comment]
i think i am very close now.

My current problem is, that the pkg-list is not generated in my stagedir/.pkg/All

Anyone an idea?

![image](https://user-images.githubusercontent.com/11734245/67460166-9cc1e680-f63a-11e9-8b32-f7f0616b48b8.png)

**Comment by nekoprog** [comment]
You need to trace PACKAGESDIR from build/common.sh. There are many steps involving *_packages(). If error on make packages, you can start from [extract_packages()](https://github.com/opnsense/tools/blob/master/build/common.sh#L676)

**Comment by DarkSunOne** [comment]
thanks for the hint again.

in fact there was a problem in the configdir/make.conf ... compiling ports now :-)

**Comment by DarkSunOne** [comment]
Ran straight into the next bug :-(

The compiling process hangs at "checking whether printf survives out-of-memory conditions..."

Seems to be this bug: 
[https://lists.freebsd.org/pipermail/freebsd-ports/2017-December/112090.html](https://lists.freebsd.org/pipermail/freebsd-ports/2017-December/112090.html)
[https://lists.gnu.org/archive/html/qemu-devel/2015-02/msg05584.html](https://lists.gnu.org/archive/html/qemu-devel/2015-02/msg05584.html)

**Comment by nekoprog** [comment]
I need more time to investigate what happen from this [commit](https://github.com/opnsense/src/commit/41ba6e29a8d3f862f95f9ab0a1482ef58c4a7cdb). It seems like somewhere in SRCDIR/Makefile, buildworld is messing up with cross build env.

**Comment by DarkSunOne** [comment]
Did your package build finished? 

On armv7 it kicks me out at openssl with the message, that my compiler doesnt support 128bit integer and on arm64 (rpi3) it cant compile lang/rust :-(

Building on 12.1 RC2

**Comment by nekoprog** [comment]
Nah, stuck at make xtools. It's says nxb-bin not found and it just generating xtools.txz with zero byte. Will look at it later.

**Comment by DarkSunOne** [comment]
Look at my fork, already fixed it there

**Comment by nekoprog** [comment]
[Line 119](https://github.com/opnsense/tools/blob/master/build/ports.sh#L119) produces this error:
```
make: "/etc/make.conf" line 0: 1 open conditional
make: Fatal errors encountered -- cannot continue
[: make:: unexpected operator
```

I don't know why it says line 0 has 1 open conditional. So I stuck at make packages. We are almost there @DarkSunOne.

**Comment by DarkSunOne** [comment]
Take the Makefile.inc1 from my tools fork and put it in your /usr/src dir :-)

**Comment by DarkSunOne** [comment]
Next little process :-)
packages succeeded, struggling around with core now, saying that suricata-devel was not found (commented out [cause of this](https://github.com/opnsense/tools/issues/157#event-2704988640)

**Comment by fichtner** [comment]
I removed suricata/rust from arm in tools.git and core.git. Please update your branches.

**Comment by DarkSunOne** [comment]
Is a "clean-packages" necessary?
I did so cause it still complained that suricata-devel is missing (with updated branches)

**Comment by fichtner** [comment]
This should do the trick after repo updates:

    # make hotfix

**Comment by fichtner** [comment]
Can’t be, did you update core.git ?

**Comment by DarkSunOne** [comment]
I manually merged the changes to my files, shouldn't be a problem?

**Comment by fichtner** [comment]
Well, unless architectures are i386 or amd64 suricata-devel shouldn't be a core dependency anymore:

https://github.com/opnsense/core/commit/f098b3a9ba

**Comment by DarkSunOne** [comment]
Maybe a problem with target detection?
Currently compiling for armv7 on an amd64 host

**Comment by fichtner** [comment]
I don't understand. core.git depends on suricata-devel, but if you not build i386 or amd64 it won't use suricata-devel anymore as per the referenced source commit. Make sure the core.git master branch is in sync and checked in.

**Comment by nekoprog** [comment]
I don't have any problem with suricata-devel and rust. How did you run your build @DarkSunOne? Did you include DEVICE argument?

**Comment by fichtner** [comment]
Created a portable fix for the xtools on version 12: a60abedda

**Comment by DarkSunOne** [comment]
Perfect, got all sets ready to go.

Currently stuck at make arm, complaining that package os-dyndns is not found, even if its there.

If you dont have time, i will look at it in 2-3 days

**Comment by nekoprog** [comment]
> Ran straight into the next bug :-(
> 
> The compiling process hangs at "checking whether printf survives out-of-memory conditions..."
> 
> Seems to be this bug:
> https://lists.freebsd.org/pipermail/freebsd-ports/2017-December/112090.html
> https://lists.gnu.org/archive/html/qemu-devel/2015-02/msg05584.html
> 
> Edit: found out, that the build continues when i send a kill -9 to the stuck process

@fichtner How to implement this globally? I tried pasting it inside config/20.1/make.conf, but qemu-arm-static still hangs on ports/m4. Need to manually kill `qemu-arm-static ./conftest` so that build continues.

```
.ifdef QEMU_EMULATING
# XXX bug 224740: configure hangs: GSlice: failed to allocate 496 bytes (alignment: 512)
CONFIGURE_ENV+= gl_cv_func_printf_enomem=no
.endif
```

@DarkSunOne Last time I got an error about os-dyndns not found, I just ran `make packages` again.

**Comment by dgktkr** [comment]
opnsense/src master is HardenedBSD on top of FreeBSD 12.1? I've looked at the online display of the file sys/conf/options and there seem to be no PAX_* options present. I also cloned the whole OPNSense src.git tree to my computer and the PAX_* options also are absent from sys/conf/options. Am I doing something wrong?

**Comment by nekoprog** [comment]
> opnsense/src master is HardenedBSD on top of FreeBSD 12.1? I've looked at the online display of the file sys/conf/options and there seem to be no PAX_* entries present. As a confirmation, I cloned the whole OPNSense src.git tree manually to another computer and the PAX_* kernel options are also absent from sys/conf/options. Am I doing something wrong?
> 
> Interestingly enough, in GitHub opnsense/src/sys/conf/options for branch stable/19.7 there are lots of PAX_* kernel options.

Maybe they still patching for the upcoming 12.1 stable release which is tomorrow.

**Comment by fichtner** [comment]
Src.git master is a work in progress. Currently we have FreeBSD releng/12.1 there. HardenedBSD is not yet imported due to merge conflicts between the two.

**Comment by nekoprog** [comment]
I will close this issue for now since all sets have been build successfully on my [fork](https://github.com/nekoprog/tools). Bugs regarding qemu has been submitted on [bugzilla](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224740).

Hoping to see openssl111 on arm next. Since current compiler doesn't support 128-bit integer when compiling. Also miniupnpd is unable to be compiled in OPNsense 20.1, hope to see that fixed too.

**Comment by fichtner** [comment]
We could prefer LibreSSL for ARM. And I think I know the issue for miniupnpd... https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=233963 ... right now we have a patch because on FreeBSD 11 the build is broken... ;)

**Comment by nekoprog** [comment]
Nice, can't wait for the HBSD patch. Will test tools.git again after that.

**Comment by DarkSunOne** [comment]
Openssl works, even with arm and 20.1 settings, you just have to disable the 128bit compiler support in the makefile of openssl.

For miniupnpd there you just have to disable a port check feature which was removed from FreeBSD 12, i dont remember the exact settings, will post the links tomorrow.

**Comment by dgktkr** [comment]
> Openssl works, even with arm and 20.1 settings, you just have to disable the 128bit compiler support in the makefile of openssl.
> 
> For miniupnpd there you just have to disable a port check feature which was removed from FreeBSD 12, i dont remember the exact settings, will post the links tomorrow.

DarkSunOne, how exactly do you deal with miniupnp? After 8 hours of working on the packages set, my build errors out because 

> Could not find package: miniupnp

**Comment by nekoprog** [comment]
You need to add ignore arm,arm64 to plugins.conf/upnp and ports.conf/miniupnpd

**Comment by DarkSunOne** [comment]
@dgktkr or you remove CHECK_PORTINUSE in the make.conf

**Comment by fichtner** [comment]
Or simply delete net/miniupnpd/files/patch-portinuse.c and commit ;)

**Comment by fichtner** [comment]
Due to popular demand I applied a fix: https://github.com/opnsense/ports/commit/eefcea86384

(the patch in the upstream FreeBSD ticket didn't work for me)

**Comment by DarkSunOne** [comment]
Perfect, thanks :-)

**Comment by nekoprog** [comment]
Thanks a lot.

**Comment by dgktkr** [comment]
I've run into another snag when building kernel modules for the kernel target:

> ...
/usr/local/arm-gnueabi-freebsd12.0/bin/ld -m armelf_fbsd -d -warn-common --build-id=sha1 -r -d -o cloudabi32.kld cloudabi32_vdso_blob.o cloudabi32_fd.o cloudabi32_module.o cloudabi>
/usr/local/arm-gnueabi-freebsd12.0/bin/ld: error: source object cloudabi32_fd.o has EABI version 5, but target cloudabi32.kld has EABI version 0
/usr/local/arm-gnueabi-freebsd12.0/bin/ld: failed to merge target specific data of file cloudabi32_fd.o
...



It seems curious that quite a few .kld files are built before the cloudabi32.kld build fails. 

I wondered whether the problem also occurs when building from stock FreeBSD source  or whether OPNsense modifications are the cause. So I did an experiment: A build of the kernel for ClearFog using Github FreeBSD source release/12.1.0 and KERNCONF=ARMADA38X proceeds and completes without error. So it does appear that something in OPNsense's src.git is the culprit.

I also wonder why no-one else seems to have encountered this problem.

Does anyone have ideas or insights that might be helpful here?

**Comment by DarkSunOne** [comment]
I had the same error.

Are you building on 12.1?
Which device config are you using for building opnsense?

**Comment by dgktkr** [comment]
> I had the same error.
> 
> Are you building on 12.1?

The host system is 12.1-RC2. Same results with the host being release/12.1.0.

About a week ago Franco wrote that src.git was releng/12.1. The src.git I have is 3 days old. So the target system should be 12.1 also.

> Which device config are you using for building opnsense?

CLEARFOG.conf, which is a modified BANANAPI.conf. I'm also using tools from OPNsense (not nekoprog).

**Comment by DarkSunOne** [comment]
> Were you able to solve this problem for your sg3100?
yes.

Try my device config: https://github.com/DarkSunOne/tools/blob/master/device/ARMADA38X.conf
i extracted the [/usr/usg3100/boot](https://github.com/DarkSunOne/tools/blob/b77d902d27fc7f41998e7e78d283d72df3c3aa33/device/ARMADA38X.conf#L10) folder from the running pfsense image on the sg3100.

You also need to get the Netgate dts file for your kernel, you can grab it [here](https://github.com/DarkSunOne/src/commit/4c5e8fa2a260c0d636fff33b7ecbe79b16785468#diff-8f08c0275632ffbfc247d3f391f14c90)

You also need a slightly changed kernel config, try it with [that one](https://github.com/DarkSunOne/src/commit/7a341b60936eef1247e5bb96268f77b07925ebe3#diff-4a359dca10e7fee729d06bc6406ae2e0)

**Comment by dgktkr** [comment]
> > Were you able to solve this problem for your sg3100?
> 
> yes.
> 
> Try my device config: https://github.com/DarkSunOne/tools/blob/master/device/ARMADA38X.conf
> i extracted the [/usr/usg3100/boot](https://github.com/DarkSunOne/tools/blob/b77d902d27fc7f41998e7e78d283d72df3c3aa33/device/ARMADA38X.conf#L10) folder from the running pfsense image on the sg3100.
> 
> You also need to get the Netgate dts file for your kernel, you can grab it [here](https://github.com/DarkSunOne/src/commit/4c5e8fa2a260c0d636fff33b7ecbe79b16785468#diff-8f08c0275632ffbfc247d3f391f14c90)
> 
> You also need a slightly changed kernel config, try it with [that one](https://github.com/DarkSunOne/src/commit/7a341b60936eef1247e5bb96268f77b07925ebe3#diff-4a359dca10e7fee729d06bc6406ae2e0)
> 
> My SG3100 already runs with opnsense, but theres still a lot of work :-(

Hi Rene_,

Thanks for the suggestions. Changing the toolchain did indeed solve the EABI version mismatch problem. Now the build dies with undefined symbols (xz_dec_init, xz_dec_run, xz_dec_end) while linking the kernel. I'm sure it will take me a while to resolve that.

**Comment by DarkSunOne** [comment]
Hi,
Maybe the kernel config?
As said i copied the 'default' ARMADA38X config to SMP-ARMADA38X, and changed the last lines (regarding the fdt settings)
You also NEED the right dtb file!
Else the kernel wont boot.

Let me know if you need something :)

**Comment by dgktkr** [comment]
> Hi,
> Maybe the kernel config?
> As said i copied the 'default' ARMADA38X config to SMP-ARMADA38X, and changed the last lines (regarding the fdt settings)
> You also NEED the right dtb file!
> Else the kernel wont boot.
> 
> Let me know if you need something :)

Will do! I think I have the boot stuff sorted. Once I install the image on the device SSD, I'll copy over proper dtb and ubldr files to their proper places and manually dd known good boot bits to the start of the drive.

**Comment by dgktkr** [comment]
With the suggestions given in this thread, I've gotten base, kernel, tools, packages and arm to build to completion, but there are two things of note that I've encountered.

1) This may be a cosmetic problem, but the packages set is called 

> packages-19.7.6_102-OpenSSL-armv7.tar

even though `SETTINGS?=	20.1` is in /usr/tools/Makfile. The other sets have the expected names, for instance, 

> kernel-20.1.a_93-armv7-CLEARFOG.txz

2) I can boot the image built with `make arm`, but the kernel refuses to run /bin/sh, complaining: `can't exec /bin/sh for /etc/rc: Exec format error`. So, first I checked the boot/kernel/kernel in the image:

> file ../boot/kernel/kernel
>../boot/kernel/kernel: ELF 32-bit LSB executable, ARM, EABI5 version 1 (FreeBSD), dynamically >linked, interpreter /red/herring, BuildID[sha1]=fe91ba8f364ffe32a24cf99754aa14d85cfb3f94, >for FreeBSD 12.1, not stripped

Then I checked /bin/sh in the image:

> file sh
>sh: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), statically linked, for FreeBSD 12.1, >FreeBSD-style, stripped

How'd that happen?  A sampling of executables in the image /bin all are for 64 bit x86-64. A sampling of libraries in the image /lib are all 32 bit ARM EABI5. A sampling of executables in the image /sbin are also all 32 bit ARM EABI5. A sampling of executables in the image /usr/bin: some are 32 bit ARM EABI5 (crypt, top, tip) and some are x86-64 (objcopy, objdump)

So why is some code being compiled as x86-64 and some as 32 bit ARM?

**Comment by DarkSunOne** [comment]
Theres something wrong with your build environment, or how you use it.

First of all i would suggest you to stop build with DEVIVE=CLEARFOG ... as i remember you want to build for the netgate sg3100, this board is Marvell Armada385 based, and the configs for this board, especially the kernel defconfog is already there (/usr/src/sys/arm/conf/ARMADA38X)

Next one is, dont change the Makefile, use SETTINGS=20.1 in your commands.
You even need to 'make update SETTINGS=20.1' to get the latest (FreeBSD12.1 based) source.

Regarding step 3 ... i didnt need that, arm builds very well even with that line, what is the error message with that line included?

**Comment by dgktkr** [comment]
> Theres something wrong with your build environment, or how you use it.
> 
> Package name is as you said just cosmetic, they work on all my builds
> 
> First of all i would suggest you to stop build with DEVICE=CLEARFOG ... as i remember you want to build for the netgate sg3100, this board is Marvell Armada385 based, and the configs for this board, especially the kernel defconfog is already there (/usr/src/sys/arm/conf/ARMADA38X)

The board I'm trying to build for is the SolidRun ClearFog Base [https://developer.solid-run.com/products/clearfog-base/](url) I have custom KERNCONF and dtb files that work well with a plain vanilla build of FreeBSD 12.1 on this board.

> 
> Next one is, dont change the Makefile, better use SETTINGS=20.1 in your commands.

This is worth looking into.

> You even need to 'make update SETTINGS=20.1' to get the latest (FreeBSD12.1 based) source.
> 
> Regarding step 3 ... i didnt need that, arm builds very well even with that line, what is the error message with that line included?

The same one you mentioned in a post about 2 weeks ago. [https://github.com/opnsense/tools/issues/158#issuecomment-547962551](url)

**Comment by DarkSunOne** [comment]
> The board I'm trying to build for is the SolidRun ClearFog Base [https://developer.solid-run.com/products/clearfog-base/](url) I have custom KERNCONF and dtb files that work well with a plain vanilla build of FreeBSD 12.1 on this board.

Oh sorry, my fault.

> The same one you encountered in this thread about 2 weeks ago. About halfway between here and the original post: When executing `make arm`, the build errors out with
> 
> > Could not find package: os-dyndns

I found a better fix, you just need to remove "[0-9]" [here](https://github.com/opnsense/tools/blob/master/build/common.sh#L811) and [here](https://github.com/opnsense/tools/blob/master/build/common.sh#L814) 
will create a pr later

**Comment by dgktkr** [comment]
> Next one is, dont change the Makefile, better use SETTINGS=20.1 in your commands.

Hi Rene_,

Thank you ever so much. Again, your suggestion solved my problem! The web GUI is currently running on my ClearFog Base.

Take care

**Comment by dgktkr** [comment]
OK. I have the webGUI running on my board, but the console goes unresponsive after showing: 

>  Invoking start script 'beep'
>
>Root file system: /dev/ufs/OPNsense
>Wed Nov 13 18:09:26 UTC 2019
>
>*** OPNsense.localdomain: OPNsense 20.1.a_241 (armv7/OpenSSL) ***
>
 >LAN (mvneta0)   -> v4: 192.168.1.1/24
 >WAN (mvneta1)   -> 
>
 >HTTPS: SHA256 EF 39 4D 05 D1 51 CF A2 7C AE 23 5C 12 60 CD C8
 >             DD 0B 38 AC D6 E0 5D 60 74 8C E3 7E BE A9 93 7E

Is the console supposed to do that or is this a dtb problem?

**Comment by DarkSunOne** [comment]
Nice work :+1: 

Probably the exact problem i'm facing currently, already explained [here](https://github.com/opnsense/tools/issues/162)

My workaround is to change [this line](https://github.com/opnsense/core/blob/b1702d0c0a12758df069e294dfd72cf9300191d8/src/etc/rc#L201) to 
`/usr/local/sbin/opnsense-shell`

You can also enable ssh over the webgui, enable ssh, and change the line directly under /usr/local/etc/rc

**Comment by dgktkr** [comment]
Hi guys,

OPNsense has been running on my arm device for a couple of days now and so far most features are functioning as expected. Thank you nekoprog and Rene_ for your help.

One thing that isn't working as expected is logging for pf, so I'd like to ask a favor of nekoprog and/or Rene_: could you check and see if pf logging is working for you, or are **Live View** **Overview** and **Plain View** empty and **clog /var/log/filter.log** shows nothing. I'm wondering if I'm the only one with this issue.

**Comment by DarkSunOne** [comment]
Hi,

Perfect :smiley: 

i will look at this the next days :+1:

**Comment by nekoprog** [comment]
> Hi guys,
> 
> OPNsense has been running on my arm device for a couple of days now and so far most features are functioning as expected. Thank you nekoprog and Rene_ for your help.
> 
> One thing that isn't working as expected is logging for pf, so I'd like to ask a favor of nekoprog and/or Rene_: could you check and see if pf logging is working for you, or are **Live View**, **Overview** and **Plain View** empty with **clog /var/log/filter.log** showing nothing. I'm wondering if I'm the only one with this issue.

Hi, can you open new issue regarding this pf log not functioning? It will help others who look for solution with the same issue next time. :)

**Comment by dgktkr** [comment]
> 
> Hi, can you open new issue regarding this pf log not functioning at opnsense/core? It will help others who look for solution with the same issue next time. :)

I posted on another forum hoping someone would have insight into the problem: [https://forum.opnsense.org/index.php?topic=15036.0](url)

Franco replied, indicating that since I was working with OPNsense 20.1, FreeBSD 12.1 and arm, I was on my own.

Well, I accepted the challenge and looked into the matter anticipating that it would save someone else some time.

I'm pretty sure I've found the cause of the issue and have implemented a solution that works for me.

The first hint came with a reading of /usr/src/UPDATING : 

       20180406:
        In addition to supporting RFC 3164 formatted messages, the
        syslogd(8) service is now capable of parsing RFC 5424 formatted
        log messages. The main benefit of using RFC 5424 is that clients
        may now send log messages with timestamps containing year numbers,
        microseconds and time zone offsets.
        
        Similarly, the syslog(3) C library function has been altered to
        send RFC 5424 formatted messages to the local system logging
        daemon. On systems using syslogd(8), this change should have no
        negative impact, as long as syslogd(8) and the C library are
        updated at the same time. On systems using a different system
        logging daemon, it may be necessary to make configuration
        adjustments, depending on the software used.
        
        When using syslog-ng, add the 'syslog-protocol' flag to local
        input sources to enable parsing of RFC 5424 formatted messages:

                source src {
                        unix-dgram("/var/run/log" flags(syslog-protocol));
                }
        
        When using rsyslog, disable the 'SysSock.UseSpecialParser' option
        of the 'imuxsock' module to let messages be processed by the
        regular RFC 3164/5424 parsing pipeline:

                module(load="imuxsock" SysSock.UseSpecialParser="off")

        Do note that these changes only affect communication between local
        applications and syslogd(8). The format that syslogd(8) uses to
        store messages on disk or forward messages to other systems
        remains unchanged. syslogd(8) still uses RFC 3164 for these
        purposes. Options to customize this behaviour will be added in the
        future. Utilities that process log files stored in /var/log are
        thus expected to continue to function as before.

        __FreeBSD_version has been incremented to 1200061 to denote this
        change.`

Studying the version of syslog.c in FreeBSD 12.1, did, indeed, show that syslog() adds an RFC 5424 formatted header to the log message being sent to syslogd.

Apparently syslogd hasn't been modified to completely accommodate the change and neither has OPNsense. My solution is to revert to the old version of syslog.c, which formats log messages with an RFC 3164 type header. I expect the OPNsense authors will prefer a different solution.

**Comment by nekoprog** [comment]
Don't take it personally. What he meant was that 20.1 and 12.1 build is still in alpha/beta development branch, hence there will be bug along the road. As a tester, you need to address this issue on core.git hoping that core dev will look deeper into this issue. This will surely be fixed on stable 20.1 release next year, still got a few weeks then.

**Comment by dgktkr** [comment]
No worries. One reason I like open source software is that if something bothers me enough I can further develop my coding skills and fix it myself.

@nekoprog, with your encouragement I've opened an issue for OPNsense src.git on GitHub [https://github.com/opnsense/src/issues/49](url) I hope that's the right place to do it.

**Comment by dgktkr** [comment]
FWIW OPNsense src.git has progressed and is now based on HardenedBSD. And it even builds OK.
