### ISSUE TITLE
  nano: dhcpd can't run -> no user dhcpd on system

### ISSUE THREAD

**Issue by lordfinal** [opnsense/tools#16]
After adding the user 'dhcpd' to the system, the dhcp server is able to start. Beforehand no dhcpd can be enabled

tested on nano img: LibreSSL 15.9. amd64

**Comment by fichtner** [comment]
Was fixed in an early 15.7.x. New nano images based on 15.7.10 will be released this week. In the meantime, upgrading the firmware (console option 12) will fix this, too. :)

**Comment by lordfinal** [comment]
Of course I did the upgrade but the user was missing after reboot. But  I will check again. Thanks for the input

**Comment by fichtner** [comment]
That's strange. Can you run /usr/local/etc/rc.recover to see if that brings back the user after a reboot (if it's not already there).

**Comment by fichtner** [comment]
Also, what is the output of

    # pkg info

**Comment by lordfinal** [comment]
root@OPNsense:~ # pkg info
apinger-0.6.1_3                IP device monitoring tool
ataidle-2.7.2                  Utility to spin down ATA drives
beep-1.0_1                     Beeps a certain duration and pitch out of the PC Speaker
bind910-9.10.2P3_1             BIND DNS suite with updated DNSSEC and DNS64
bsdinstaller-2.3_5             BSD Installer mega-package
bsnmp-regex-0.6_1              bsnmpd module allowing creation of counters from log files
bsnmp-ucd-0.4.1                bsnmpd module that implements parts of UCD-SNMP-MIB
ca_root_nss-3.19.2             Root certificate bundle from the Mozilla Project
choparp-20021107_4             Simple proxy arp daemon
clog-1.0.1_3                   Circular log support for FreeBSD syslogd
cpdup-1.17_2                   Comprehensive filesystem mirroring and backup program
cpustats-0.1                   cpustats
curl-7.43.0_2                  Non-interactive tool to get files from FTP, GOPHER, HTTP(S) servers
dhcp6-20080615_2               KAME DHCP6 client, server, and relay
dhcpleases-0.2                 read dhpcd.lease file and add it to hosts file
dnsmasq-2.75,1                 Lightweight DNS forwarder, DHCP, and TFTP server
easy-rsa-2.2.2                 Small RSA key management package based on openssl
expat-2.1.0_3                  XML 1.0 parser written in C
expiretable-0.6_1              Utility to remove entries from the pf(4) table based on their age
filterdns-0.2                  filterdns
filterlog-0.2                  Parse pflog(4) output
freetype2-2.6_1                Free and portable TrueType font rendering engine
gettext-runtime-0.19.5.1       GNU gettext runtime libraries and programs
gmp-5.1.3_2                    Free library for arbitrary precision arithmetic
idnkit-1.0_5                   Library to handle internationalized domain names
ifinfo-10.1                    Interface statistics reader
igmpproxy-0.1_2,1              Multicast forwarding IGMP proxy
indexinfo-0.2.3                Utility to regenerate the GNU info page index
isc-dhcp42-client-4.2.8        The ISC Dynamic Host Configuration Protocol client
isc-dhcp42-relay-4.2.8         The ISC Dynamic Host Configuration Protocol relay
isc-dhcp42-server-4.2.8_1      ISC Dynamic Host Configuration Protocol server
jansson-2.7_1                  C library for encoding, decoding, and manipulating JSON data
libart_lgpl-2.3.21_2,1         Library for high-performance 2D graphics
libdaemon-0.14_1               Lightweight C library that eases the writing of UNIX daemons
libedit-3.1.20150325_1         Command line editor library
libevent2-2.0.22_1             API for executing callback functions on events or timeouts
libffi-3.2.1                   Foreign Function Interface
libhtp-0.5.16                  Security-aware parser for the HTTP protocol
libiconv-1.14_8                Character set conversion library
libltdl-2.4.6                  System independent dlopen wrapper
libmcrypt-2.5.8_3              Multi-cipher cryptographic library (used in PHP)
libnet-1.1.6_3,1               C library for creating IP packets
libpdel-0.5.3_6                Packet Design multi-purpose C library for embedded applications
libressl-2.2.2                 Free version of the SSL/TLS protocol forked from OpenSSL
libxml2-2.9.2_3                XML parser library for GNOME
libyaml-0.1.6_2                YAML 1.1 parser and emitter written in C
lighttpd-1.4.36                Secure, fast, compliant, and flexible Web Server
lzo2-2.09                      Portable speedy, lossless data compression library
minicron-0.0.2                 very small cron
miniupnpd-1.9_1,1              UPnP IGD implementation which uses pf/ipf
mpd4-4.4.1_2                   Multi-link PPP daemon based on netgraph(4)
mpd5-5.7_2                     Multi-link PPP daemon based on netgraph(4)
nettle-2.7.1                   Low-level cryptographic library
ntp-4.2.8p3                    The Network Time Protocol Distribution
oniguruma4-4.7.1_1             BSDL Regular Expressions library compatible with POSIX/GNU/Perl
openldap-client-2.4.41         Open source LDAP client implementation
openssh-portable-6.9.p1_2,1    The portable version of OpenBSD's OpenSSH
openvpn-2.3.8                  Secure IP/Ethernet tunnel daemon
opnsense-15.7.9                OPNsense release package
os-update-15.7.8               OPNsense update utility
pcre-8.37_3                    Perl Compatible Regular Expressions library
pecl-radius-1.2.7              Radius client library for PHP
perl5-5.20.2_5                 Practical Extraction and Report Language
pftop-0.7_4                    Utility for real-time display of statistics for pf
phalcon-2.0.6                  Phalcon PHP Framework written in C-language
php-pfSense-0.2_4              Library for getting useful info
php-suhosin-0.9.37.1_1         PHP extension that implements high-level protections
php-xdebug-2.2.5               Xdebug extension for PHP
php56-5.6.12                   PHP Scripting Language
php56-bcmath-5.6.12            The bcmath shared extension for php
php56-bz2-5.6.12               The bz2 shared extension for php
php56-ctype-5.6.12             The ctype shared extension for php
php56-curl-5.6.12              The curl shared extension for php
php56-dom-5.6.12               The dom shared extension for php
php56-filter-5.6.12            The filter shared extension for php
php56-gettext-5.6.12           The gettext shared extension for php
php56-hash-5.6.12              The hash shared extension for php
php56-json-5.6.12              The json shared extension for php
php56-ldap-5.6.12              The ldap shared extension for php
php56-mbstring-5.6.12          The mbstring shared extension for php
php56-mcrypt-5.6.12            The mcrypt shared extension for php
php56-mysql-5.6.12             The mysql shared extension for php
php56-openssl-5.6.12           The openssl shared extension for php
php56-pdo-5.6.12               The pdo shared extension for php
php56-pdo_sqlite-5.6.12        The pdo_sqlite shared extension for php
php56-session-5.6.12           The session shared extension for php
php56-simplexml-5.6.12         The simplexml shared extension for php
php56-sockets-5.6.12           The sockets shared extension for php
php56-sqlite3-5.6.12           The sqlite3 shared extension for php
php56-tokenizer-5.6.12         The tokenizer shared extension for php
php56-xml-5.6.12               The xml shared extension for php
php56-zlib-5.6.12              The zlib shared extension for php
pkg-1.5.6                      Package manager
png-1.6.17_1                   Library for manipulating PNG images
py27-Babel-2.0                 Collection of tools for internationalizing Python applications
py27-Jinja2-2.7.3              Fast and easy to use stand-alone template engine
py27-MarkupSafe-0.23           Implements a XML/HTML/XHTML Markup safe string for Python
py27-pytz-2015.4,1             World Timezone Definitions for Python
py27-requests-2.7.0            HTTP library written in Python for human beings
py27-setuptools27-17.0         Python packages installer
py27-sqlite3-2.7.10_6          Standard Python binding to the SQLite3 library
py27-ujson-1.33                Ultra fast JSON encoder and decoder for Python
python27-2.7.10                Interpreted object-oriented programming language
radvd-1.9.7                    Linux/BSD IPv6 router advertisement daemon
rate-0.9                       Traffic analysis command-line utility
relayd-5.5.20140810_1          OpenBSD relay daemon
rrdtool12-1.2.30_7             Round Robin Database Tools v1.2
smartmontools-6.4_1            S.M.A.R.T. disk monitoring tools
sqlite3-3.8.10.2               SQL database engine in a C library
squid-3.5.7                    HTTP Caching Proxy
sshlockout_pf-0.0.2_2          Automatically block IPs with failed SSH logins using pf(4)
strongswan-5.3.2               Open Source IKEv2 IPsec-based VPN solution
sudo-1.8.14p3                  Allow others to run commands as root
suricata-2.0.8_1               High Performance Network IDS, IPS and Security Monitoring engine
syslogd-10.1_1                 FreeBSD syslogd with additions
voucher-0.1_4                  voucher support
wol-0.7.1_2                    Tool to wake up Wake-On-LAN compliant computers
zip-3.0_1                      Create/update ZIP files compatible with PKZIP
root@OPNsense:~ #

=============================================================================
But actually this time the dhcpd group wasn't existing. Strange but it works for now.

**Comment by fichtner** [comment]
Ok, in any case new images this week. Sorry about the fuzz. Closing. :)
