### ISSUE TITLE
Sign package set

### ISSUE THREAD

**Issue by DarkSunOne** [opnsense/tools#163]
Hello,

i dont want to reflash my arm images every time i build a new package set.

i managed to setup my personal repo at https://opnsense.rene.network and configured my mirror within opnsense.

But now i noticed, that only signed packages are allowed, i cant find any information of how to create these signing keys, and add them to my images.

So where to start?

All the best,
René

**Comment by fichtner** [comment]
Hi René,

pkg's signing bits are explained here:

https://www.freebsd.org/cgi/man.cgi?query=pkg-repo&apropos=0&sektion=8&manpath=FreeBSD+11.2-RELEASE+and+Ports&arch=default&format=html#end


Cheers,
Franco

**Comment by fichtner** [comment]
Oh, and BTW: the key and pub part go to repo.key and repo.pub files in the version's configuration directory. The fingerprint is created with:

    # make fingerprint

as documented in the README. That should be all.

**Comment by DarkSunOne** [comment]
Thanks for the link, seems simple :)

```
[root@build12 /usr/tools]# find /usr/ -name repo.key
[root@build12 /usr/tools]# 
```
cant find them :-(

But i remember that they have been created in the beginning

**Comment by fichtner** [comment]
repo.xxx is the name tools.git wants, not how they are created by OpenSSL.

**Comment by DarkSunOne** [comment]
Oh, missed that, thought they were created automaticlally.

Can be closed, understood it now.

Thanks :-)
