### ISSUE TITLE
net-mgmt/arpwatch add to pkg's

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#164]
Hi,

since arpscan plugin dropped with Python3 and some requests to watch for arp poisioning I'd add a plugin for arpwatch to monitor arp changes, maybe also possible to integrate alerts when unknown mac addresses join the network.

**Comment by fabianfrz** [comment]
I think this is some quite old software and something more modern should be used.

Some tools for arp only may be better (for example https://en.wikipedia.org/wiki/ArpON) or also support NDP (https://github.com/fln/addrwatch)

**Comment by mimugmail** [comment]
Addrwatch looks nice but no port, maybe I can build one

**Comment by fichtner** [comment]
do we still want this? :)

**Comment by mimugmail** [comment]
For the long-term addrwatch would be better, I have no idea if I find the time to maintain an additional FreeBSD port, but we'll see :)

**Comment by lpingree** [comment]
I for one still want this if it's possible.

**Comment by mimugmail** [comment]
I wrote a small plugin at my community repo which supports similar features
