### ISSUE TITLE
php version

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/tools#167]
current php verion is https://www.php.net/downloads.php#v7.4.1 - should the web interface be upgraded to that one?

**Comment by AdSchellevis** [comment]
eventually, yes, not for 20.1

**Comment by fichtner** [comment]
Compatibility patches welcome. At the moment 7.2 is still security-supported and we're not missing any features or seeing any relevant bugs.

We can't add multiple PHP version to the repository which makes testing relatively hard, but it's possible to build a different PHP version yourself to help with the process and such compatibility patches.

In general it's a time sink that needs to be coordinated correctly and 1 month before a major release is not the time to start working on it as Ad indicated.

**Comment by fichtner** [comment]
Right now we are on 7.3 and this is the last version for phalcon 3. Phalcon 4 migration therefore must happen before changing to 7.4...
