### ISSUE TITLE
fatal: not a git repository

### ISSUE THREAD

**Issue by ghost** [opnsense/tools#173]
hi,
There was a problem when building packages:  fatal: not a git repository.  This is where the compiling after www/squid
 Can anyone help me pls?

**Comment by fichtner** [comment]
Can you give as build log for this error? It is a little strange and offers no context...

**Comment by win7fs** [comment]
> Can you give a build log for this error? It is a little strange and offers no context...

hi fichtner,
The compiling process stops at
=====>>building for squid
......
[25/25]Deleting files for pkgconf-1.6.3,1:100%
fatal: not a git repository(or any of the parent directories): .git
*** Error code 128
Stop.

And this is the config.conf in device/config.conf:

export MAKE_ARGS_DEV="CROSS_BINUTILS_PREFIX=/usr/local/aarch64-unknown-freebsd12.1/bin"
export PRODUCT_KERNEL=ARM
export PRODUCT_TARGET=arm64
export PRODUCT_ARCH=aarch64
export PRODUCT_WANTS="aarch64-binutils qemu-user-static"

It was so strange.I do tricks with config/20.1/ports.conf:
www/squid                     arm,arm64
and it was OK but remained 
`make:couldn't find package:squid`     then
`ls /usr/local/opnsense/build/20.1/aarch64/sets/`
`packages-20.1.2_35-OpenSSL-aarch64.tar`

:-)

**Comment by fichtner** [comment]
Can you run your build with VERBOSE=yes parameter? Not sure where the error is supposed to come from.
