### ISSUE TITLE
make file issue

### ISSUE THREAD

**Issue by securigeek** [opnsense/tools#175]
Hello I am using ubuntu 18.04 and I am getting the following error on make update setup : 

addy@devil:/usr/tools$ make update
Makefile:42: *** missing separator.  Stop.
addy@devil:/usr/tools$ make dvd
Makefile:42: *** missing separator.  Stop.

Please help.

Thanks,
Securigeek

**Comment by mimugmail** [comment]
You need FreeBSD 11.2 as the build system

**Comment by securigeek** [comment]
Hello Mike,

Thank you for your prompt response. Now since I do not have a free bsd system, and I want to install Opnsense 20 on my RPI 3b . Can you please recomend me  the steps . I have been struggling for couple of days now. I am not so good with RPIs , getting to learn them now. Any help is much appreciated.

Thanks,
Addy

**Comment by mimugmail** [comment]
Currently there is no supported release for 3b, better wait for 20.7 to get broader plattform support

**Comment by fichtner** [comment]
Once 20.7 is out there is probably more work done by @nekoprog and others to support more ARM, but you will stille have to build it yourself because there are too many devices types until a truly generic platform is available.

**Comment by nekoprog** [comment]
Nothing can be done right now, waiting for next release with HBSD12, lots of arm64 supported.

**Comment by securigeek** [comment]
So if i use the Freebsd os I can build the image for RPI 3B ?

**Comment by fichtner** [comment]
HardenedBSD/FreeBSD 12.1 will be in OPNsense 20.7 (July 2020) and then we will be able to work out compile instructions for RPI3 (nit sure if 3B is the same or different).

**Comment by nekoprog** [comment]
In theory, yes it will work, since @DarkSunOne has a working image from the last test. Just a matter of time to merge the configs later on 20.7.

**Comment by DarkSunOne** [comment]
My last successfull built for the Pi3B was with 20.1 and BSD 12.1 base, didnt compiled it since 20.1 release.

I will start up my build environment as soon i have more time.

@fichtner yes the Pi3 and Pi3B are the same, theres nothing different for the built procedure

**Comment by rezafathikohi** [comment]
@DarkSunOne Thanks. How can i download your latest image for RPI3? Is there any link? Thanks
