### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by bortn** [opnsense/tools#177]
I have build error:

`running install_egg_info
Copying botocore.egg-info to /usr/obj/usr/ports/devel/py-botocore/work-py37/stage/usr/local/lib/python3.7/site-packages/botocore-1.15.39-py3.7.egg-info
running install_scripts
writing list of installed files to '/usr/obj/usr/ports/devel/py-botocore/work-py37/.PLIST.pymodtmp'
[20200416121128] ====> Compressing man pages (compress-man)
[20200416121128] ===> Installing for py37-botocore-1.15.39
[20200416121128] ===> Checking if py37-botocore is already installed
[20200416121129] ===> Registering installation for py37-botocore-1.15.39 as automatic
Installing py37-botocore-1.15.39...
===>   py37-boto3-1.10.6 depends on package: py37-botocore>=1.13.6,<1.14.0 - not found
*** Error code 1

Stop.
make: stopped in /usr/ports/www/py-boto3
Creating repository in /usr/obj/usr/tools/config/20.1/OpenSSL:amd64/.pkg-new/: 100%
Packing files for repository: 100%
>>> Running build step: clean
>>> Removing packages set
>>> Creating package mirror set for 20.1.4_36-OpenSSL-amd64... done
-rw-r--r--  1 root  wheel   637M Apr 16 19:12 packages-20.1.4_36-OpenSSL-amd64.tar
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 1.10.6 for www/py-boto3@py37
*** Error code 1

Stop.
make: stopped in /usr/tools
`

**Comment by fichtner** [comment]
Yeah, I have the same errors. Try latest master with the reverts applied.
