### ISSUE TITLE
Binary package for radsecproxy

### ISSUE THREAD

**Issue by Mad-Onion** [opnsense/tools#178]
radsecproxy is a generic RADIUS proxy that supports both UDP and TLS (RadSec) RADIUS transports. It is commonly used in the eduroam-project, connecting research and education communities worldwide.
I'm interested in building a plugin to configure the radsecproxy-daemon, but I need a compiled binary in the distribution.

Sourcecode and more information here: https://github.com/radsecproxy/radsecproxy

**Comment by fichtner** [comment]
deps look manageable. if build time is ok we will include it with 20.1.7 onward

**Comment by Mad-Onion** [comment]
Awesome! Thank you very much :-)
