### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Fazelesswhite** [opnsense/tools#18]
I've been trying to build opnsense and I'm getting this error : http://pastebin.com/dLgrTVuC
Can you guys help me fix it?

**Comment by fichtner** [comment]
We've seen this twice now, but I can't reproduce it. Which build step fails?

# make ports
# make plugins
# make core

Also, maybe it helps to flush the old package database:

# make clean-packages

**Comment by Fazelesswhite** [comment]
I ran :
```
# make clean-packages
# pkg upgrade -y
```
and then : 
```
# make ports
```
Got the following error : 
```
.MAKE.LEVEL.ENV=MAKELEVEL
ARCH=amd64
BLOCKSIZE=K
CDROM=/tmp/images/OPNsense-201508302033-OpenSSL-cdrom-amd64.iso
CONFIGDIR=/usr/tools/config/15.7
CONFIG_PKG=/usr/local/etc/pkg/repos/origin.conf
CONFIG_XML=/usr/local/etc/config.xml
COREDIR=/usr/core
CPUS=4
EDITOR=vi
GROUP=wheel
HOME=/root
HOST=bsd-hayzam
HOSTTYPE=FreeBSD
IMAGESDIR=/tmp/images
LABEL=OPNsense
LOGNAME=root
MACHTYPE=x86_64
MAIL=/var/mail/root
MAKEFLAGS= .MAKE.LEVEL.ENV=MAKELEVEL
MAKELEVEL=1
NANOIMG=/tmp/images/OPNsense-201508302033-OpenSSL-nano-amd64.img
OLDPWD=/usr/tools
OSTYPE=FreeBSD
PACKAGESDIR=/.pkg
PAGER=more
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
PLUGINSDIR=/usr/plugins
PORTSDIR=/usr/ports
PORTSREFDIR=/usr/freebsd-ports
PRODUCT_FLAVOUR=OpenSSL
PRODUCT_NAME=OPNsense
PRODUCT_RELEASE=OPNsense-201508302033-OpenSSL
PRODUCT_SETTINGS=15.7
PRODUCT_VERSION=201508302033
PWD=/usr/tools/build
REMOTEHOST=bba390797.alshamil.net.ae
SERIALIMG=/tmp/images/OPNsense-201508302033-OpenSSL-serial-amd64.img
SETSDIR=/tmp/sets
SHELL=/bin/csh
SHLVL=1
SRCDIR=/usr/src
SSH_CLIENT=83.110.102.145 54793 22
SSH_CONNECTION=83.110.102.145 54793 192.99.206.248 22
SSH_TTY=/dev/pts/0
STAGEDIR=/usr/local/stage
TARGETARCH=amd64
TARGET_ARCH=amd64
TERM=xterm-256color
TOOLSDIR=/usr/tools
USER=root
VENDOR=amd
VGAIMG=/tmp/images/OPNsense-201508302033-OpenSSL-vga-amd64.img
>>> Setting up stage in /usr/local/stage
*** Error code 1

Stop.
make: stopped in /usr/tools
```
This is what I am getting, I am sorry for the late reply and thank you for giving me a reply too :)

**Comment by Fazelesswhite** [comment]
UPDATE : 

I made a virtual machine and tried to build it : 

I ran this first : 

'''
# make clean-packages
# pkg upgrade -y
'''

and then I ran : 

'''
# make ports
# make plugins
# make core
'''

All of them worked..but then I ran 

'''
make everything
'''

But I got the following error :( : 
'''
>>> Creating package mirror set for 15.7.10_9-OpenSSL-amd64... done
.MAKE.LEVEL.ENV=MAKELEVEL
ARCH=amd64
BLOCKSIZE=K
CDROM=/tmp/images/OPNsense-201508291444-OpenSSL-cdrom-amd64.iso
CONFIGDIR=/usr/tools/config/15.7
CONFIG_PKG=/usr/local/etc/pkg/repos/origin.conf
CONFIG_XML=/usr/local/etc/config.xml
COREDIR=/usr/core
CPUS=5
EDITOR=vi
GROUP=wheel
HOME=/root
HOST=
HOSTTYPE=FreeBSD
IMAGESDIR=/tmp/images
LABEL=OPNsense
LOGNAME=root
MACHTYPE=x86_64
MAIL=/var/mail/root
MAKEFLAGS= .MAKE.LEVEL.ENV=MAKELEVEL
MAKELEVEL=1
NANOIMG=/tmp/images/OPNsense-201508291444-OpenSSL-nano-amd64.img
OLDPWD=/usr/tools
OSTYPE=FreeBSD
PACKAGESDIR=/.pkg
PAGER=more
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
PLUGINSDIR=/usr/plugins
PORTSDIR=/usr/ports
PORTSREFDIR=/usr/freebsd-ports
PRODUCT_FLAVOUR=OpenSSL
PRODUCT_NAME=OPNsense
PRODUCT_RELEASE=OPNsense-201508291444-OpenSSL
PRODUCT_SETTINGS=15.7
PRODUCT_VERSION=201508291444
PWD=/usr/tools/build
REMOTEHOST=10.211.55.2
SERIALIMG=/tmp/images/OPNsense-201508291444-OpenSSL-serial-amd64.img
SETSDIR=/tmp/sets
SHELL=/bin/csh
SHLVL=1
SRCDIR=/usr/src
SSH_CLIENT=10.211.55.2 64625 22
SSH_CONNECTION=10.211.55.2 64625 10.211.55.14 22
SSH_TTY=/dev/pts/0
STAGEDIR=/usr/local/stage
TARGETARCH=amd64
TARGET_ARCH=amd64
TERM=xterm-256color
TOOLSDIR=/usr/tools
USER=root
VENDOR=amd
VGAIMG=/tmp/images/OPNsense-201508291444-OpenSSL-vga-amd64.img
>>> Setting up stage in /usr/local/stage
>>> Setting up world in /usr/local/stage
>>> Setting up kernel in /usr/local/stage
>>> Extracting packages in /usr/local/stage
>>> Installing packages in /usr/local/stage...
pkg: No packages installed.  Nothing to do!
Installing pkg-1.5.6...
Extracting pkg-1.5.6: 100%
Message for pkg-1.5.6:
If you are upgrading from the old package format, first run:

  # pkg2ng
Usage: pkg add [-IAfqM] <pkg-name> ...
       pkg add [-IAfqM] <protocol>://<path>/<pkg-name> ...

For more information see 'pkg help add'.
*** Error code 64

Stop.
make: stopped in /usr/tools
'''

**Comment by AdSchellevis** [comment]
Can you check the time of your build machine? I've tried the build process yesterday with a VM and there are some steps in the build which really need the clock to sync.

Last issue I had was when building iso images for the devel (git master) version it was picking up a wrong version tag in build/iso.sh
(I will create an issue for that, Makefiles are not really my thing)

**Comment by Fazelesswhite** [comment]
Okay :)

**Comment by Fazelesswhite** [comment]
Nope, I set the time right and I also managed to edit the iso.sh file as you instructed still I got the error above..:(

**Comment by AdSchellevis** [comment]
can you try again with debug enabled?

make everything DEBUG=1 

Hopefully this will show what goes wrong in your situation, if this doesn't produce a readable error, maybe you could dump all output into a text file and email it to me?
(my email adress is ad at opnsense.org)

**Comment by Fazelesswhite** [comment]
One issue..when I try to boot it on my alix, it doesn't boot up..it just stays still and nothing happens

**Comment by fichtner** [comment]
Things have gotten more complicated in the last few weeks with plugins and product types (stable/devel). A fix when in that should be able to build with the master branch, but then again not with the stable branches...

* Plugins may "hang" /usr/local/stage by launching a daemon that wants the chroot's devfs, but building plugins can be avoided altogether for initial images.
* Make "everything" tries to assemble all images, it's hard to trace which goes wrong.
* Setting DEBUG seems to clobber the kernel/base build.

At least for me it's not possible to trace all subtle errors that creep in with chroot, exported environment variables or the new-found ability to build different branches and being able to identify them uniquely, let alone building all types in one go. But that's just me being defensive I think. Never mind.

If you are expecting an image type, it may be easier to let me know which so we can try the minimal sequence and go from there. :)

**Comment by fichtner** [comment]
Will close with 15.7.14 unless I hear something back. So far people reported fixes have helped. :)
