### ISSUE TITLE
arm ranlib missing

### ISSUE THREAD

**Issue by DarkSunOne** [opnsense/tools#180]
Hello,

currently its not possible to create an arm image:
"tar ./usr/bin/elftc-ranlib: Not found in archive"
![image](https://user-images.githubusercontent.com/11734245/83842254-c24fbc00-a702-11ea-88ff-bd2e6e544a24.png)

@nekoprog , you're still on this?

regards,
René

**Comment by nekoprog** [comment]
still waiting for official 20.7 release, right now it's still missing some patch from freebsd12.1

**Comment by fichtner** [comment]
I have no clue what we're looking at here. It's obviously our tooling, but it's only trying to delete cross compile binaries which no longer exist...

**Comment by DarkSunOne** [comment]
The cleanup works, its the tar command after it ([here](https://github.com/opnsense/tools/blob/9b0ad3a4bfed320722993b66fc248d9cbb2fc72e/build/common.sh#L474))

i implemented a dirty hack [here](https://github.com/opnsense/tools/blob/9b0ad3a4bfed320722993b66fc248d9cbb2fc72e/build/common.sh#L471) to exclude this one file in my test environment which let me build arm images without any problems.

The compiled arm image works very well on my MV ARMADA385 board, i will investigate this further as soon i have time to.

I think this is low prio for now, i will track my results here

**Comment by DarkSunOne** [comment]
This does not occur anymore with current source
