### ISSUE TITLE
Is it possible to build to target powerpc?

### ISSUE THREAD

**Issue by rekshflake** [opnsense/tools#183]
Is it possible to use the tools to create a powerpc image for the QorIQ P2020?

**Comment by rekshflake** [comment]
Any updates on this?

**Comment by fichtner** [comment]
If you add ARCH support and curate relevant ports, yes. From the project perspective we have no stakes in this so we will not work on this.

**Comment by rekshflake** [comment]
So I assume there's no official support for the powerpc architecture.

Would it be hard to implement support for powerpc? Also what are my OS options if I wanted something similar to OPNSense running on the same arch?

**Comment by mimugmail** [comment]
Why dont you start play around with the tools repo, start builing Images for amd64, try to understand how everything works. Then you will see it's more than one person full-time job to achieve this

**Comment by rekshflake** [comment]
I don't want to attempt something that's known to fail.
