### ISSUE TITLE
Add textproc/jq as a package

### ISSUE THREAD

**Issue by cpw** [opnsense/tools#186]
Hi,
The JQ tool, https://stedolan.github.io/jq/download/ is very useful for command line parsing of JSON data, allowing sophisticated scripts to be created based on JSON data from things like webservices and commands like pluginctl.

It would be very useful to have this tool available as a binary package in opnsense, in my opinion.

Thanks!

**Comment by fichtner** [comment]
Ok, why not. Added to upcoming 20.7 packages :)
