### ISSUE TITLE
Compiling on a RPI3

### ISSUE THREAD

**Issue by ImAnOwl** [opnsense/tools#187]
Hi,

i just cloned the git and wanted to start make update. I received the folllowing error:
Makefile:42: *** missing separator.  Stop.
Seems to be a error with tabs(spaces) in the makefile.

MfG,
ImAnOwl

**Comment by fichtner** [comment]
Taking a wild guess: sounds like an error you get when you do not run the tools in a BSD operating system in general? ;)
