### ISSUE TITLE
Adding/modifying files into the final image

### ISSUE THREAD

**Issue by fepitre** [opnsense/tools#188]
I'm looking at adding/modifying files into the final image using specific devices conf file like https://github.com/opnsense/tools/blob/master/device/A10.conf. As I don't have a specific device, I'm unsetting PRODUCT_DEVICE to not build specific kernel and other things. According to https://github.com/opnsense/tools/blob/db2421cfb3da1373c182ecd7e3547e123d4cb618/build/common.sh#L979 it will not trigger the hooks. Maybe this variable could be replaced by PRODUCT_DEVICE_REAL as I don't see this variable impacting other build steps up to https://github.com/opnsense/tools/blob/db2421cfb3da1373c182ecd7e3547e123d4cb618/build/common.sh#L240? Maybe there is another alternative for adding/modifying files into the final image in a more generic and proper way?

**Comment by fichtner** [comment]
Depending on the files that need to be included the easiest option is to write a plugin and add it to ADDITIONS= during image build.


Cheers,
Franco

**Comment by fepitre** [comment]
Thank you for your answer. Here the use case is to provide already prepared opnsense VM with config file seeded.
