### ISSUE TITLE
Failed to Build base for RPI3 on amd64 host.

### ISSUE THREAD

**Issue by spikerguy** [opnsense/tools#190]
Hello,
I have forked @nekoprog opnsense tools fork where he had added cross compiling option.
I have pulled the latest changes from this master branch to my branch and tried to compile it.

Before I was getting error on when I did not have pulled the latest upstream changes
```
===> lib/csu (all)
cc: error: no such file or directory: '/usr/lib/clang/8.0.1/share/cfi_blacklist.txt'
A failure has been detected in another branch of the parallel make
```
Complete log can be found [here](https://github.com/nekoprog/tools/issues/7#issuecomment-667616911)

Then I rebased from upstream and tried to compile base again now I get [this](https://pastebin.com/L0KyuP6L) error.
Can someone help me understand this issue?

I am trying to add RockPIE device support to it as we have it running fine on freebsd already. There are some other errors while compiling packages too which I assume must due to the depreciation of 20.1 which I tried to build first.

Thank you.

**Comment by mimugmail** [comment]
Search the latest commits in tools about this one. Nekos fork doesnt include this fix

**Comment by f-9t9it** [comment]
Hello @mimugmail 
Thanks for replying. 

I have already rebase it to latest upstream commits.
You can find it here. 
https://github.com/spikerguy/tools/pull/1

If there is still something missing then I can try to compare it again but I doubt there is anything missing unless it is still not present in master branch. 

Thanks

**Comment by spikerguy** [comment]
Hello @mimugmail 
Thanks for replying. 

I have already rebase it to latest upstream commits.
You can find it here. 
https://github.com/spikerguy/tools/pull/1

If there is still something missing then I can try to compare it again but I doubt there is anything missing unless it is still not present in master branch. 

Thanks

**Comment by lattera** [comment]
This is because you're building OPNsense on a FreeBSD host. You'll need to build on a HardenedBSD host.

**Comment by spikerguy** [comment]
> This is because you're building OPNsense on a FreeBSD host. You'll need to build on a HardenedBSD host.

Ahh this is something new to me as nekoprog informed that it can work on freebsd to. 

I can try it on hardenedbsd.  
Thanks

**Comment by fichtner** [comment]
If we are talking "cc: error: no such file or directory: '/usr/lib/clang/8.0.1/share/cfi_blacklist.txt'" specifically (which was solved BTW): this is a compiler bootstrap issue with FreeBSD because the source tree has it, but it only inspects the system for it.

**Comment by lattera** [comment]
> If we are talking "cc: error: no such file or directory: '/usr/lib/clang/8.0.1/share/cfi_blacklist.txt'" specifically (which was solved BTW): this is a compiler bootstrap issue with FreeBSD because the source tree has it, but it only inspects the system for it.

https://github.com/HardenedBSD/hardenedBSD/commit/d32f51d7b5bae514e7660ad1e7741ca511fff0b2

**Comment by cherso** [comment]
Successfully compiled **OPNsense 20.7.3** for **RPI3** (_**aarch64**_)

original opnsense/tools with minor changes + nekoprog RPI3.conf and SMP-ARM (thanks!)
base, xtools, packages, arm-3G built under FreeBSD 12.1 stable
kernel built under hardenedBSD 12 stable

**Comment by fichtner** [comment]
This was fixed.
