### ISSUE TITLE
build/base.sh fails to build for SMP-BANANAPI at "Generating base set"

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#192]
Hi,

just tried to play a bit again with arm and make xtools fails at:

```
>>> Setting up stage in /usr/obj/usr/tools/config/20.7/OpenSSL:armv6
>>> Generating base set:
tar: Error opening archive: Failed to open '/usr/obj/usr/src/amd64.amd64/release/base.txz'
*** Error code 1
```

My make command is:
`make base kernel DEVICE=BANANAPI && make xtools DEVICE=BANANAPI && make packages DEVICE=BANANAPI`

It seems it takes the ENV from the build system and not the ones from BANANAPI config as it wants to pack in amd64 folder.
If I adjust `setup_set ${STAGEDIR}/work ${BASE_OBJ}` to the fixed path it works.

Nonetheless it's one of more other build errors but maybe a quick one to fix :)

**Comment by mimugmail** [comment]
I saw the temp fixes from @nekoprog repo, I'll test them :)

**Comment by fichtner** [comment]
FWIW, I think this might be https://github.com/opnsense/tools/pull/181

**Comment by mimugmail** [comment]
Indeed, looks similar  :)
