### ISSUE TITLE
ftp/tftp-hpa: add pkg

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#196]
Really small and easy to install. No config required, just a bit rc.conf.
Can be handy to update headless devices like voip phones, AP's etc.

**Comment by razamatan** [comment]
isn't this just a oneliner to get it into the standard repo?  curious as to know what the blockers are (i.e. just time, etc.).

**Comment by AdSchellevis** [comment]
time to add, time to build, time to maintain. we're not trying to build all software in the world, although this may get in, as a general rule we try to prevent (too much) overlapping functionality. When there are already existing alternatives in our repo we're not always including multiple flavours into our builds (for example Suricata vs Snort, we choose the first). people can always build their own from the ports tree if needed.

**Comment by razamatan** [comment]
the tftp implementation in dnsmasq can be used in isolation if the php for the config was updated to allow a user to specify binding on port 0 (effectively, not binding the main dns/dhcp functionality).  but that setup is kinda weird, and i'd much rather have an actual tftp install.

**Comment by razamatan** [comment]
ok.. playing around with installing it via ports myself, this package isn't maintained anymore afaict.  maybe the better alternative is ftp/py-tftpy which looks to be maintained somewhat.

**Comment by razamatan** [comment]
so the plot thickens.  turns out there's already a tfpd installed in /usr/libexec/tftpd .  man tfpd works, too.  afaict (asking on irc), it's there in the latest installed (i installed opnsense over freebsd 12.2 using opnsense-bootstrap, and folks on irc who used iso installs have it on their system, too).

we probably don't need this package since a tftpd exists as part of the base system...

**Comment by mimugmail** [comment]
I'm not a fan of inetd but if it will stay I'm ok with it:
https://www.freebsd.org/doc/handbook/network-inetd.html

**Comment by fichtner** [comment]
inetd is insofar tricky because we would have to worry about all consumers of inetd now AND in the future and provide the proper structure. It's probably not worth the work.

**Comment by razamatan** [comment]
so i got the inetd + /usr/libexec/tftpd working fine using /etc/rc.conf.d/tftpd to hold inetd_enable="YES" and the single line in /etc/inetd.conf for tftpd uncommented.

i just want to confirm that it's against the forward vision of opnsense to support the underlying bsd's inetd based daemons?  at one point xinetd was available as a package, but it's gone now.  so any (x)inetd based service is considered verboten going forward?

**Comment by fichtner** [comment]
@mimugmail still the plan or cut?

**Comment by mimugmail** [comment]
I would build a small plugin around if it would be in repo :)

**Comment by razamatan** [comment]
just so i understand, this mean it's available in ports for me to install on my own, but is/will not be offered as a package to install via pkg..?

**Comment by fichtner** [comment]
It's always in ports. Now it's in packages. It makes providing plugins for it viable.

**Comment by razamatan** [comment]
thought so, cool.  thanks!
________________________________
