### ISSUE TITLE
Depend on either git or git-lite

### ISSUE THREAD

**Issue by lattera** [opnsense/tools#197]
My systems typically don't have the git package installed, but rather git-lite. git-lite is more than sufficient for OPNsense development.

**Comment by AdSchellevis** [comment]
We tend to use git, which is probably the most popular choice anyway. Supporting different flavours in the development flow often is asking for issues in the long run, so personally I'm not a very big fan of offering choice on core development components unless there is a huge benefit in doing so (other than installation size and personal preference).

**Comment by lattera** [comment]
git-lite is the same as git, just without the GUI components. I should be able to craft a patch to satisfy this ticket sometime this week or next.

**Comment by fichtner** [comment]
probably just this https://github.com/opnsense/tools/blob/ae81fbb8c88ef6ed6f1b511690f6924d8f975aee/build/common.sh#L283

We could check for binary instead.

**Comment by lattera** [comment]
Agreed on just checking for the binary.

**Comment by fichtner** [comment]
I'll take care of this tomorrow.

**Comment by lattera** [comment]
Thanks! You're awesome!
