### ISSUE TITLE
possible to build opnsense to MT7621A board, like this?

### ISSUE THREAD

**Issue by vampywiz17** [opnsense/tools#199]
i think i will buy this board: https://www.asiarf.com/shop/wifi-wlan/wifi_ap_router/wifi-router-board-mtk-mt7621a-mt7615n-2-giga-ethernets-ap7621-il1/

Think that possible to build a opnsense image that support this board? and the good things on MT7621A (like hwNAT, and other hardware acceleration things) is working?

**Comment by thutex** [comment]
would be interesting to have this support to create an entry-level competitor for things like the edgerouter x.
