### ISSUE TITLE
sysutils/ethname: new pkg

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#202]
https://www.freshports.org/sysutils/ethname/

Fresh port arrived which allows locking interface names to mac addresses. 
A plugin would be a good start for ppl wiht a need to add more interfaces and dont want to mess around with interface scrambling.

**Comment by AdSchellevis** [comment]
I don't really think we need a new package for that, not sure if this would actually work on our end either (hooking into rc will be too late, trying to refactor it to use early boot hook might not be the best idea either). Building a script that renames interfaces would likely be much simpler, as a pattern renaming all on early boot to a name containing the mac address is likely easier to maintain as well.

e.g.:
```
ifconfig le4 name E004c69af71b4
 ```

where 004c69af71b4 is the mac address.

**Comment by mimugmail** [comment]
I'm not against an OPNsense-tailored implementation but as you might know my insights are too limited to do this on my own :)

**Comment by eborisch** [comment]
For reference (I'm the author) ethname _is_ an rc script that hooks in before _netif_, and it is, as you say, a _script that renames interfaces_. It is designed to rename interfaces on boot, and is configured via rc.conf with entries like:

`ethname_e4l_mac="00:4c:69:af:71:b4"`

So I _think_ it is exactly what you're describing. There was [some discussion](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=212480#c2) of if it should be a port or part of base FreeBSD, but for now it is shipped as a port.

It's also designed such that "restarting" it is non-destructive (it detects already-renamed devices and leaves them alone, and will rename any newly configured (or newly available) interfaces as requested.

It does not currently have the ability to "stop" and rename them back to their originals, but I don't think there is much of a use case for that.

The one thing (that I'm aware of) that it doesn't handle nicely is bridges, as these don't exist at this point in the boot process.

**Comment by fichtner** [comment]
FWIW, hooking into rc is too late unless we add an early plugin hook. The question is what we want to do with it, e.g. which problem it solves and likely that a plugin makes no sense so it would be core territory. Am I missing something?

@eborisch thanks for the explanations 👍

**Comment by eborisch** [comment]
I'm certainly not familiar with how OPNsense differs from FreeBSD; if the networks are brought up and configured before rc, it certainly won't work as designed. :)

**Comment by fichtner** [comment]
I've added the package since there are no build-related complications such as dependencies or build times (nice work on this by @eborisch btw) and I'll leave it up to @mimugmail or others to play with it. Happy to give guidance on integration.

@eborisch historically m0n0wall circumvented rc to configure the networking on its own. That never changed. ;)
