### ISSUE TITLE
Package Request: acpid or qemu-guest-agent

### ISSUE THREAD

**Issue by MBfromOK** [opnsense/tools#206]
OPNsense 20.7.7_1-amd64
I have been having issues with my Proxmox server that hosts this OPNSense VM needing a reboot / shutdown (weather) and OPNSense is not responding to the hypervisors shutdown / reboot requests.

Per [their documentation](https://pve.proxmox.com/wiki/QEMU/KVM_ACPI_Guest_Shutdown) I need to install either apcid or the qemu Guest Agent in the vm; I tried to pkg install both of these, but no packages could be found.

Please create / include a package for this event daemon.
**(Edit):**_extra clarity_

**Comment by AdSchellevis** [comment]
The documentation is for linux, acpi is part of FreeBSD's base system (https://www.freebsd.org/doc/handbook/acpi-overview.html), it does work like a charm on most hardware platforms (as well as vmware).

**Comment by fichtner** [comment]
To this day still there is no qemu-guest-agent package in FreeBSD ports either.

**Comment by MBfromOK** [comment]
I tried to use the linked document to resolve the issue I was experiencing, but while I was (apparently) able to initiate S3, S4, and S5 states from the VM I am still getting an error from ProxMox when I attempt to initiate a reboot / shutdown from my ProxMox Hypervisor, my debian VM's are working fine so I know that the technology is working.

Any chance you could help me to verify that OPNSense is receiving the commands correctly?

**Comment by AdSchellevis** [comment]
you probably better move the question to the forum (https://forum.opnsense.org) so more people can discuss option, we're not using ProxMox ourselves here. (if a fix is needed, it's likely an upstream one, either by publishing a port for qemu-guest-agent or some driver extension)

**Comment by MBfromOK** [comment]
Thanks for the help!

I will pursue communication issues with the forums.
