### ISSUE TITLE
make dvd failing consistently on the same issue 

### ISSUE THREAD

**Issue by chaichairiko** [opnsense/tools#207]
Hi,
Between builds I clean the entire system. I am getting this error
![Screenshot from 2021-01-05 09-10-51](https://user-images.githubusercontent.com/10689817/103617466-f7d9b380-4f36-11eb-8a93-44691dd1ce08.png)

Apologies for the screenshot, instead of code pasting. I was using a VMWare console with no mouse

**Comment by AdSchellevis** [comment]
it's probably better to use the form (https://forum.opnsense.org) instead of opening issues about different steps of your journey, this isn't the level of community support we can offer and I expect not a lot of people watch issues in the tools repo other than core team members. close this issue or the other one (https://github.com/opnsense/tools/issues/205)?

Our experience (on both physical and vmware instances) is that tagged builds are reproducible when following the described steps (precisely) and using the defined type of build environment (for 20.7 that is FreeBSD 12.1-RELEASE https://github.com/opnsense/tools#setting-up-a-build-system)

**Comment by mimugmail** [comment]
I also cloned tools repo on a 12.1 vanilla install on proxmox, followed the steps and successfully build a OpenSSL DVD recently.

**Comment by chaichairiko** [comment]
@AdSchellevis looking at the forum, I see multiple issues regarding build failures that are not being answered since October. While I understand that your tagged branches may pass, it seems there are issues when building the system that are unanswered. 
Nevertheless, I understand your comment and will open these issues in the forum

**Comment by fichtner** [comment]
Links please and I will explain to you each one...

**Comment by chaichairiko** [comment]
https://forum.opnsense.org/index.php?topic=20460.msg95124#msg95124
https://forum.opnsense.org/index.php?topic=19654.msg90538#msg90538
https://forum.opnsense.org/index.php?topic=19403.msg89393#msg89393

**Comment by fichtner** [comment]
> https://forum.opnsense.org/index.php?topic=20460.msg95124#msg95124

Fetch error. You can prefetch "distfiles" to avoid it. Unfortunately we can't fix the Internet :) 

https://github.com/opnsense/tools#advanced-package-builds

> https://forum.opnsense.org/index.php?topic=19654.msg90538#msg90538

     make: stopped in /usr/src
    *** Error code 2

Unusual build error in FreeBSD. Never saw this, maybe sourced edited or configuration changed. Bug tracker is  https://bugs.freebsd.org/bugzilla/

> https://forum.opnsense.org/index.php?topic=19403.msg89393#msg89393

No support for anything other than amd64 from us. tools.git is open source and can be adjusted to build other architectures. It simply requires work to be done not relevant for the project for a purpose other than the project. ;)

**Comment by chaichairiko** [comment]
Thanks for your quick comment.
What I am concerned about is not getting answers in the forum, not those specific issues

**Comment by fichtner** [comment]
Usually, responses warrant good chance of being helpful. If questions are out of scope or do not provide enough context it is difficult to start a long process of communication. For your build log it would be helpful to add VERBOSE=yes to the build to see which shell command errors out. If pkg errors out doing installing packages there surely is an error somewhere, but it's not in your screenshot.

**Comment by chaichairiko** [comment]
Thank you sir, I will try that and the response to the forum post I am writing
