### ISSUE TITLE
Suricata : build with --enable-prelude option to allow users to easily consolidate alerting on Prelude SIEM

### ISSUE THREAD

**Issue by Nils-GitHub1** [opnsense/tools#208]
Could it be possible to enable Prelude SIEM support by default in OpnSense Suricata ?

This would avoid having to rebuild suricata and provide additional use cases for Opnsense.

The needed libprelude is small in size.

https://github.com/HardenedBSD/opnsense-core/blob/master/src/opnsense/service/templates/OPNsense/IDS/suricata.yaml
This would allow to enable in suricata.yaml
'# alert output to prelude (http://www.prelude-technologies.com/) only
  '# available if Suricata has been compiled with --enable-prelude
  - alert-prelude:
      enabled: no
      profile: suricata
      log-packet-content: no
      log-packet-header: yes

**Comment by fichtner** [comment]
@Nils-GitHub1 we have to discuss this at the office tomorrow. At first glance and from previous FreeBSD feedback it should not be in the defaults. See also troubles on Suricata 6 here https://redmine.openinfosecfoundation.org/issues/4065
