### ISSUE TITLE
Buildkernel Error 2

### ISSUE THREAD

**Issue by bevobird** [opnsense/tools#211]
Hello I got an error when I wanted to build the RPI2 arm image.
Can someone help me?

Used Commands:
pkg install git qemu-user-static arm-gnueabi-binutils u-boot-rpi2 rpi-firmware
make update
pkg install qemu-user-static
make base kernel ARCH=arm:armv6 KERNEL=SMP-RPI2

Error:
![Unbenannt](https://user-images.githubusercontent.com/47929399/105967369-0c1c5680-6086-11eb-923b-fde7b90a8be3.PNG)

**Comment by fichtner** [comment]
You probably need https://github.com/opnsense/tools/pull/203 anyway

**Comment by bevobird** [comment]
Okay But do I only have to "make update" or how can I update so that the build works ?

**Comment by fichtner** [comment]
No, PR for #203 is still open. ARM is a work in progress still....

**Comment by bevobird** [comment]
Okay so I have to wait =( . Can you mybe tell me how long it takes ? And if the build is ready dose it also takes like 6-8 hours to build this for the RPi2 ? because I still have OPNsense 19.1.7_13-armv6 on the RPi2.

**Comment by nekoprog** [comment]
You can use my fork for testing purpose, but need to select 20.7, 21.1 need some polishing, might have to wait if you don't mind.

**Comment by bevobird** [comment]
I tried it, but I got an error again.  would it be possible that you can tell me which command I have to use for the RPI 2 Arm Build?

**Comment by nekoprog** [comment]
You need to run
`make base DEVICE=RPI2`
Every step command needs to include `DEVICE=RPI2`
