### ISSUE TITLE
wrong rrdtool SET option?

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#229]
Hi,

I tried to install smokeping and found this error:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=211543

In my build env I added a set for GRAPHS and it works. 
Now I wanted to add a PR and saw that GRAPH .. without "S" is UNSET.
Is there a reason for this?

https://github.com/opnsense/tools/blob/master/config/21.1/make.conf#L53

**Comment by fichtner** [comment]
The option is called GRAPH, the bugzilla comment is likely a typo. We disabled it because it pulls in part of GNOME desktop: 5b9b7df3 02a1521e

We could see if things improved over the years, but not overly confident about this having changed considerably.

**Comment by mimugmail** [comment]
OK, then better stick to the old option. I will build an alternative packet with a clear warning. Thx for having a look :)
