### ISSUE TITLE
Include support for HAProxy Prometheus metrics

### ISSUE THREAD

**Issue by svenschiller** [opnsense/tools#230]
I'd like to send HAProxy metrics to Prometheus. The exporter built into HAProxy requires a make option (USE_PROMEX=1) to be set, see https://github.com/haproxy/haproxy/tree/master/addons/promex . 
Could you please add this in your build process?

**Comment by AdSchellevis** [comment]
At a first glance this needs PROMEX appended net_haproxy_SET (https://github.com/opnsense/tools/blob/6e84a332829a69ac4006c7c96415f57817a070dd/config/21.1/make.conf#L74).

**Comment by fichtner** [comment]
nightly build says ok
