### ISSUE TITLE
Support Multipath BGP routing

### ISSUE THREAD

**Issue by dominic-p** [opnsense/tools#231]
This is a followup from [this discussion](https://github.com/opnsense/tools/pull/185#issuecomment-825552504).

As suggested I'm creating an issue to track support for Multipath routing. I'm excited to use it with MetalLB to enable load balancing on our on-prem Kubernetes cluster. It looks like support [has landed](https://www.freebsd.org/releases/13.0R/relnotes/#network-routing) in FreeBSD 13. So, when the time comes for OPNsense to transition to HardenedBSD 13, everything should be in place to enable Multipath BGP.

Apologies if this issue is in the wrong place. Feel free to close or move it if needed. And, as always, thank you for the fantastic software. :)

**Comment by AlexisDucastel** [comment]
Hi there, I'm also interested in multipath feature for MetalLB on on-prem clusters :)

**Comment by fichtner** [comment]
Sure, added it to 22.1 configuration for FreeBSD 13 as promised.

**Comment by onedr0p** [comment]
@fichtner that's great to hear. Looking forward to 22.1. Thanks!

**Comment by taxilian** [comment]
Super excited for this. this will be in 21.7.2? that will solve lots of issues for me!

**Comment by fichtner** [comment]
Mhhh, no, we said 22.1 too times?

**Comment by budimanjojo** [comment]
Super right on time, I'm currently planning to use Calico in BGP mode. Thank you !!

**Comment by taxilian** [comment]
Just to verify, since I didn't see it in the official release notes -- is this out in the OPNSense 22.1 release?

**Comment by onedr0p** [comment]
> Just to verify, since I didn't see it in the official release notes -- is this out in the OPNSense 22.1 release?

Yes! Head over to the tunables to enabled it...

`net.route.multipath=1`

**Comment by fichtner** [comment]
Note that for normal multi-wan use this will cause undefined behaviour sind multiple default routes can be added and the last one wins, which is the one that was established last.

**Comment by taxilian** [comment]
Awesome =] Any updates to FRR required or is that all already in place? (I
assume it is).

Not going to try to update this in the middle of the day, but this should
really improve my network efficiency.

Richard
