### ISSUE TITLE
Cannot make core: tar: Option -f requires an argument

### ISSUE THREAD

**Issue by oparoz** [opnsense/tools#24]
This is straight from the router, not from a VM.

```
[02.02.2016 14:11:48  /usr/core]
root@base # git pull --rebase
remote: Counting objects: 469, done.
remote: Compressing objects: 100% (284/284), done.
remote: Total 469 (delta 297), reused 126 (delta 126), pack-reused 52
Receiving objects: 100% (469/469), 185.29 KiB | 200.00 KiB/s, done.
Resolving deltas: 100% (304/304), completed with 39 local objects.
From https://github.com/opnsense/core
   35a1118..e6ee842  master     -> origin/master
   a3ea380..5560803  stable/16.1 -> origin/stable/16.1
 * [new tag]         16.1.1     -> 16.1.1
First, rewinding head to replay your work on top of it...
Fast-forwarded master to e6ee8423801c13e636d81ed29ab398ce2db287a1.

[02.02.2016 14:11:55  /usr/core]
root@base # cd ../tools/

[02.02.2016 14:12:04  /usr/tools]
root@base # make core
.MAKE.LEVEL.ENV=MAKELEVEL
ARCH=amd64
BLOCKSIZE=K
CONFIGDIR=/usr/tools/config/16.1
CONFIG_PKG=/usr/local/etc/pkg/repos/origin.conf
CONFIG_XML=/usr/local/etc/config.xml
COREDIR=/usr/core
CPUS=4
EDITOR=vi
GROUP=wheel
HOME=/root
HOSTTYPE=FreeBSD
IMAGESDIR=/tmp/images
LABEL=OPNsense
LOGNAME=root
MACHTYPE=x86_64
MAIL=/var/mail/root
MAKEFLAGS= .MAKE.LEVEL.ENV=MAKELEVEL
MAKELEVEL=1
OLDPWD=/usr/tools
OSTYPE=FreeBSD
PACKAGESDIR=/.pkg
PAGER=less
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:/root/bin
PLUGINSDIR=/usr/plugins
PORTSDIR=/usr/ports
PORTSREFDIR=/usr/freebsd-ports
PRODUCT_FLAVOUR=OpenSSL
PRODUCT_NAME=OPNsense
PRODUCT_PRIVKEY=/root/repo.key
PRODUCT_PUBKEY=/root/repo.pub
PRODUCT_RELEASE=OPNsense-201602021412-OpenSSL
PRODUCT_SETTINGS=16.1
PRODUCT_TYPE=opnsense-devel
PRODUCT_VERSION=201602021412
PWD=/usr/tools/build
SETSDIR=/tmp/sets
SHELL=/usr/local/etc/rc.initial
SHLVL=1
SRCDIR=/usr/src
SSH_TTY=/dev/pts/0
STAGEDIR=/usr/obj/stage
TARGETARCH=amd64
TARGET_ARCH=amd64
TERM=xterm
TOOLSDIR=/usr/tools
USER=root
VENDOR=amd
>>> Setting up stage in /usr/obj/stage
>>> Setting up world in /usr/obj/stage
tar: Option -f requires an argument
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
*** Error code 1

Stop.
make: stopped in /usr/tools
```

**Comment by fichtner** [comment]
Not sure what your tools.git commit is, but you'll need to run:

    # make ports
    # make packages

before core will build. Recent commits will get the drift.

Also note this tweak for better reporting:

    # make core VERBOSE=please

There is no unstaged out of band build for core at the moment, meaning the build system wants to build all the parts including kernel, base, ports and plugins.

**Comment by oparoz** [comment]
> There is no unstaged out of band build for core at the moment, meaning the build system wants to build all the parts including kernel, base, ports and plugins.

Ah, that's what I wanted to avoid. base has never been compiled.

Does that mean that it's unsafe to only update core and that base+kernel have to be updated at the same time?

**Comment by fichtner** [comment]
Try the latest commits on tools:

# make prefetch-kernel,base,packages VERSION=16.1
# make core-master

Pew pew :) Only problem is that core package will be pushed into the /tmp/sets/packages-* archive.

I have ideas about inline packaging, but I was still pondering whether the tools.git should or should not be required in this case.

**Comment by oparoz** [comment]
OK so the required packages were downloaded to `/tmp/sets/` 

```
-rw-r--r--  1 root  wheel   3.5K Jan 28 12:32 base-16.1-amd64.obsolete
-rw-r--r--  1 root  wheel    44M Jan 28 12:33 base-16.1-amd64.txz
-rw-r--r--  1 root  wheel    23M Jan 28 12:34 kernel-16.1-amd64.txz
drwxr-xr-x  2 root  wheel   512B Feb  2 15:13 .
-rw-r--r--  1 root  wheel   167M Feb  2 15:13 packages-16.1.1_6-OpenSSL-amd64.tar
```

and I have a core package at `/usr/obj/stage/.pkg-new/All/opnsense-16.1.txz`

But this seems to be the old version, not the newer 16.1.1. So how do we get the latest core package?

**Comment by fichtner** [comment]
The sets are there to set up the build jail, the latest core package is built by what I wrote:

    # make core-master

("master" is the branch or tag name or commit hash, e.g.

    # make core-16.1.1

)

**Comment by oparoz** [comment]
Thanks.
The thing that I missed was that the new packages were in  `/tmp/sets/packages-16.1.1_6-OpenSSL-amd64.tar`. That's because a package with a very similar name was downloaded as part of the prefetch command, but those were the previous packages.

So that process works to update the GUI without touching anything else :+1: 

Maybe the Readme should be altered to indicate that `make core` can't be run on it's own?

**Comment by fichtner** [comment]
It can. The build system supports progress markers and automatic skipping plus dependency tracking since 16.1-ish.

If you type "make core" after prefetching everything, it'll tell you it has nothing to do.

**Comment by fichtner** [comment]
Also see the actual target dependency that glues e.g. "make everything" together...

https://github.com/opnsense/tools/blob/master/Makefile#L36-L39

**Comment by oparoz** [comment]
>It can. The build system supports progress markers and automatic skipping plus dependency tracking since 16.1-ish.
If you type "make core" after prefetching everything, it'll tell you it has nothing to do.

That's what I mean. There are pre-requirements. Those won't be automatically resolved when doing `make core`. I had to prefetch base, kernel and packages

**Comment by fichtner** [comment]
You're right, I've tightened the dependency chain in the referenced commit. Can you recheck?

**Comment by fichtner** [comment]
BUT: prefetching will always remain a manual operation

**Comment by oparoz** [comment]
>BUT: prefetching will always remain a manual operation

That's what I think should be added to the Readme, because without doing a prefetch, I still get `tar: Option -f requires an argument`. The packages need to be there, but it's not obvious that base and kernel have to be made available to build core.

**Comment by fichtner** [comment]
With the last commit and no prefetch "make core" starts to build the base system.
After prefetch or "make packages" I get an instant ">>> Packages (core) are up to date" with "make core".

**Comment by oparoz** [comment]
Of course it works better if I actually fetch the commit.

All good now, thanks.

**Comment by fichtner** [comment]
Thanks for double-checking :)
