### ISSUE TITLE
Add net-mgmt/iprange as a package

### ISSUE THREAD

**Issue by vogelfreiheit** [opnsense/tools#240]
net-mgmt/iprange can be very useful in reducing/coalescing large tables (ex. processing AWS network blocks), especially when you want deduplication.

I recall this is available in pfsense through the pfBlockerNG package, but it should be straightforward to include it in OPNsense as it is an upstream package.

Altogether with JQ this can be used satisfactorily to handle custom alias tables, like the aforementioned AWS example.

**Comment by fichtner** [comment]
Last update of the software in FreeBSD ports was September 2018. For now I will not add this due to risk of removal from FreeBSD ports in the near future.
