### ISSUE TITLE
make dvd error 

### ISSUE THREAD

**Issue by sreekupm** [opnsense/tools#242]
Dear Team, 

I got error while make dvd 

Please help me to solve the same.

root@freebsd:/usr/tools # make dvd
.MAKE.LEVEL.ENV=MAKELEVEL
ABI_FILE=/usr/lib/crt1.o
BLOCKSIZE=K
CONFIGDIR=/usr/tools/config/21.7
CONFIG_XML=/usr/local/etc/config.xml
COREBRANCH=stable/21.7
COREDIR=/usr/core
COREENV=CORE_PHP=74 CORE_ABI=21.7 CORE_PYTHON=38
CPUS=6
DEVICEDIR=/usr/tools/device
EDITOR=vi
ENV_FILTER=env -i USER=root LOGNAME=root HOME=/root SHELL=/bin/csh BLOCKSIZE=K MAIL=/var/mail/root PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin TERM=xterm HOSTTYPE=FreeBSD VENDOR=amd OSTYPE=FreeBSD MACHTYPE=x86_64 PWD=/usr/tools/build GROUP=wheel HOST=freebsd EDITOR=vi PAGER=less ABI_FILE=/usr/lib/crt1.o
EXTRABRANCH=
GROUP=wheel
HOME=/root
HOST=freebsd
HOSTTYPE=FreeBSD
IMAGESDIR=/usr/local/opnsense/build/21.7/amd64/images
LOGNAME=root
LOGSDIR=/usr/local/opnsense/build/21.7/amd64/logs
MACHTYPE=x86_64
MAIL=/var/mail/root
MAKEFLAGS= .MAKE.LEVEL.ENV=MAKELEVEL
MAKELEVEL=1
META_MODE=normal
OLDPWD=/usr/tools
OSTYPE=FreeBSD
PACKAGESDIR=/.pkg
PAGER=less
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin
PLUGINSBRANCH=stable/21.7
PLUGINSDIR=/usr/plugins
PLUGINSENV=PLUGIN_PHP=74 PLUGIN_ABI=21.7 PLUGIN_PYTHON=38
PORTSBRANCH=master
PORTSDIR=/usr/ports
PORTSENV=
PORTSREFBRANCH=main
PORTSREFDIR=/usr/freebsd-ports
PORTSREFURL=https://git.FreeBSD.org/ports.git
PRINT_ENV_SKIP=1
PRODUCT_ABI=21.7
PRODUCT_ADDITIONS=os-dyndns
PRODUCT_ARCH=amd64
PRODUCT_COMPORT=0x3f8
PRODUCT_COMSPEED=115200
PRODUCT_CORE=opnsense
PRODUCT_CORES=opnsense opnsense-devel opnsense-business
PRODUCT_CRYPTO=openssl
PRODUCT_DEVEL=
PRODUCT_DEVICE_REAL=A10
PRODUCT_FLAVOUR=OpenSSL
PRODUCT_GITBASE=https://github.com/opnsense
PRODUCT_HOST=amd64
PRODUCT_KERNEL=SMP
PRODUCT_LUA=5.3
PRODUCT_MIRROR=http://mirrors.nycbug.org/pub/opnsense
PRODUCT_NAME=OPNsense
PRODUCT_PERL=5.32
PRODUCT_PHP=74
PRODUCT_PLUGIN=os-*
PRODUCT_PLUGINS=os-*
PRODUCT_PRIVKEY=/usr/tools/config/21.7/repo.key
PRODUCT_PUBKEY=/usr/tools/config/21.7/repo.pub
PRODUCT_PYTHON=38
PRODUCT_RELEASE=OPNsense-202108121226-OpenSSL
PRODUCT_RUBY=27
PRODUCT_SERVER=user@does.not.exist
PRODUCT_SETTINGS=21.7
PRODUCT_SIGNCHK=/usr/tools/scripts/pkg_fingerprint.sh /usr/tools/config/21.7/repo.pub
PRODUCT_SIGNCMD=/usr/tools/scripts/pkg_sign.sh /usr/tools/config/21.7/repo.pub /usr/tools/config/21.7/repo.key
PRODUCT_SUFFIX=
PRODUCT_TARGET=amd64
PRODUCT_TYPE=opnsense
PRODUCT_UEFI=dvd serial vga vm arm
PRODUCT_VERSION=202108121226
PWD=/usr/tools/build
REMOTEHOST=192.168.0.30
SETSDIR=/usr/local/opnsense/build/21.7/amd64/sets
SHELL=/bin/csh
SHLVL=1
SRCABI=FreeBSD:12:amd64
SRCBRANCH=stable/21.7
SRCDIR=/usr/src
SRCREVISION=12.1
SSH_CLIENT=192.168.0.30 63318 22
SSH_CONNECTION=192.168.0.30 63318 192.168.0.240 22
SSH_TTY=/dev/pts/0
STAGEDIR=/usr/obj/usr/tools/config/21.7/OpenSSL:amd64
STAGEDIRPREFIX=/usr/obj
TARGETDIR=/usr/local/opnsense/build/21.7/amd64
TARGETDIRPREFIX=/usr/local/opnsense/build
TERM=xterm
TOOLSBRANCH=master
TOOLSDIR=/usr/tools
UPLOADDIR=.
USER=root
VENDOR=amd
>>> Running build step: kernel
>>> Passing arguments: (none)
make[1]: "/usr/src/Makefile.inc1" line 343: SYSTEM_COMPILER: libclang will be built for bootstrapping a cross-compiler.
make[1]: "/usr/src/Makefile.inc1" line 348: SYSTEM_LINKER: libclang will be built for bootstrapping a cross-linker.

--------------------------------------------------------------
>>> Kernel build for SMP started on Thu Aug 12 12:26:28 IST 2021
--------------------------------------------------------------
===> SMP

--------------------------------------------------------------
>>> stage 1: configuring the kernel
--------------------------------------------------------------
Kernel build directory is /usr/obj/usr/src/amd64.amd64/sys/SMP
Don't forget to do ``make cleandepend && make depend''

--------------------------------------------------------------
>>> stage 2.3: build tools
--------------------------------------------------------------

--------------------------------------------------------------
>>> stage 3.1: building everything
--------------------------------------------------------------
ERROR: ctfconvert: mvs_if.o doesn't have type data to convert
/usr/src/sys/dev/mrsas/mrsas_cam.c:1919:4: error: misleading indentation; statement is not part of the previous 'if' [-Werror,-Wmisleading-indentation]
                        if (mpt_cmd->ccb_ptr->cpi.bus_id == bus_id &&
                        ^
/usr/src/sys/dev/mrsas/mrsas_cam.c:1916:3: note: previous statement is here
                if (bus_id == 1)
                ^
1 error generated.
--- mrsas_cam.o ---
*** [mrsas_cam.o] Error code 1

make[2]: stopped in /usr/obj/usr/src/amd64.amd64/sys/SMP
--- all_subdir_acl_nfs4 ---
--- modules-all ---
*** [modules-all] Error code 2

make[2]: stopped in /usr/obj/usr/src/amd64.amd64/sys/SMP
ERROR: ctfconvert: mvs_pci.o doesn't have type data to convert
ERROR: ctfconvert: mrsas_fp.o doesn't have type data to convert
ERROR: ctfconvert: mvs.o doesn't have type data to convert
ERROR: ctfconvert: if_msk.o doesn't have type data to convert
2 errors

make[2]: stopped in /usr/obj/usr/src/amd64.amd64/sys/SMP
--- buildkernel ---
--- buildkernel ---
*** Error code 2

Stop.
make: stopped in /usr/tools

**Comment by fichtner** [comment]
It's just a build error that you are going to have to deal with inside the kernel code. I don't know what source code you are using but I can tell you with the available code from us you don't hit this error on amd64.

**Comment by sreekupm** [comment]
Dear fichtner, 

I have installed Freebsd 12.2 bootonly 
then i have done the below steps 

pkg install git
cd /usr
git clone https://github.com/opnsense/tools
cd tools
make update
make dvd

**Comment by fichtner** [comment]
Yes, install 12.1 as suggested in README

**Comment by fichtner** [comment]
See https://github.com/opnsense/tools#setting-up-a-build-system

**Comment by sreekupm** [comment]
Thanks for your support, I will try with 12.1 and update here at the earliest.

**Comment by sreekupm** [comment]
Dear Franco,

I have installed 12.1 and repeat the same procedure, but building was stuck, please check the below console output and please help me to solve the issue 

Build machine details  AMD Ryzen 5 2400G
VM- 6Vcpu, 12GB Ram, 80GB Hdd, 


fetch: https://codeload.github.com/bsdjhb/libcxx-gdbpy/tar.gz/229610a?dummy=/bsdjhb-libcxx-gdbpy-229610a_GH0.tar.gz: size of remote file is not known
bsdjhb-libcxx-gdbpy-229610a_GH0.tar.gz                5299  B   23 MBps    00s
mpfr-4.1.0.tar.xz                                     1489 kB  130 kBps    11s
patch01                                               2061  B   10 MBps    00s
patch02                                               2543  B   11 MBps    00s
patch03                                               9973  B   40 MBps    00s
patch04                                                 26 kB  142 kBps    00s
patch05                                               5345  B   23 MBps    00s
patch06                                               4026  B   19 MBps    00s
patch07                                               3580  B   17 MBps    00s
patch08                                               4002  B   19 MBps    00s
patch09                                               4591  B   22 MBps    00s
patch10                                                 25 kB  141 kBps    00s
patch11                                               4584  B   21 MBps    00s
patch12                                               6768  B   48 MBps    00s
patch13                                               3344  B   16 MBps    00s
gmp-6.2.1.tar.xz                                      1979 kB  296 kBps    07s
libtool: warning: relinking 'libgmpxx.la'
libtool: warning: remember to run 'libtool --finish /usr/local/lib'
libtool: warning: remember to run 'libtool --finish /usr/local/lib'
source-highlight-3.1.9.tar.gz                         1676 kB  311 kBps    06s
ctags-5.8.tar.gz                                       468 kB  771 kBps    00s
fetch: https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2: Forbidden
boost_1_72_0.tar.bz2                                   101 MB 1041 kBps 01m40s
icu4c-69_1-src.tgz                                      23 MB 9501 kBps    03s
ar: warning: creating libicudata.a
ustr_wcs.cpp:353:30: warning: comparison of integers of different signs: 'int32_t'
      (aka 'int') and 'unsigned long' [-Wsign-compare]
                if(remaining < (nulLen * MB_CUR_MAX)){
                   ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
ustr_wcs.cpp:406:30: warning: comparison of integers of different signs: 'int32_t'
      (aka 'int') and 'unsigned long' [-Wsign-compare]
                if(remaining < (nulLen * MB_CUR_MAX)){
                   ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
2 warnings generated.
ustr_wcs.cpp:353:30: warning: comparison of integers of different signs: 'int32_t'
      (aka 'int') and 'unsigned long' [-Wsign-compare]
                if(remaining < (nulLen * MB_CUR_MAX)){
                   ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
ustr_wcs.cpp:406:30: warning: comparison of integers of different signs: 'int32_t'
      (aka 'int') and 'unsigned long' [-Wsign-compare]
                if(remaining < (nulLen * MB_CUR_MAX)){
                   ~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
2 warnings generated.
ar: warning: creating ../lib/libicuuc.a
ar: warning: creating ../lib/libicui18n.a
ar: warning: creating ../lib/libicuio.a
ar: warning: creating ../../lib/libicutu.a
ar: warning: creating libicutest.a
ar: warning: creating uconvmsg/libuconvmsg.a

**Comment by fichtner** [comment]
I'm no seeing any error here?

**Comment by sreekupm** [comment]
Dear Franco, 

Please share the exact Freebsd 12.1 release link.

**Comment by fichtner** [comment]
I've always used https://download.freebsd.org/ftp/releases/amd64/amd64/ISO-IMAGES/12.1/FreeBSD-12.1-RELEASE-amd64-dvd1.iso.xz but I think the error is more about specific build system than FreeBSD image.

**Comment by sreekupm** [comment]
Dear Franco, 

I have tried so many times with the above mentioned release. again and again  failed, also no log file created and some times build machine got stuck up :( . 

Any idea about this?

**Comment by AdSchellevis** [comment]
Unfortunately we can't offer additional community support on the build system, other than all resources that are available already. Our build process pushes logs to https://nightly.opnsense.org/21.7/amd64/logs/ , sometimes it might help to compare output. When some ports fail, you can also build them isolated to figure out what's different on your end. 

When it comes to building ports, the FreeBSD Porter's handbook is a useful resource as well https://docs.freebsd.org/en/books/porters-handbook/

**Comment by mimugmail** [comment]
You can also try to higher RAM to 16GB. Rust builds will fail with 8GB, didn't tried with 12GB.

**Comment by sreekupm** [comment]
I have tried with 16 GB Ram, The build encountered fatal issues!
also log file not created 



The operation will free 1 MiB.
[1/2] Deinstalling xorg-macros-1.19.3...
[1/2] Deleting files for xorg-macros-1.19.3: 100%
[2/2] Deinstalling xorgproto-2021.4...
[2/2] Deleting files for xorgproto-2021.4: 100%
>>> Saving runtime package: libfontenc
>>> Saving runtime package: mkfontscale
>>> Saving runtime package: urwfonts
[20210829033133] ===> Cleaning for mkfontscale-1.2.1
[20210829033133] ===> Cleaning for libfontenc-1.1.4
[20210829033133] ===> Cleaning for urwfonts-1.0_8
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 9 packages:

Installed packages to be REMOVED:
        expat: 2.4.1
        fontconfig: 2.13.93_1,1
        freetype2: 2.10.4
        libfontenc: 1.1.4
        mkfontscale: 1.2.1
        pkg: 1.16.3
        pkgconf: 1.7.4,1
        png: 1.6.37_1
        urwfonts: 1.0_8

Number of packages to be removed: 9

The operation will free 22 MiB.
[1/9] Deinstalling urwfonts-1.0_8...
[1/9] Deleting files for urwfonts-1.0_8: 100%
[2/9] Deinstalling fontconfig-2.13.93_1,1...
[2/9] Deleting files for fontconfig-2.13.93_1,1: 100%
[3/9] Deinstalling mkfontscale-1.2.1...
[3/9] Deleting files for mkfontscale-1.2.1: 100%
[4/9] Deinstalling freetype2-2.10.4...
[4/9] Deleting files for freetype2-2.10.4: 100%
[5/9] Deinstalling expat-2.4.1...
[5/9] Deleting files for expat-2.4.1: 100%
[6/9] Deinstalling libfontenc-1.1.4...
[6/9] Deleting files for libfontenc-1.1.4: 100%
[7/9] Deinstalling pkg-1.16.3...
[7/9] Deleting files for pkg-1.16.3: 100%
[8/9] Deinstalling pkgconf-1.7.4,1...
[8/9] Deleting files for pkgconf-1.7.4,1: 100%
[9/9] Deinstalling png-1.6.37_1...
[9/9] Deleting files for png-1.6.37_1: 100%
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 5.59,1 for security/stunnel
*** Error code 1

Stop.
make: stopped in /usr/tools
You have new mail.
root@freebsd:/usr/tools #

**Comment by fichtner** [comment]
To me this looks ok, stunnel distfiles have been removed from their mirror prior to version 5.60 and you need to keep up with ports tree to deal with such upstream breakage.

**Comment by fichtner** [comment]
See https://github.com/opnsense/ports/commit/ffa0a1f6da161879e4b5dbc4a384971fb26ab077 and even https://github.com/opnsense/ports/commit/f385e72528bf2d3ffaf08655b1c5d97b4052ef85 so please don’t ask for support for fixed issues…

**Comment by sreekupm** [comment]
Dear Franco, 

Sorry for the above issue, I have updated ports then its working but again failed another one 


Deinstallation has been requested for the following 9 packages:

Installed packages to be REMOVED:
        expat: 2.4.1
        fontconfig: 2.13.94,1
        freetype2: 2.10.4
        libfontenc: 1.1.4
        mkfontscale: 1.2.1
        pkg: 1.16.3
        pkgconf: 1.7.4,1
        png: 1.6.37_1
        urwfonts: 1.0_8

Number of packages to be removed: 9

The operation will free 22 MiB.
[1/9] Deinstalling urwfonts-1.0_8...
[1/9] Deleting files for urwfonts-1.0_8: 100%
[2/9] Deinstalling fontconfig-2.13.94,1...
[2/9] Deleting files for fontconfig-2.13.94,1: 100%
[3/9] Deinstalling mkfontscale-1.2.1...
[3/9] Deleting files for mkfontscale-1.2.1: 100%
[4/9] Deinstalling freetype2-2.10.4...
[4/9] Deleting files for freetype2-2.10.4: 100%
[5/9] Deinstalling expat-2.4.1...
[5/9] Deleting files for expat-2.4.1: 100%
[6/9] Deinstalling libfontenc-1.1.4...
[6/9] Deleting files for libfontenc-1.1.4: 100%
[7/9] Deinstalling pkg-1.16.3...
[7/9] Deleting files for pkg-1.16.3: 100%
[8/9] Deinstalling pkgconf-1.7.4,1...
[8/9] Deleting files for pkgconf-1.7.4,1: 100%
[9/9] Deinstalling png-1.6.37_1...
[9/9] Deleting files for png-1.6.37_1: 100%
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 9.16.19 for dns/bind916
>>> Aborted version 1.19.0 for net-mgmt/telegraf
*** Error code 1

Stop.
make: stopped in /usr/tools

**Comment by sreekupm** [comment]
I think port updated. net-mgmt/telegraf: update to 1.19.2 from 1.19.0. 
Please check the same

**Comment by sreekupm** [comment]
> Dear Franco,
> 
> Sorry for the above mistakes, I have updated ports then its working, but again failed another one
> 
> Deinstallation has been requested for the following 9 packages:
> 
> Installed packages to be REMOVED:
> expat: 2.4.1
> fontconfig: 2.13.94,1
> freetype2: 2.10.4
> libfontenc: 1.1.4
> mkfontscale: 1.2.1
> pkg: 1.16.3
> pkgconf: 1.7.4,1
> png: 1.6.37_1
> urwfonts: 1.0_8
> 
> Number of packages to be removed: 9
> 
> The operation will free 22 MiB.
> [1/9] Deinstalling urwfonts-1.0_8...
> [1/9] Deleting files for urwfonts-1.0_8: 100%
> [2/9] Deinstalling fontconfig-2.13.94,1...
> [2/9] Deleting files for fontconfig-2.13.94,1: 100%
> [3/9] Deinstalling mkfontscale-1.2.1...
> [3/9] Deleting files for mkfontscale-1.2.1: 100%
> [4/9] Deinstalling freetype2-2.10.4...
> [4/9] Deleting files for freetype2-2.10.4: 100%
> [5/9] Deinstalling expat-2.4.1...
> [5/9] Deleting files for expat-2.4.1: 100%
> [6/9] Deinstalling libfontenc-1.1.4...
> [6/9] Deleting files for libfontenc-1.1.4: 100%
> [7/9] Deinstalling pkg-1.16.3...
> [7/9] Deleting files for pkg-1.16.3: 100%
> [8/9] Deinstalling pkgconf-1.7.4,1...
> [8/9] Deleting files for pkgconf-1.7.4,1: 100%
> [9/9] Deinstalling png-1.6.37_1...
> [9/9] Deleting files for png-1.6.37_1: 100%
> 
> > > > ERROR: The build encountered fatal issues!
> > > > Aborted version 9.16.19 for dns/bind916
> > > > Aborted version 1.19.0 for net-mgmt/telegraf
> > > > *** Error code 1
> 
> Stop.
> make: stopped in /usr/tools

Dear Team, any Idea?

**Comment by AdSchellevis** [comment]
unfortunately we can't offer this level of community support.

**Comment by sreekupm** [comment]
Ok, When I try to make dvd, no log file is generated any idea about that?

**Comment by sreekupm** [comment]
> unfortunately we can't offer this level of community support.

apart from community support any other support option is available ?

**Comment by mimugmail** [comment]
Just comment telegraf in ports.conf, you only need it if you host a repo. 
For me ports compile fine without telegraf

**Comment by AdSchellevis** [comment]
commercial support is handled via Deciso in the Netherlands, you can use the forum (https://forum.opnsense.org/) to discuss as well, but looking briefly into the issues you are running into I doubt this will lead to results soon to be honest. 

Best always start with a clean environment and follow the exact steps for a stable release as described in the documentation.

**Comment by sreekupm** [comment]
> commercial support is handled via Deciso in the Netherlands, you can use the forum (https://forum.opnsense.org/) to discuss as well, but looking briefly into the issues you are running into I doubt this will lead to results soon to be honest.
> 
> Best always start with a clean environment and follow the exact steps for a stable release as described in the documentation.

Thanks for the reply. 
I have tried over 10 times :(. 
I will try more

**Comment by fichtner** [comment]
These are normal day to day problems when dealing with FreeBSD ports to be honest. It makes no sense to support them in any other capacity than fixing the ports repository as these builds affect nightly performance -> https://nightly.opnsense.org/

Make sure to cache your distfiles. Log files are only generated for nightly runs, but just pipe your output through tee utility. It's not like there is no transparency and documentation for build tools.


Cheers,
Franco

**Comment by mimugmail** [comment]
With disabling telegraf in ports.conf and plugins.conf I was able to build a dvd.

**Comment by mksbcisco** [comment]
> > Dear Franco,
> > Sorry for the above mistakes, I have updated ports then its working, but again failed another one
> > Deinstallation has been requested for the following 9 packages:
> > Installed packages to be REMOVED:
> > expat: 2.4.1
> > fontconfig: 2.13.94,1
> > freetype2: 2.10.4
> > libfontenc: 1.1.4
> > mkfontscale: 1.2.1
> > pkg: 1.16.3
> > pkgconf: 1.7.4,1
> > png: 1.6.37_1
> > urwfonts: 1.0_8
> > Number of packages to be removed: 9
> > The operation will free 22 MiB.
> > [1/9] Deinstalling urwfonts-1.0_8...
> > [1/9] Deleting files for urwfonts-1.0_8: 100%
> > [2/9] Deinstalling fontconfig-2.13.94,1...
> > [2/9] Deleting files for fontconfig-2.13.94,1: 100%
> > [3/9] Deinstalling mkfontscale-1.2.1...
> > [3/9] Deleting files for mkfontscale-1.2.1: 100%
> > [4/9] Deinstalling freetype2-2.10.4...
> > [4/9] Deleting files for freetype2-2.10.4: 100%
> > [5/9] Deinstalling expat-2.4.1...
> > [5/9] Deleting files for expat-2.4.1: 100%
> > [6/9] Deinstalling libfontenc-1.1.4...
> > [6/9] Deleting files for libfontenc-1.1.4: 100%
> > [7/9] Deinstalling pkg-1.16.3...
> > [7/9] Deleting files for pkg-1.16.3: 100%
> > [8/9] Deinstalling pkgconf-1.7.4,1...
> > [8/9] Deleting files for pkgconf-1.7.4,1: 100%
> > [9/9] Deinstalling png-1.6.37_1...
> > [9/9] Deleting files for png-1.6.37_1: 100%
> > > > > ERROR: The build encountered fatal issues!
> > > > > Aborted version 9.16.19 for dns/bind916
> > > > > Aborted version 1.19.0 for net-mgmt/telegraf
> > > > > *** Error code 1
> > 
> > 
> > Stop.
> > make: stopped in /usr/tools
> 
> Dear Team, any Idea?

Sorry for raking up an old post
My build is also failing at same point... were you able to solve this?
Let me know what you did

**Comment by JPBeltman** [comment]
For creating logs you can use | tee log.txt

Make base .... | tee base_log.txt for example, a base_log.txt will be available in /tools afterwards
