### ISSUE TITLE
sysutils/puppet7: packaging issue, file missing

### ISSUE THREAD

**Issue by fraenki** [opnsense/tools#246]
Trying to run Puppet Agent from puppet7-7.9.0 results in the following error:

```
$ puppet agent -t
cannot load such file -- /usr/local/lib/ruby/site_ruby/2.7/puppet
```

After comparing the OPNsense puppet7 package to the official FreeBSD package, I've noticed that puppet.rb is missing from the OPNsense package:

```
# OPNsense
$ pkg info -l puppet7 | grep '2.7/puppet.rb'
-OR-
$ tar jtvf puppet7-7.9.0.txz | grep '2.7/puppet.rb'
(yields no results)

# FreeBSD
$ tar jtvf puppet7-7.10.0.txz | grep '2.7/puppet.rb'
-rw-r--r--  0 root   wheel   13665 Aug 11 15:52 /usr/local/lib/ruby/site_ruby/2.7/puppet.rb
```

So it looks like something went wrong while building the package. Are there any logs available?

(Initially I've reported it to FreeBSD because I thought it was an issue with the port, see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257686.)

**Comment by AdSchellevis** [comment]
are you sure you pulled our ports tree before build? 7.9.0 is the previous version, we seemed to have pulled the latest in https://github.com/opnsense/ports/commit/e7b4a17aafd5c56bf68bf937e6d17ba8abec71bb

**Comment by fraenki** [comment]
@AdSchellevis No, I'm using the official package from the OPNsense repo:
https://pkg.opnsense.org/FreeBSD:12:amd64/21.7/latest/Latest/puppet7.txz
...and it's missing this crucial file.

**Comment by AdSchellevis** [comment]
@fraenki you can try our previous package (https://pkg.opnsense.org/FreeBSD:12:amd64/21.7/MINT/21.7/OpenSSL/All/puppet7-7.8.0.txz) or build the current one in our ports tree, we will likely ship a new release in a couple of weeks

**Comment by fraenki** [comment]
Version 7.8.0 was also broken. I'll try to build a new package directly from the current OPNsense ports tree and report back afterwards.

**Comment by AdSchellevis** [comment]
thanks, if that doesn't work, we probably have to check on our end why it's different.

**Comment by fraenki** [comment]
OK, with current ports tree and default options the manually built package contains the required file:

```
[root@opnsense ~/ports/sysutils/puppet7]# ALLOW_UNSUPPORTED_SYSTEM=1 make package
[...]
[root@opnsense ~/ports/sysutils/puppet7]# tar jtvf work/pkg/puppet7-7.10.0.txz | grep '2.7/puppet.rb'
-rw-r--r--  0 root   wheel   13665 Aug 11 15:52 /usr/local/lib/ruby/site_ruby/2.7/puppet.rb
```

I'll wait for the next OPNsense release and test the official release package again.

**Comment by fraenki** [comment]
On OPNsense 21.7.2 this issue is fixed:

```
root@opnsense:~ # opnsense-version 
OPNsense 21.7.2 (amd64/OpenSSL)

root@opnsense:~ # pkg info '*puppet7*'
puppet7-7.10.0

root@opnsense:~ # pkg info -l puppet7 | grep '2.7/puppet.rb'
	/usr/local/lib/ruby/site_ruby/2.7/puppet.rb
```

**Comment by fichtner** [comment]
It's likely https://github.com/opnsense/tools/commit/ad95a2af872a -- make -s usage has been broken in FreeBSD ports forever and all attempts to bring patches into it have silently failed where new bugs have been added...
