### ISSUE TITLE
config: test for matching FreeBSD release

### ISSUE THREAD

**Issue by till** [opnsense/tools#260]
I didn't read the README too carefully and only discovered after a few hours of building all the kernel/system mismatches which triggered a failure in the end of the entire process. Is it possible to check the OS-Version in the `Makefile` early on? Not entirely sure if I know enough make to do, but I'm happy to give it a shot if there's a general interest. :)

**Comment by fichtner** [comment]
@till sure, fair enough... I'll think of something :)
