### ISSUE TITLE
Request: Add libusb to repository

### ISSUE THREAD

**Issue by tstack77** [opnsense/tools#273]
Please

**Comment by fichtner** [comment]
Reason?

**Comment by tstack77** [comment]
Implement uhubctl to reset cellular modem when necessary.

uhubctl is utility to control USB power per-port on smart USB hubs.
https://github.com/mvp/uhubctl

**Comment by AdSchellevis** [comment]
https://www.freebsd.org/cgi/man.cgi?usbconfig ?

**Comment by JPBeltman** [comment]
Could you mention the needed spec? Don't mind trying to build a port/plug-in/package for you, but it's quite hard without knowing what for.

Usbconfig works for me on b13.0-stable and 22.1

**Comment by tstack77** [comment]
root@OPNsense:~ # usbconfig
ugen0.1: <0x8086 XHCI root HUB> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)
ugen1.1: <Intel EHCI root HUB> at usbus1, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (0mA)
ugen1.2: <vendor 0x8087 product 0x8001> at usbus1, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (0mA)
ugen0.2: <VIA Labs, Inc. USB2.0 Hub> at usbus0, cfg=255 md=HOST spd=HIGH (480Mbps) pwr=ON (0mA)`

`root@OPNsense:~ # usbconfig ugen1.2 power_off`
or
`root@OPNsense:~ # usbconfig ugen0.2 power_off`

Both commands seem to run without error, but they do not have the desired result of turning power off of the usb port. Strange that both display "pwr=ON (0mA)", and "pwr=OFF (0mA)" after command sent, as they are definitely providing power.

I have a qotom q355g4, maybe there is something in the bios that is overriding.
