### ISSUE TITLE
Availability CrowdSec package/port

### ISSUE THREAD

**Issue by JPBeltman** [opnsense/tools#274]
_disclaimer: CrowdSec is available, in beta version only, as plug-in for OPN 21.7 & 22.1. It was released on January 22th via their [git](https://github.com/crowdsecurity/opnsense-plugin-crowdsec)_

Has anyone already managed to port/package CrowdSec for aarch64? Asking for a friend. 

I've only checked sources I've known to be reliable/work: OPN/; tools, plugins & conf and the ftp of @yrzr, so apologies if I've missed yours. 

I'll try to build it myself this weekend. @yrzr , I'm using your RPI image currently, may I send/share the package with you to include in your packages if it succeeds (excluding current bugs in CS repo & after your own tests ofc)?

Also, since I've already mentioned you twice. Regarding the performance of the PI4 image, my (weird) test setup:  isp:LAN->NIC;WAN:opn_pi:LAN;usb3->WAN:switch:LAN->WAN:wireless_router:(2x 2.4GHz-, 1x 5GHZ-device), got max. 240 mbps, min. 90 down / max., min. 30 up during simultaneous speed tests with minimal config opposed to 350d/30u from isp router on single device. Not bad!

**Comment by AdSchellevis** [comment]
Best ask them if/when they plan to upstream a plugin into our community repository.  As long as it's distributed under BSD 2 clause and has a maintainer, I don't see a reason why we couldn't accept it. (maybe some notes on integration https://github.com/crowdsecurity/opnsense-plugin-crowdsec/commit/c982a3ff9c4ef0f2d47fbf20b11565cd3965c668#r64558460, which might not be a blocker at all)

**Comment by yrzr** [comment]
@JPBeltman I find the package is in the[ FreeBSD port](https://www.freshports.org/security/crowdsec).

There is no need to add the package to my server. You can simply enable the official FreeBSD repository in `/etc/pkg/FreeBSD.conf` and install this particular package. Remember to disable this repository after installation and do NOT upgrade `pkg`.
