### ISSUE TITLE
Request: include crowdsec packages

### ISSUE THREAD

**Issue by mmetc** [opnsense/tools#280]
I am ironing out the kinks of the [crowdsec plugin](https://github.com/crowdsecurity/opnsense-plugin-crowdsec) and it depends on the packages security/crowdsec (>=1.3.2) and security/crowdsec-firewall-bouncer (>=0.0.23r2). They already landed in your ports tree. Can you add them to ports.conf too so that I can release the plugin? I have not tested ARM.

The previous releases of the two packages don't work correctly with OPNsense. To my understanding I can't specify dependency versions, that's the reason I am asking now.

Thanks a lot

**Comment by fichtner** [comment]
@mmetc would you mind doing a PR to ports.conf ?

**Comment by mmetc** [comment]
https://github.com/opnsense/tools/pull/281
