### ISSUE TITLE
make dvd. Stop

### ISSUE THREAD

**Issue by gitmessage** [opnsense/tools#282]
FreeBSD 13.0

follow: https://github.com/opnsense/tools/blob/master/README.md

pkg install git
cd /usr
git clone https://github.com/opnsense/tools
cd tools
make update
make dvd

cp: /usr/obj/usr/tools/config/22.1/OpenSSL:amd64/.pkg/All/*: No such file or directory
*** Error code 1

Stop.

The image.
Thanks!
[
<img width="716" alt="Snipaste_2022-03-22_20-41-16" src="https://user-images.githubusercontent.com/24708498/159510335-3456ae40-f480-4d3c-9b6f-58430dd756f0.png">
](url)

**Comment by fichtner** [comment]
Possibly wrong pkg version in build host.

**Comment by gitmessage** [comment]
pkg in FreeBSD 13.0 is 1.17.5
build dvd 
Error:
pkg: No packge files have been found
*** Error code 1

Stop.

Then I change /ports-mgmt/pkg/Makefile  /ports-mgmt/pkg/distinfo from 1.16.3 to 1.17.5

Error:

cp: /usr/obj/usr/tools/config/22.1/OpenSSL:amd64/.pkg/All/*: No such file or directory
*** Error code 1

What can I do?

Thanks very much!

**Comment by fichtner** [comment]
> Then I change /ports-mgmt/pkg/Makefile /ports-mgmt/pkg/distinfo from 1.16.3 to 1.17.5

No, you install 1.16.3 and it's good...

https://forum.opnsense.org/index.php?topic=27597.msg134044#msg134044

**Comment by gitmessage** [comment]
Thanks. I will try.

**Comment by gitmessage** [comment]
Follow your suggest. It worked.
Thanks!
