### ISSUE TITLE
make dvd error: Could not find package:opnsens

### ISSUE THREAD

**Issue by gitmessage** [opnsense/tools#286]
This is hard to access github.com. Then clone source of opnsense (core src tools plugin)to local gitlab.
Build dvd, error: Could not find package:opnsens. Please see the pic. Thanks!
<img width="721" alt="Snipaste_2022-04-11_01-02-16" src="https://user-images.githubusercontent.com/24708498/162631113-3f6aea30-63fd-4b1b-a35d-e6046b76695a.png">

**Comment by gitmessage** [comment]
I edit Makfile
GITBASE?=(my local gitlab url)
Thanks!

**Comment by turboproc** [comment]
You might want to run 
```
make core
```
first as it should build the opnsense package.

**Comment by fichtner** [comment]
> GITBASE?=(my local gitlab url)

Maybe you should fix your product name ;)
