### ISSUE TITLE
Support requested: updating a set

### ISSUE THREAD

**Issue by turboproc** [opnsense/tools#293]
May be I missed something i documentation that belongs to this repository and therefore asking the following. If I have a (e.g.) package set available in version 21.1.4 (package-21.1.4)  and I want to upgrade this one to 21.1.8, is it required to rebuild the complete set? I could imagine a procedure whereby the existing set is completely unpacked, the changed parts are being upgraded (usually only a few) and the new set with upgraded parts is being packed again into one set. Strange idea?

**Comment by fichtner** [comment]
Not a strange idea, just not very well suited: needs large amount of downloads and also requires rebuilding/repackaging, we only really need all packages when doing offline ABI safe reinstalls which require reinstalling all packages anyway.


Cheers,
Franco
