### ISSUE TITLE
make update does not seem to pull backported patch to freebsd ports

### ISSUE THREAD

**Issue by JohannesNeu** [opnsense/tools#295]
Hi,
I encountered a gdb bug in freebsd for aarch64 builds. It probably affects many packages but I stumbled over it trying to buid the icinga2 package. The problem was fixed upstream with a backported patch ( https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=264095 ) and I was able to verify it by compiling icinga2 with freebsd. I then set up a opnsense build environment on a newly set up machine and did "make install ports-incinga2 DEVICE=ARM64" which led to the same error I received on normal freebsd ports, before the patch was backported (https://cgit.freebsd.org/ports/commit/?id=c5722abb6a5cfdb83d8e2fcce271cba48dbd7281).

Is it possible that "make update" does not pull this patch?

**Comment by fichtner** [comment]
Make update does not pull upstream changes.

**Comment by fichtner** [comment]
More patience waiting for ports sync please? Or apply fix locally.

**Comment by JohannesNeu** [comment]
thanks! I will write a ticket over there then :-)
