### ISSUE TITLE
22.1 build: prefetch-packages issue

### ISSUE THREAD

**Issue by clementmoulin** [opnsense/tools#298]
Hi

I trying to build a custom images, but the process fails on "Installing packages".
After some debug I have found the issue: using `prefetch-packages` the downloaded packages set are using the old extension ".txz" and current build script is looking for the new extension ".pkg".

Is it possible to update the packages set ?

Because on mirror I can see that the packages set is only available for 22.1 and not for minor updates.

**Comment by fichtner** [comment]
All off it is working as intended. If you want to prefech 22.1 use the 22.1 build tag.

Unfortunately the whole pkg extension thing has caused numerous incompatibilities for little benefit on our end.


Cheers,
Franco

**Comment by clementmoulin** [comment]
Yes, I know :/
But for now building VERSION=22.1 does not work if I try to use packages prefetched.

For others that might be interested to build last version without having to build all packages, I'm sharing my workaround:
```ABI=FreeBSD:13
ARCH=amd64
FLAVOR=OpenSSL
VER=22.1
VER_MINOR=.8

cd /usr/local/opnsense/build/$VER/$ARCH/sets/
mkdir packages/
cd packages/
rsync -vaz --delete rsync://mirror.wdc1.us.leaseweb.net/opnsense/$ABI:$ARCH/$VER/latest/Latest .
cd ..
rm packages-${VER}${VER_MINOR}-$FLAVOR-$ARCH.tar
tar cvf packages-${VER}${VER_MINOR}-$FLAVOR-$ARCH.tar -C packages/ .```

**Comment by fichtner** [comment]
VERSION=22.1 is not how you build version 22.1. Make sure to have all repositories used for building on the 22.1 tag instead.

As such 22.1 is a historic set that can help you get started and it's also used for offline upgrades during major version changes. It is what it is and it's all 99% of all users need.


Cheers,
Franco
