### ISSUE TITLE
Updater throws sqlite error on 22.7 vm images

### ISSUE THREAD

**Issue by maurice-w** [opnsense/tools#308]
When setting up a build system and building a vm image according to README.md, the updater in the resulting OPNsense image doesn't work.

Last time I built a vm image was probably 21.1 (worked fine), so not sure when exactly this broke.

**How to reproduce**

Install FreeBSD-13.0-RELEASE-amd64 (also tried 13.1, same issue), then:
```
# pkg install git
# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools
# make update [OS=13.0]
# make prefetch-base,kernel,packages [OS=13.0]
# make vm-vhdx [OS=13.0]
```
The resulting image boots and works fine, except for the updater:
```
***GOT REQUEST TO CHECK FOR UPDATES***
Currently running OPNsense 22.7 (amd64/OpenSSL) at Tue Jul 26 15:52:45 UTC 2022
Fetching changelog information, please wait... done
Updating OPNsense repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries: .......... done
OPNsense repository update completed. 797 packages processed.
All repositories are up to date.
pkg: warning: database version 36 is newer than libpkg(3) version 35, but still compatible
pkg: sqlite error while executing INSERT OR IGNORE INTO mtree(content) VALUES(?1) in file pkgdb.c:115: no such table: mtree
pkg: warning: database version 36 is newer than libpkg(3) version 35, but still compatible
pkg: sqlite error while executing INSERT OR IGNORE INTO mtree(content) VALUES(?1) in file pkgdb.c:115: no such table: mtree
self: No packages available to install matching 'opnsense'
***DONE***
```

**Comment by fichtner** [comment]
FreeBSD updated to pkg 1.18 making the database incompatible between 1.17 which we use and 1.18 which you get from their repo. This was discussed a couple of times now and the only practical solution is for us to update to 1.18, but I can't do that before a major release for risk of regression and that includes the business edition 22.10 which is still 3 months away.

I'll try to test impact of the 1.18 update for us when I can but it will be at least 2 weeks with all things going on right now.


Cheers,
Franco

**Comment by fichtner** [comment]
FWIW, this probably is https://github.com/opnsense/tools/issues/249 which was reported earlier but takes too much effort to fix on your side (besides doing the update mentioned here).

**Comment by maurice-w** [comment]
No worries, I'll just wait for the official DVD image then and do a manual VM install. And good to know it's not an entirely new issue.

Good luck with the 22.7 release!

Maurice

**Comment by JohannesNeu** [comment]
You can try to work around it if you don't mind the hassle: https://forum.opnsense.org/index.php?topic=29418.msg142180#msg142180  I am compiling right now and it seems to work, but no idea if I may run into a problem further down the road.

**Comment by maurice-w** [comment]
I now tried a simpler workaround: When setting up the build system, use an official OPNsense 22.7.r1 image instead of vanilla FreeBSD. All other steps as outlined above. This works for me!
```
***GOT REQUEST TO CHECK FOR UPDATES***
Currently running OPNsense 22.7 (amd64/OpenSSL) at Tue Jul 26 21:54:26 UTC 2022
Fetching changelog information, please wait... done
Updating OPNsense repository catalogue...
Fetching meta.conf: . done
Fetching packagesite.pkg: .......... done
Processing entries: .......... done
OPNsense repository update completed. 797 packages processed.
All repositories are up to date.
Checking integrity... done (0 conflicting)
Your packages are up to date.
Checking for upgrades (109 candidates): .......... done
Processing candidates (109 candidates): . done
Checking integrity... done (0 conflicting)
Your packages are up to date.
***DONE***
```

**Comment by JohannesNeu** [comment]
thanks for the advice! I will try this in my next run :-)

**Comment by fichtner** [comment]
Handling this via #249 as mentioned.
