### ISSUE TITLE
make clean-core unable to find files due to naming

### ISSUE THREAD

**Issue by JohannesNeu** [opnsense/tools#309]
I just stumbled upon a minor problem with make clean-core.
It seems to look for files with an "-aarch64.txz" ending but when you compile with DEVICE=RPI, then the files end with "aarch64-RPI.txz", hence they cannot be found by the script.

```
root@generic:/usr/tools # make clean-core
>>> Removing core from packages set
>>> Setting up stage in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Setting up base in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
tar: Error opening archive: Failed to open '/usr/local/opnsense/build/22.7/aarch64/sets/base-*-aarch64.txz'
*** Error code 1

Stop.
make: stopped in /usr/tools
root@generic:/usr/tools # ls /usr/local/opnsense/build/22.7/aarch64/sets/
base-22.7.r1_10-aarch64-RPI.txz		kernel-22.7.r1_10-aarch64-RPI.txz

```

**Comment by fichtner** [comment]
Not sure. It looked like it was fixed in 2019.. fd9e920b21f ... if still the case I need more info. Closing for now since stale.

**Comment by fichtner** [comment]
BTW you do have to run `make clean-core DEVICE=RPI`. It's not clear if you have it pinned as an environment but that would be the obvious mistake. Always use DEVICE if you use it once...
