### ISSUE TITLE
How to configure a software package

### ISSUE THREAD

**Issue by ggsnpdsn** [opnsense/tools#314]
There are two cases, I don't know where to configure

1. I added a new software package, which is not in ports. I want to compile it into the installation file and run it immediately after startup.

2. I need to compile a software package in ports, such as mongodb50. I want to compile it into the installation file and run it immediately after startup.

**Comment by fichtner** [comment]
For 1. you might want to start with https://docs.freebsd.org/en/books/porters-handbook/ and 2. https://docs.freebsd.org/en/books/handbook/ports/

I don't think there will be more answers here to such basic (FreeBSD) things.
