### ISSUE TITLE
make dvd failed

### ISSUE THREAD

**Issue by ggsnpdsn** [opnsense/tools#315]
I compile according to this step. I only want to compile the software required by opnsense, but it seems that all packages have been compiled. Is there a command like make menuconfig to select the installation package?

# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools
# make update
# mkdir -p /tmp/opnsense
# cd /tmp/opnsense
# git clone https://github.com/opnsense/tools
# cd tools
# env ROOTDIR=/tmp/opnsense make update
# make dvd
Creating repository in /usr/obj/usr/tools/config/22.7/OpenSSL:amd64/.pkg-new/: 100%
Packing files for repository: 100%
>>> Removing packages set
>>> Creating package mirror set for 22.7_78-OpenSSL-amd64... done
-rw-r--r--  1 root  wheel   668M Aug 11 14:40 packages-22.7_78-OpenSSL-amd64.tar
>>> WARNING: The build provided additional info.
>>> Package list inconsistency for emulators/qemu-guest-agent
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 1.19 for databases/p5-DBD-Sybase
>>> Aborted version 9.16.31 for dns/bind916
>>> Aborted version 3.5.12_1,1 for mail/postfix35
>>> Aborted version 3.2_1 for mail/rspamd
>>> Aborted version 2.0.1_12 for net-mgmt/bandwidthd
>>> Aborted version 2.13.4 for net-mgmt/icinga2
>>> Aborted version 1.2.8p25_3 for net-mgmt/mk-livestatus
>>> Aborted version 1.35.1 for net-mgmt/netdata
>>> Aborted version 1.23.0_2 for net-mgmt/telegraf
>>> Aborted version 16.27.0 for net/asterisk16
>>> Aborted version 4.36.2_4 for net/v2ray
>>> Aborted version 20200512_1 for opnsense/dhcp6c
>>> Aborted version 2.4.0 for opnsense/google-api-php-client@php80
>>> Aborted version 22.1 for opnsense/installer
>>> Aborted version 22.7 for opnsense/lang
>>> Aborted version 19.1.3 for opnsense/pam_opnsense
>>> Aborted version 2.0.37 for opnsense/phpseclib@php80
>>> Aborted version 22.7 for opnsense/update
>>> Aborted version 7.17.3_3 for sysutils/beats7
>>> Aborted version 1.11.3_4 for sysutils/consul
>>> Aborted version 2.8.0_6 for sysutils/nut
>>> Aborted version 1.8_4 for www/lightsquid
>>> Aborted version 1.22.0_7,3 for www/nginx
>>> Aborted version 2.4.0_2 for www/sarg
>>> Aborted version 1.9.2 for www/webgrind
*** Error code 1

Stop.
make: stopped in /tmp/opnsense/tools
#
It took 2 days and this error occurred. How can I compile the ISO installation file?

**Comment by JohannesNeu** [comment]
I get the same error doing "make arm DEVICE=RPI".

```
Creating repository in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64/.pkg-new/: .......... done
Packing files for repository: .... done
>>> Removing packages set
>>> Creating package mirror set for 22.7.1_31-OpenSSL-aarch64... done
-rw-r--r--  1 root  wheel   639M Aug 14 20:42 packages-22.7.1_31-OpenSSL-aarch64.tar
>>> WARNING: The build provided additional info.
>>> Skipped version 1.19,2 for lang/go
>>> Package list inconsistency for emulators/qemu-guest-agent
>>> Skipped version 3.1.0,1 for net/luasocket
>>> Skipped version 4.36.2_4 for net/v2ray
>>> Skipped version 0.0.20220316_4,1 for net/wireguard-go
>>> Skipped version 22.7.1 for opnsense/lang
>>> Skipped version 1.8.7_4 for security/vault
>>> Skipped version 7.17.3_3 for sysutils/beats7
>>> Skipped version 1.11.3_4 for sysutils/consul
>>> Skipped version 1.3.1_4 for sysutils/node_exporter
>>> Skipped version 2.12.0_2 for textproc/minify
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 1.36.0 for net-mgmt/netdata
>>> Aborted version 2.8.0_6 for sysutils/nut
*** Error code 1

Stop.
make: stopped in /usr/tools
root@generic:/usr/tools # 
```

I would assume that this line causes the problems?
```
...
>>> Package list inconsistency for emulators/qemu-guest-agent
...
```

I checked the ports.sh and found these lines: 
```
	elif ! make -C ${PORTSDIR}/\${PORT} check-plist \${MAKE_ARGS}; then
		echo ">>> Package list inconsistency for \${PORT_ORIGIN}" >> /.pkg-msg
```

So I checked whether the folder was there and it is:
```
root@generic:/usr/tools # ls -la /usr/ports/emulators/ | grep qemu-guest-agent
drwxr-xr-x    3 root  wheel   512 May 12 10:22 qemu-guest-agent
```

Next I tried building it and I think it worked?:
```
root@generic:/usr/ports/emulators/qemu-guest-agent # make -C /usr/ports/emulators/qemu-guest-agent/
...
gmake[2]: Leaving directory '/usr/ports/emulators/qemu-guest-agent/work/qemu-5.0.1'
===>  Staging for qemu-guest-agent-5.0.1
===>   Generating temporary packing list
gmake[2]: Entering directory '/usr/ports/emulators/qemu-guest-agent/work/qemu-5.0.1'
/usr/bin/install -c -d -m 0755 "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/share/qemu"
/usr/bin/install -c -d -m 0755 "/usr/ports/emulators/qemu-guest-agent/work/stage/var"/run
/usr/bin/install -c -d -m 0755 "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/include"
/usr/bin/install -c -d -m 0755 "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/bin"
/usr/bin/install -c -c -m 0755 qemu-ga ivshmem-client ivshmem-server qemu-nbd qemu-storage-daemon qemu-img qemu-io qemu-edid  "/usr/por
ts/emulators/qemu-guest-agent/work/stage/usr/local/bin"
strip "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/bin/qemu-ga" "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/lo
cal/bin/ivshmem-client" "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/bin/ivshmem-server" "/usr/ports/emulators/qemu-gues
t-agent/work/stage/usr/local/bin/qemu-nbd" "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/bin/qemu-storage-daemon" "/usr/p
orts/emulators/qemu-guest-agent/work/stage/usr/local/bin/qemu-img" "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/bin/qemu
-io" "/usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/bin/qemu-edid"
gmake[2]: Leaving directory '/usr/ports/emulators/qemu-guest-agent/work/qemu-5.0.1'
/bin/mkdir -p /usr/ports/emulators/qemu-guest-agent/work/stage/usr/local/qemu
====> Compressing man pages (compress-man)
===> Staging rc.d startup script(s)
root@generic:/usr/ports/emulators/qemu-guest-agent # 
```

So I assumed "make check-plist" would work, but it doesn't:
```
root@generic:/usr/ports/emulators/qemu-guest-agent # make -C /usr/ports/emulators/qemu-guest-agent check-plist
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: bin/ivshmem-client
Error: Orphaned: bin/ivshmem-server
Error: Orphaned: bin/qemu-storage-daemon
Error: Orphaned: @dir qemu
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/emulators/qemu-guest-agent
```

Is this because I did not pass the \${MAKE_ARGS} arguments? Or might this be the actual error? And why would the compilation work but not check-plist?

**Comment by bet0x** [comment]
I compiled it and just works. I executed an make update then repeat with make dvd and done. Same error, same package.

**Comment by sreekupm** [comment]
@ggsnpdsn 

Please read the instructions and follow the steps.

**Comment by ggsnpdsn** [comment]
> @ggsnpdsn
> 
> Please read the instructions and follow the steps.

What's wrong with my steps? Which compilation instructions do I follow? Is there a link

**Comment by sreekupm** [comment]
@ggsnpdsn 

Do the below steps 

# pkg install git
# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools
# make update
# make dvd

**Comment by fichtner** [comment]
Timeout.
