### ISSUE TITLE
`make ports PORTSLIST="..."` doesn't override the list from config

### ISSUE THREAD

**Issue by johnnyslee** [opnsense/tools#318]
I've been using the following command to build single package:
```
sudo make ports SETTINGS="22.7" PORTSENV="DEPEND=no PRUNE=no" PORTSLIST="dns/dnsmasq" PORTSBRANCH="dnsmasq-git"
```
but suddenly it started to build everything in `ports.conf`, instead of just the package plus its dependencies.
I have to replace the contents of `ports.conf` with just the value of `PORTSLIST`.

**Comment by fichtner** [comment]
Oops, likely since 968e273e0639cee9b504f2ff66757cd22526f65f

I’ll fix, but currently on vacation so it could take a bit.
