### ISSUE TITLE
ld: error: undefined symbol: ip6_get_fwdtag

### ISSUE THREAD

**Issue by turboproc** [opnsense/tools#321]
Upgraded my Rock PI 4 host to FreeBSD 13.1 , trying to build latest OPNSense for a R4S target, being stopped by following error message:
```
ld: error: undefined symbol: ip6_get_fwdtag
>>> referenced by ip6_fastfwd.c
>>>               ip6_fastfwd.o:(ip6_tryforward)
>>> referenced by ip6_fastfwd.c
>>>               ip6_fastfwd.o:(ip6_tryforward)
>>> referenced by ip6_forward.c
>>>               ip6_forward.o:(ip6_forward)
ld: error: undefined symbol: ip6_flush_fwdtag
>>> referenced by ip6_forward.c
>>>               ip6_forward.o:(ip6_forward)
--- kernel ---
*** [kernel] Error code 1

make[2]: stopped in /usr/obj/usr/src/arm64.aarch64/sys/SMP-ARM
--- all_subdir_usb ---

make[3]: stopped in /usr/src/sys/modules
--- all_subdir_zfs ---

make[3]: stopped in /usr/src/sys/modules
--- all_subdir_tmpfs ---

make[3]: stopped in /usr/src/sys/modules
--- modules-all ---
*** [modules-all] Error code 2

make[2]: stopped in /usr/obj/usr/src/arm64.aarch64/sys/SMP-ARM
2 errors

make[2]: stopped in /usr/obj/usr/src/arm64.aarch64/sys/SMP-ARM
--- buildkernel ---

make[1]: stopped in /usr/src
--- buildkernel ---

make: stopped in /usr/src
*** Error code 2

Stop.
```
Any idea where to look for the cause of this ?

**Comment by fichtner** [comment]
ip6_get_fwdtag() is our code, but I don't see why it's not found as it's properly prototyped in sys/netinet6/ip6_var.h which is also included from ip6_fastfwd.c

**Comment by turboproc** [comment]
Hi @fichtner , checked that already and indeed prototyping is there. What I cannot find is the file (<something>.c) that in the provides the referenced function. Compiling seems to go OK, linking shows the error. Any suggestion where this file would be located ?

**Comment by turboproc** [comment]
Hi @fichtner, weird case, took a while to understand that the `sys/netinet6/ip6_output.c` file was corrupt. For what ever reason the part that contains the ...tag() functions was not there. Syncing the file and re-building solved the issue. No clue how this could happen.

**Comment by fichtner** [comment]
freebsd-update utility by default also updates /usr/src, that would be my first guess

**Comment by turboproc** [comment]
That explains. Had my host upgraded from 13.0 to 13.1 last week.

**Comment by fichtner** [comment]
Aha, found it then 😊 closing since solved
