### ISSUE TITLE
Make aarch64 packages

### ISSUE THREAD

**Issue by nabrog87** [opnsense/tools#326]
Hello,
I have successfully created base, kernel and xtools sets for aarch64, but  have an error while trying to make the packages .
here is the log
host arch: amd64

  >>> Running build step: ports
>>> Passing arguments: (none)
>>> Setting up stage in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Setting up base in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Setting up /usr/ports clone in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Setting up /usr/src clone in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Setting up xtools in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Setting up chroot in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
ELF ldconfig path: /lib /usr/lib /usr/lib/compat
32-bit compatibility ldconfig path:
>>> Setting up distfiles in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Extracting packages in /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64
>>> Extract failed: no packages set found
===>   go-1.19,2 depends on file: /usr/local/sbin/pkg - not found
[20221026065309] ===> License BSD2CLAUSE accepted by the user
[20221026065309] ===> Fetching all distfiles required by pkg-1.17.5_1 for building
[20221026065309] ===> Extracting for pkg-1.17.5_1
[20221026065309] ===> License BSD2CLAUSE accepted by the user
[20221026065309] ===> Fetching all distfiles required by pkg-1.17.5_1 for building
[20221026065309] => SHA256 Checksum OK for freebsd-pkg-1.17.5_GH0.tar.gz.
[20221026065309] ===> Patching for pkg-1.17.5_1
[20221026065309] ===> Applying FreeBSD patches for pkg-1.17.5_1 from /usr/ports/ports-mgmt/pkg/files
[20221026065309] ===> Configuring for pkg-1.17.5_1
No installed jimsh or tclsh, building local bootstrap jimsh0
No working C compiler found. Tried cc and gcc.
[20221026065310] ===> Script "configure" failed unexpectedly.
Please report the problem to pkg@FreeBSD.org [maintainer] and attach the
"/usr/obj/usr/ports/ports-mgmt/pkg/work/pkg-1.17.5/config.log" including the
output of the failure of your make command. Also, it might be a good idea to
provide an overview of all packages installed on your system (e.g. a
/usr/obj/usr/ports/ports-mgmt/pkg/work/pkg-1.17.5/src/pkg-static info -g -Ea).
*** Error code 1
Stop.
make[2]: stopped in /usr/ports/ports-mgmt/pkg
*** Error code 1
Stop.
make[1]: stopped in /usr/ports/ports-mgmt/pkg
*** Error code 1
Stop.
make: stopped in /usr/ports/lang/go
[20221026065311] ===> Cleaning for pkg-1.17.5_1
[20221026065311] ===> Cleaning for go-1.19,2

Below the contents of the config.log file

```
 Invoked as: ./configure
Tclsh: /usr/obj/usr/tools/config/22.7/OpenSSL:aarch64/usr/obj/usr/ports/ports-mgmt/pkg/work/pkg-1.17.5/jimsh0
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:4:7: error: use of undeclared identifier 'F_CLOSEM'
(void)F_CLOSEM;
      ^
1 error generated.
============
The failed code was:
#include <fcntl.h>
int main(void) {
#ifndef F_CLOSEM
(void)F_CLOSEM;
#endif
return 0;
}
============
Failed: cc -g -O2 conftest__.c -o conftest__
ld: error: undefined symbol: arc4random_stir
>>> referenced by conftest__.c:3
>>>               /tmp/conftest__-1765d9.o:(main)
>>> did you mean: arc4random_stir@FBSD_1.0
>>> defined in: /lib/libc.so.7
cc: error: linker command failed with exit code 1 (use -v to see invocation)
============
The failed code was:
extern void arc4random_stir(void);
int main(void) {
arc4random_stir();
return 0;
}
============
Failed: cc -g -O2 conftest__.c -o conftest__
ld: error: undefined symbol: basename_r
>>> referenced by conftest__.c:3
>>>               /tmp/conftest__-813738.o:(main)
>>> did you mean: basename_r@FBSD_1.2
>>> defined in: /lib/libc.so.7
cc: error: linker command failed with exit code 1 (use -v to see invocation)
============
The failed code was:
extern void basename_r(void);
int main(void) {
basename_r();
return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'sys/statfs.h' file not found
#include <sys/statfs.h>
         ^~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <sys/statfs.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
============
The failed code was:
#include <endian.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o -lelf
cc: warning: -lelf: 'linker' input unused [-Wunused-command-line-argument]
conftest__.c:2:1: error: use of undeclared identifier 'Elf_Note'
Elf_Note _x;
^
1 error generated.
============
The failed code was:
int main(void) {
Elf_Note _x;
return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/err.h' file not found
#include <bsd/err.h>
         ^~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/err.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/libutil.h' file not found
#include <bsd/libutil.h>
         ^~~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/libutil.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/readpassphrase.h' file not found
#include <bsd/readpassphrase.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/readpassphrase.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/stdio.h' file not found
#include <bsd/stdio.h>
         ^~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/stdio.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/stdlib.h' file not found
#include <bsd/stdlib.h>
         ^~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/stdlib.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/strlib.h' file not found
#include <bsd/strlib.h>
         ^~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/strlib.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/string.h' file not found
#include <bsd/string.h>
         ^~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/string.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/sys/cdefs.h' file not found
#include <bsd/sys/cdefs.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/sys/cdefs.h>
int main(void) {

return 0;
}
============
Failed: cc -g -O2 -c conftest__.c -o conftest__.o
conftest__.c:1:10: fatal error: 'bsd/unistd.h' file not found
#include <bsd/unistd.h>
         ^~~~~~~~~~~~~~
1 error generated.
============
The failed code was:
#include <bsd/unistd.h>
int main(void) {

return 0;
}
============
pkg-config --modversion atf-c : Package atf-c was not found in the pkg-config search path.
Perhaps you should add the directory containing `atf-c.pc'
to the PKG_CONFIG_PATH environment variable
Package 'atf-c', required by 'virtual:world', not found
```

What am I missing? 
Thank you!

**Comment by nabrog87** [comment]
All seem to work. now ,I removed the sets and rerun "make update"  then recreated the sets.
I started  creating the packages. and all seems to be ok. for now..
Don't know what was the problem, because I always followed the same steps.
Thank you!

**Comment by fichtner** [comment]
@nabrog87 glad you could solve it. let's close then!
