### ISSUE TITLE
Add btop package

### ISSUE THREAD

**Issue by x390** [opnsense/tools#327]
Please add [sysutils/btop](https://www.freshports.org/sysutils/btop).

**Comment by x390** [comment]
Hi, I don't mean to be pushy but can this be added anytime soon? Thanks in advance.

**Comment by fichtner** [comment]
@mimugmail you probably want to remove this from your repo if you have it

**Comment by fichtner** [comment]
Ok no it still pulls in gcc12 as a dependency. No way this is going in.

> Updating FreeBSD repository catalogue...
> FreeBSD repository is up to date.
> All repositories are up to date.
> The following 8 package(s) will be affected (of 0 checked):
>
> New packages to be INSTALLED:
> 	binutils: 2.40_4,1
> 	btop: 1.2.13_1
>	**gcc12: 12.2.0_6**
>	gmp: 6.2.1
>	liblz4: 1.9.4,1
>	mpc: 1.3.1_1
>	mpfr: 4.2.0_1,1
>	zstd: 1.5.5
>
> Number of packages to be installed: 8
>
> The process will require **460 MiB more space**.
> **95 MiB to be downloaded**.

**Comment by mimugmail** [comment]
I dont offer it either ...

**Comment by fichtner** [comment]
I confused this with htop it seems.
