### ISSUE TITLE
make dvd 785¨

### ISSUE THREAD

**Issue by thuttu** [opnsense/tools#330]
>>> Setting up distfiles in /usr/obj/usr/tools/config/22.7/OpenSSL:amd64
>>> Extracting packages in /usr/obj/usr/tools/config/22.7/OpenSSL:amd64
>>> Extract failed: no packages set found
make: chdir /usr/ports//usr/tools/config/22.7/ports.conf: No such file or directory
cp: /usr/obj/usr/tools/config/22.7/OpenSSL:amd64/.pkg/All/*: No such file or directory
*** Error code 1

I Think that something is wrong about generating ports conf dir. (Double directories in make: chdir)

**Comment by fichtner** [comment]
There isn't much to go on here. The error was probably much earlier. No packages set  = no dvd.

**Comment by thuttu** [comment]
make: chdir /usr/ports//usr/tools/config/22.7/ports.conf: No such file or directory
Is first error I can see on stdout is there better ways to look what happens but anyway
in build make: chdir /usr/ports//usr/tools/config/22.7/ports.conf: No such file or directory contains oddness 
it looks like that there is /usr/ports/ and /usr/tools/config/22.7/ports.conf combined which is not real directory 
ports conf is atleast on /usr/tools/config/22.7/ports.conf this problem came after make update and I was iriginally trying to build RPI version which fails same way any idea what I should look?

**Comment by fichtner** [comment]
"dvd" is the wrong target for building an ARM device... do you have one with a DVD drive?

**Comment by fichtner** [comment]
Ok, our nightly build exhibits the same issue so this is broken and was reverted... 6b61fb18d47

**Comment by thuttu** [comment]
Odd make dvd still fails same way even I did clean freebsd install and project setup
For clearify fails were with make dvd (AMD64) and make packages DEVICE=RPI

**Comment by fichtner** [comment]
thanks, this is awfully weird. I'll look into it on Monday
