### ISSUE TITLE
"make vm-vmdk" don`t add changes of menu.xml in ISO

### ISSUE THREAD

**Issue by andyoulovexy** [opnsense/tools#333]
![image](https://user-images.githubusercontent.com/38940994/211234287-80ddeb21-fd3a-4acc-906d-6523821d6635.png)
![image](https://user-images.githubusercontent.com/38940994/211234298-cff529d8-1724-4528-aa22-5f5497ad4d91.png)

**Comment by fichtner** [comment]
Uncommitted changes like your additional files are not built into core package. That‘s why the error exists. ;)

**Comment by mimugmail** [comment]
Just add the two of first screenshot here https://github.com/opnsense/core/blob/master/plist

(your fort please) :)

**Comment by fichtner** [comment]
The idea is: your modifications, your choices.
