### ISSUE TITLE
Build a single installable plugin

### ISSUE THREAD

**Issue by cardigliano** [opnsense/tools#339]
Building a plugin requires running "make plugins" (as reported in https://docs.opnsense.org/development/examples/helloworld.html#create-an-installable-plugin), however this takes a long time to compile all plugins and complete.
Any chance we can build a single plugin?
Thank you.

**Comment by fichtner** [comment]
Just use an existing OPNsense install?

**Comment by cardigliano** [comment]
I need to build packages for third party OPNsense plugins

**Comment by fichtner** [comment]
Ok?! Don’t let me keep you 😊

**Comment by cardigliano** [comment]
Back to my question, we used to create plugin packages 'manually' with _pkg create_ / _tar_, using as package name os-xxx and adding +MANIFEST, +POST_INSTALL, plist, and the plugin sources to this tarball. However those packages seems to be no longer detected in the plugins list in the latest OPNsense GUI. For this reason I decided to move to a more standard approach by using the 'tools' as described in the documentation. However this approach seems to trigger a huge OPNsense building process rather than just creating a small plugin installer. Any chance you can improve this?

**Comment by mimugmail** [comment]
Just clone the plugins repo, add you code to some folder, enter it and type "make package", then you get all what you need :)

**Comment by cardigliano** [comment]
This seems to be what I was looking for. My 5 cents: I suggest adding a note in https://docs.opnsense.org/development/examples/helloworld.html#create-an-installable-plugin
Thank you for the hint!
