### ISSUE TITLE
Add cloudflared

### ISSUE THREAD

**Issue by binzhou** [opnsense/tools#342]
If I understand correctly, this is available as a binary package now: https://github.com/cloudflare/cloudflared/issues/145#issuecomment-1046101572

Could this please be added to the opnsense pkgs? Would be very useful to be able to run cloudflare tunnels from opnsense.

**Comment by mimugmail** [comment]
Its in my repo and works fine 

https://www.routerperformance.net/opnsense-repo/

If you add it to official just ping me and I remove it over there :)

**Comment by fichtner** [comment]
No plans for the time being.

**Comment by sammyke007** [comment]
@mimugmail Is this still possible? I can't seem to find it in Packages?

**Comment by sammyke007** [comment]
> Did you activate the repo? https://www.routerperformance.net/opnsense-repo/

Yes, it's there:

![Screenshot_2023-11-30-21-30-22-96_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/opnsense/tools/assets/33524412/0f6f0a7f-818c-4b99-8f24-d7c398117eb6)

**Comment by mimugmail** [comment]
cloudflared is only a package, not a plugin

**Comment by sammyke007** [comment]
> cloudflared is only a package, not a plugin 

OK, so installing it should be
pkg install cloudflared
?

Is it explained somewhere how to configure it?

I found this guide: https://www.jackpearce.co.uk/cloudflared-opnsense/

**Comment by mimugmail** [comment]
Looks good yes, maybe rc is already in

**Comment by sammyke007** [comment]
It works perfectly fine, tnx!

**Comment by hmorneau** [comment]
The package haven't been updated, at this point it's more than a year old.
