### ISSUE TITLE
Installed pkg version '1.19' does not match required version '1.18'

### ISSUE THREAD

**Issue by HRTshazab** [opnsense/tools#343]
I was trying to build image from the current opnsense stable version 23.1.
Getting this error 

`>>> Running build step: ports
>>> Passing arguments: (none)
Installed pkg version '1.19' does not match required version '1.18'
*** Error code 1

Stop.
make: stopped in /home/shazab/opnsense/tools`
![image](https://user-images.githubusercontent.com/103932126/216915237-c3c72fdd-00cf-422c-8275-4fd45be5342e.png)

**Comment by mimugmail** [comment]
You need to install pkg 1.18 via ports

**Comment by afteroot** [comment]
@mimugmail  could you please explain, how to do it ?

**Comment by mimugmail** [comment]
Not a good idea to warm up an old issue as the result might not fix your problems.

**Comment by afteroot** [comment]
But i have almost same error )
```
>>> Running build step: ports

Passing arguments: (none)
Installed pkg version '1.20' does not match required version '1.19'
*** Error code 1
```
So  fix is, 
```
/usr/ports/ports-mgmt/pkg
make reinstall
```
after that  issue is solved
```
[root@build /usr/ports/ports-mgmt/pkg]# pkg --version
1.19.2
```

**Comment by mimugmail** [comment]
Yep, thats all :)
