### ISSUE TITLE
Image creation question

### ISSUE THREAD

**Issue by opnsense2** [opnsense/tools#347]
Hello, need help.
If I fork repositories and change something in them (for example, the appearance of OpenSense), do I need to make changes to the tools/Makefile file before building the image?
I'm going to make an image from my forked repositories.

Thank you.

**Comment by fichtner** [comment]
It depends on the changes? 😉

basically community support ends when you change something which causes breakage you want resolved via these questions.

**Comment by opnsense2** [comment]
> It depends on the changes? 😉
> 
> basically community support ends when you change something which causes breakage you want resolved via these questions.

I changed the location of the menu items and in some places the fonts in the "core".
Didn't change anything else.
Do I need to replace GITBASE?= https://github.com/opnsense
to my account name? Then it will take my repository "core"?

**Comment by fichtner** [comment]
GITBASE is just for initial fetch. What matters is that /usr/core has YOUR branch checked out and all changes added as commits in order to land in the final image. The build will nag about misconfiguration, but branches can be overridden when required or change build.conf accordingly.

**Comment by opnsense2** [comment]
> GITBASE is just for initial fetch. What matters is that /usr/core has YOUR branch checked out and all changes added as commits in order to land in the final image. The build will nag about misconfiguration, but branches can be overridden when required or change build.conf accordingly.

# pkg install git
# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools
# make update

That is, here it is necessary to clone not only "tools", but also the rest of MY forked repositories (src.git, ports.git, core.git and plugins.git)?

**Comment by opnsense2** [comment]
> You can replace /usr/core with anything you want, add separate remotes to existing git, check out other branches... Yes feel free to modify GITBASE but as I said you will only clone once per build VM setup and afterwards you have to make manual adjustments anyway.

Where is the build.conf file?

**Comment by fichtner** [comment]
oO

https://github.com/opnsense/tools/blob/master/config/23.1/build.conf

**Comment by opnsense2** [comment]
> oO
> 
> https://github.com/opnsense/tools/blob/master/config/23.1/build.conf

Yes, I just found it
To use my core, you need to add a line there:
core_REPO=https://github.com/my_username/core.git
?

**Comment by fichtner** [comment]
just use "make GITBASE=https://github.com/my_username update". Last time: after initial clone of the repos GITBASE does not matter at all

**Comment by opnsense2** [comment]
> make GITBASE=https://github.com/my_username update

LUA?=		5.4
OS?=		13.1
PERL?=		5.32
PHP?=		81
PYTHON?=	39
RUBY?=		27
SSL?=		openssl
make GITBASE=https://github.com/opnsense2 update

Is that right (build.conf file)?

**Comment by fichtner** [comment]
# make GITBASE=https://github.com/opnsense2 update

is the command to run ;) you CAN edit build.conf and you will have to, but not for the reasons you think I just said
