### ISSUE TITLE
lstat("/usr/obj/usr/tools/config/23.1/aarch64/work/boot/cdboot"): No such file or directory

### ISSUE THREAD

**Issue by answer1573** [opnsense/tools#348]
Follow these steps:
# pkg install git
# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools
# make update
**#make DEVICE=ARM64 dvd**
Environment
'''# uname -a
FreeBSD Opensense 13.1-RELEASE FreeBSD 13.1-RELEASE releng/13.1-n250148-fc952ac2212 GENERIC arm64
**The error is as follows:**
4096 bytes transferred in 0.000078 secs (52248230 bytes/sec)
Creating `/usr/obj/usr/tools/config/23.1/aarch64/efiboot.img'
/usr/obj/usr/tools/config/23.1/aarch64/efiboot.img: 4039 sectors in 4039 FAT12 clusters (512 bytes/cluster)
BytesPerSec=512 SecPerClust=1 ResSectors=1 FATs=2 RootDirEnts=512 Sectors=4096 Media=0xf0 FATsecs=12 SecPerTrack=63 Heads=255 HiddenSecs=0
Populating `/usr/obj/usr/tools/config/23.1/aarch64/efiboot.img'
Image `/usr/obj/usr/tools/config/23.1/aarch64/efiboot.img' complete
>>> Building dvd image... makefs: cd9660_add_boot_disk: lstat("/usr/obj/usr/tools/config/23.1/aarch64/work/boot/cdboot"): No such file or directory
*** Error code 1

**Comment by fichtner** [comment]
ARM doesn’t have a DVD. That’s what the “arm” image is for. 😉
