### ISSUE TITLE
RaspberryPi build "Could not find package: py39-duckdb"

### ISSUE THREAD

**Issue by mestafin** [opnsense/tools#350]
I am trying to build OPNsense 23.1 for RaspberryPi.

I am doing a cross-compile on a vm running FreebSD 13.1

I am following the recommended steps:

```
# pkg install git
# cd /usr
# git clone https://github.com/opnsense/tools
# cd tools

```

In MakeFile I updated the entry:

DEVICE? = RPI2
```

# make update

# make base kernel

# make xtools

```
`# make packages`

This fails with the following message:

```
....
....
Extracting py39-Jinja2-3.1.2: 100%
Installing py39-dnspython-2.3.0,1...
Extracting py39-dnspython-2.3.0,1: 100%
Could not find package: py39-duckdb
*** Error code 1

Stop.
make: stopped in /usr/tools
```

Any advice?

**Comment by fichtner** [comment]
Probably not  for this architecture. I will propose a fix next week.

**Comment by mestafin** [comment]
Any feedback?

**Comment by fichtner** [comment]
See 340d1c4 and 5f79844

**Comment by mestafin** [comment]
Your fix solved the problem of ducked, but now I have another problem:
