### ISSUE TITLE
Please add step-cli

### ISSUE THREAD

**Issue by dabo-devconsole** [opnsense/tools#360]
Please add step-cli, even without a plugin, it would be really helpful.
https://smallstep.com/docs/step-cli/installation/#freebsd
https://www.freshports.org/security/step-cli/

step is an easy-to-use CLI tool for building, operating, and automating Public Key Infrastructure (PKI) systems and workflows. step acts as front-end interface to [Certificate Manager](https://smallstep.com/docs/certificate-manager/) and [step-ca](https://smallstep.com/docs/step-ca/), an online X.509 and SSH Certificate Authority (CA). step is also a standalone, general-purpose PKI toolkit: You can use it for many common crypto and X.509 operations.

Thanks in advance

**Comment by fichtner** [comment]
Hi,

https://github.com/smallstep/cli/blob/master/go.mod ends up a little heavy on the build and distribution side as it adds 8 MB (compressed) to the packages set. I have to decline this.


Cheers,
Franco
