### ISSUE TITLE
*Support* How to rebuild the missing packages only, not the entire list of ports?

### ISSUE THREAD

**Issue by kontrol-br** [opnsense/tools#362]
Hi Franco,
good day!

I am compiling a custom list of ports to support a package I am working with (Squid+ E2guardian + NTLM auth + Samba413)
I have enabled NIS back to the core and added "samba413" to the ports list. I also have compiled all previous ports from the original list.
Additionally I have added the kernel option to enable the "UCHCOM" driver to support an Arduino nano board which is being used as an LCD display controller. So far, so good.
Now I just want to compile the missing packages like "samba413" and its dependencies. 
Unfortunately I could not find a way to do it.
Could you please let me know how to make that with the script options?
Thank You!
Fabricio.

**Comment by kontrol-br** [comment]
Awesome!  Thanks @fichtner Franco, I will git it a try, very soon.
I will post results back here.
Thanks Much!
Fabricio.

**Comment by fichtner** [comment]
Assuming this worked. Closing.

**Comment by kontrol-br** [comment]
Thanks Franco.  Yes, it worked. 
Much appreciated.
