### ISSUE TITLE
Building vm images of older versions

### ISSUE THREAD

**Issue by nerrehmit** [opnsense/tools#364]
I am currently trying to build opnsense qcow2 vm images of different versions for the use with a cloud provider.

I did manage to successfully create a qcow2 image of the current 23.1 release just using the steps outlined in the README.

However I lack the know-how to understand what is needed to build an image of version 22.7 (or possibly 23.7 once released).
What I've tried is supplying the VERSIONS in different variables when running make
`make prefetch-distfiles,kernel VERSION="22.7" SRCBRANCH="stable/22.7" ABI="22.7"`
`make vm-qcow2,5G,1G ABI="22.7" SRCBRANCH="stable/22.7"`

but this still errored out and apparently used the wrong directory
```
>>> Running build step: plugins
>>> Passing arguments: (none)
pkg-static: Invalid ABI
pkg-static: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
pkg-static: Invalid ABI
pkg-static: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
>>> Setting up stage in /usr/obj/usr/tools/config/23.1/amd64
>>> Setting up base in /usr/obj/usr/tools/config/23.1/amd64
>>> Setting up chroot in /usr/obj/usr/tools/config/23.1/amd64
ELF ldconfig path: /lib /usr/lib /usr/lib/compat
32-bit compatibility ldconfig path:
>>> Extracting packages in /usr/obj/usr/tools/config/23.1/amd64
>>> Removing packages in /usr/obj/usr/tools/config/23.1/amd64: 
>>> Installing packages in /usr/obj/usr/tools/config/23.1/amd64: pkg git
pkg: Invalid ABI
pkg: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
pkg: No packages installed.  Nothing to do!
pkg: Invalid ABI
pkg: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
Installing pkg-1.19.1_1...
pkg: wrong architecture: FreeBSD:13:amd64 instead of 22.7

Failed to install the following 1 package(s): ./.pkg/All/pkg-1.19.1_1.pkg
*** Error code 1

Stop.
make: stopped in /usr/tools
```

I'd appreciate any hint or pointing me to documentation helping me with this. Thanks

**Comment by fichtner** [comment]
I'm pretty sure setting ABI=22.7 manually will wreck the build here:

    pkg: wrong architecture: FreeBSD:13:amd64 instead of 22.7

Usually SETTINGS=22.7 should suffice... but you've left it at default which is 23.1.

**Comment by nerrehmit** [comment]
Thanks for the quick response and the usefull pointer. Using SETTING it worked!

Just for completness those were my steps for building a vm image based on 22.7

```
git checkout tags/22.7
make update
git checkout tags/22.7
make prefetch-distfiles,kernel,base,packages SETTINGS="22.7"
make vm-qcow2,5G,1G SETTINGS="22.7"
```
