### ISSUE TITLE
The Buillding took more than a day and is not finished yet 

### ISSUE THREAD

**Issue by Ammar-UT** [opnsense/tools#365]
it's normal ?
i have 18gb RAM
125gb SSD
i7 - 12th gen 
running freebsd 13-1 
20Mb internet speed 
after a while it stop and got an error 
" could not find ddclient-devel " 

does there any way to make a dvd image without building the plugins ?

**Comment by mimugmail** [comment]
If you dont need the plugin just comment it in https://github.com/opnsense/tools/blob/master/config/23.1/plugins.conf#L8

**Comment by Ammar-UT** [comment]
it's normal to take all this time for building?

**Comment by mimugmail** [comment]
Sure, did you ever compile Rust from source? :)

**Comment by fichtner** [comment]
Quite normal considering you probably also have no distfiles prefetched.

**Comment by Ammar-UT** [comment]
No, this is the first time :). 

What is the fastest way to make an img? 
When I run make dvd I got error 
' Couldn't find package stunnel' but the package already installed 
so I run ' make hotfix-rebuild' not finished yet.

**Comment by Ammar-UT** [comment]
No, this is the first time :). 

What is the fastest way to make an img? 
When I run make dvd I got error 
' Couldn't find package stunnel' but the package already installed 
so I run ' make hotfix-rebuild' not finished yet. 


    Until this moment it is not over yet, error show when running
 ' make dvd  : could not find packages php81-opcache'
it's already installed and build finish for this package. 
' make ports-www/php81-opcache packages : zabbix62 not exist' 

cd to usr/ports and run 
'make : patch error in www/iridium and www/ungoogled '
cd to /usr/ports/www/iridium and run 
' make : finish successfully after 54000'

Any help🙂

**Comment by Ammar-UT** [comment]
Until this moment it is not over yet, error show when running
 ' make dvd  : could not find packages php81-opcache'
it's already installed and build finish for this package. 
' make ports-www/php81-opcache packages : zabbix62 not exist' 

cd to usr/ports and run 
'make : patch error in www/iridium and www/ungoogled '
cd to /usr/ports/www/iridium and run 
' make : finish successfully after 54000'

Any help🙂
