### ISSUE TITLE
make opnsense could not find package basnmp-regex error code 1 

### ISSUE THREAD

**Issue by cvsyun013** [opnsense/tools#37]
I according to your production step by step step by step to appear a mistake to ask how to deal with

help  me please
![34](https://cloud.githubusercontent.com/assets/5831248/16607252/9d98b3ec-4371-11e6-8717-e5b9097acbeb.png)

**Comment by fichtner** [comment]
Look, I really don't know why the package didn't build, this is the wrong build step. We need a log trail (100 lines!) of "make ports" build in order to get that sorted...

**Comment by cvsyun013** [comment]
这个打包工具能不能完善下啊 错了也没有日志的  您上次发说1-2天发我一个打包的vm镜像啊 已经过去快一周了啊
This package can not improve the tools under the wrong ah, there is no log of the last time you said 1-2 sent me a package of VM mirror ah have been past nearly a week ah

**Comment by fichtner** [comment]
I'm sorry, but I think you are in over your head with handling build systems and/or FreeBSD. It's too time consuming to debug this.

**Comment by cvsyun013** [comment]
I also debug run quickly, I have been debugging for a long time, you are convenient to send me a VM to make a mirror image? Too many errors I follow FreeBSD to deal with a variety of errors with a fast 10 days without the ability to rule out the problem and network problems

**Comment by cvsyun013** [comment]
This production tool has been open source so it should be directly available to use instead of modifying the system has nothing to do with the error ah

**Comment by fichtner** [comment]
It works, please review your setup. :)
