### ISSUE TITLE
add net-mgmt/tcpreplay

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/tools#372]
Just leaving this here so I don't forget.

While testing it's sometimes practical to have tcpreplay available (https://github.com/opnsense/ports/tree/master/net-mgmt/tcpreplay), if it doesn't add too much build time, I would like to add it to our list.

**Comment by fichtner** [comment]
@AdSchellevis This adds over 15 minutes to the build and 6 MB to the resulting packages set file. I'm leaning towards leaving it out unless you really see the benefit.

**Comment by AdSchellevis** [comment]
@fichtner thanks for testing this for me, I'll just build it manually when I need it.

**Comment by mimugmail** [comment]
I can create a list of pkg which might not be relevant anymore if it helps?
