### ISSUE TITLE
Add package base64

### ISSUE THREAD

**Issue by giggio** [opnsense/tools#375]
It is super useful for scripting.

https://www.freshports.org/converters/base64/

**Comment by giggio** [comment]
I installed the port from feshports (git clone, make, make install), but ended up using `openssl enc -base64 -A`, as it works without needing the port.
This is a common package, so you might want to include it.
I did not have to install any special tooling (or maybe it was already there, IDK).

**Comment by fichtner** [comment]
@giggio I'm also using OpenSSL when necessary. PHP, Python and Perl can do it too with ease so I'm not sure how useful this will be (factoring in this is the first time in a decade I'm hearing this sort of request).

**Comment by giggio** [comment]
@fichtner I've been using base64 for a while, and if you search you'll find it is a common tool. Maybe more on the Linux side, which I'm familiar with.
If you don't think this applies, feel free to close it.

**Comment by giggio** [comment]
Thanks! <3

**Comment by fichtner** [comment]
Sure, sorry this took so long. 😊
