### ISSUE TITLE
Ads security/xray-core to ports and pkgs.

### ISSUE THREAD

**Issue by drlebedev** [opnsense/tools#378]
## Request
Add new package xray-core from Freebsd ports (https://www.freshports.org/security/xray-core/). 

## Requester
Upstream port Maintainer

## Context
The xray core is an encrypted connection proxy that helps to penetrate the censoring firewalls.  Xray is a feature-reach fork of v2ray that is included in the OpnSense package list but is not updated and is not effective today.  Xray is fully config-compatible with v2ray and can be used as a drop-in replacement.  Maintainers of OpnSense pkg repo can consider obsolete v2ray version replacement with xray.

It supports state-of-the-art encryption and obfuscation tools to build custom network topologies and overcome traffic filtering. It supports 

1. Shadowscoks, including Shadowsocks 2022
2. Socks 
3. Vless/VMess
4. Trojan

Traffic can be routed via CDN (Cloudflare) with the support of Websocket and gRPC transport.

## OpnSense pkg repo fit
As Xray is a network security and penetration tool, it fits the core function of OpnSense. OpnSense already supports Shadowsocks (via plugin) and v2ray (obsolete pkg version). Including Xray in packages helps to mitigate security risks from obsolete packages and migrate to the state-of-the-art secure proxy as a drop-in replacement.

**Comment by drlebedev** [comment]
@fichtner Any chance you can take a look on this?

**Comment by drlebedev** [comment]
@fichtner  quick ping on above

**Comment by fichtner** [comment]
@drlebedev Sorry for the delay. Confirmed. v2ray will be replaced by xray-core package in 23.7.8.

Cheers,
Franco
