### ISSUE TITLE
Add emulators/qemu-devel or emulators/qemu

### ISSUE THREAD

**Issue by samip5** [opnsense/tools#381]
It seems that since it defaults to USE_GL, I'm not quite sure how I would install it and I'm not sure how large of a package list it would generate.

Please look into it and I would prefer to just have qemu-img binary, but it seems to be a part of the main qemu port/pkg.

**Comment by fichtner** [comment]
I'm afraid I can't assist with this issue. The qemu agent in the packages is all we need as a project. Keep in mind the binary packages set are provided as upgrade bundles and adding large unused parts (also like rust and gcc and llvm) is not our intention because it would massively impact mirror performance, user disk requirements and wasted amounts of energy.

**Comment by samip5** [comment]
> upgrade bundles

Could you please tell me what do you mean by that? Do you mean that all of the extra parts would increase the total requirements for disk space as well on all installs?

**Comment by fichtner** [comment]
Take a look at the mirror:

https://pkg.opnsense.org/FreeBSD:13:amd64/23.7/sets/

The "packages" sets are full build sets required for offline upgrades. Addling llvm would probably add 100 MB to that 748 MB file. This stacks up rather quickly for no apparent gain to hundreds of thousands of users...

**Comment by samip5** [comment]
> Take a look at the mirror:
> 
> https://pkg.opnsense.org/FreeBSD:13:amd64/23.7/sets/
> 
> The "packages" sets are full build sets required for offline upgrades. Addling llvm would probably add 100 MB to that 748 MB file. This stacks up rather quickly for no apparent gain to hundreds of thousands of users...

Aaah, I see what you mean now. Okay that makes complete sense. It seems I should probably create my own pkg repository with the needed things compiled and use that instead of compiling on my firewall. :)

**Comment by fichtner** [comment]
Yep, you can easily add third party packages. You could also manually add FreeBSD packages as long as they don't pull in conflicting options and changes (at least installing manually is a lot safer than enabling the FreeBSD package mirror).

    # pkg add -f link/to/freebsd/package/or/compiler


Cheers,
Franco

**Comment by samip5** [comment]
Ah, that was much more easy than I thought to just use upstream pkgs. :)

Crisis averted.

**Comment by fichtner** [comment]
@samip5 ok both happy :)
