### ISSUE TITLE
Strongswan curl fetcher 

### ISSUE THREAD

**Issue by belerovon** [opnsense/tools#384]
**Important notices**

Before you add a new report, we ask you kindly to acknowledge the following:

- [x] I have read the contributing guide lines at https://github.com/opnsense/core/blob/master/CONTRIBUTING.md
- [x] I am convinced that my issue is new after having checked both open and closed issues at https://github.com/opnsense/core/issues?q=is%3Aissue

**Describe the bug**
I have the following Situation:

Setting up an IPSec with X509 Certificate

IPSec working and is up but in logs I can see CRL and OCSP Check are failing due to "no capable fetcher found"

CURL to OCSP and CRL from my Opnsense working correctly

Risk: That means that I can not revoke Certificates what is in my point of view a security Issue.

What i also have seen from swanctl --stats or ipsec statusall I can see that following modules are loaded:

> loaded plugins: charon aes des blowfish rc2 sha2 sha1 md4 md5 random nonce x509 revocation constraints pubkey pkcs1 pkcs7 pkcs12 pgp dnskey sshkey pem openssl pkcs8 fips-prf curve25519 xcbc cmac hmac kdf gcm drbg attr kernel-pfkey kernel-pfroute resolve socket-default stroke vici updown eap-identity eap-md5 eap-mschapv2 eap-radius eap-tls eap-ttls eap-peap xauth-generic xauth-eap xauth-pam whitelist addrblock counters

For me, it seems the Opnsense Strongwan package isn't build with the strongswan-mod-curl.

Think this would be really easy for you and increase the security.

**To Reproduce**
 * Using a PKI (e.g. openssl) and sign  X509 Usercertificate with a CRL and/or OCSP
 * Import CA to Truststore of Opnsnse so the certificates can be checked and trusted
 * VPN > IPsec > Tunnel Settings : Add in IPSec VPN with Mutal RSA Authentication method and select imported CA
 * Add a Phase 2
 * Open in terminal a tail -f: tail -f /var/log/ipsec/latest.log | grep "con"
 * Connect to IPSec

in logs you will see the connection comes up but with hint:

> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="293"] 05[LIB] <con4|52> unable to fetch from http://ocsp.xxxxxx.tld:8080, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="294"] 05[CFG] <con4|52> ocsp request to http://ocsp.xxxxxx.tld:8080 failed
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="295"] 05[CFG] <con4|52> ocsp check failed, fallback to crl
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="296"] 05[CFG] <con4|52>   fetching crl from 'http://crl.xxxxxx.tld/intermediate.crl.pem' ...
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="297"] 05[LIB] <con4|52> unable to fetch from http://crl.xxxxxx.tld/intermediate.crl.pem, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="298"] 05[CFG] <con4|52> crl fetching failed

**Expected behavior**
Strongswan should be able to use curl to fetch OCSP or CRL.
Strongswan on a Linux system have installed strongswan-mod-curl and with it seems to work correctly.

**Relevant log files**
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="293"] 05[LIB] <con4|52> unable to fetch from http://ocsp.xxxxxx.tld:8080, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="294"] 05[CFG] <con4|52> ocsp request to http://ocsp.xxxxxx.tld:8080 failed
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="295"] 05[CFG] <con4|52> ocsp check failed, fallback to crl
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="296"] 05[CFG] <con4|52>   fetching crl from 'http://crl.xxxxxx.tld/intermediate.crl.pem' ...
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="297"] 05[LIB] <con4|52> unable to fetch from http://crl.xxxxxx.tld/intermediate.crl.pem, no capable fetcher found
> <30>1 2023-05-19T12:35:04+02:00 zh-fw.xxxxxx.tld charon 17843 - [meta sequenceId="298"] 05[CFG] <con4|52> crl fetching failed

**Environment**
* OPNsense 23.1.7_3 (amd64).
* strongswan | 5.9.10_1

**Comment by fichtner** [comment]
To test:

    # opnsense-revert -z strongswan

Feedback welcome.


Cheers,
Franco

**Comment by doktornotor** [comment]
Looks good here. I guess the default CRL directory should be created when installing the port to avoid pointless log noise:

```
charon 16567 - [meta sequenceId="18"] 00[CFG] loading crls from '/usr/local/etc/ipsec.d/crls'
charon 16567 - [meta sequenceId="19"] 00[LIB] opening directory '/usr/local/etc/ipsec.d/crls' failed: No such file or directory

```

Otherwise there are no complaints any more about "no capable fetched" after installing, restarting ipsec with `configctl ipsec restart` and reconnecting the tunnel.

**Comment by belerovon** [comment]
Great - can confirm, OCSP now works


> <30>1 2023-11-15T20:06:08+01:00 zh-fw.xxxx.tld charon 16414 - [meta sequenceId="6413"] 13[CFG] <con4|6> checking certificate status of "C=DE, ST=BW, L=xxxx, O=xxxx, CN=xxxx, E=xxxx@xxxx.de"
> <30>1 2023-11-15T20:06:08+01:00 zh-fw.xxxx.tld charon 16414 - [meta sequenceId="6414"] 13[CFG] <con4|6>   requesting ocsp status from 'http://ocsp.xxxx.tld:8080' ...
> <30>1 2023-11-15T20:06:08+01:00 zh-fw.xxxx.tld charon 16414 - [meta sequenceId="6415"] 13[CFG] <con4|6>   ocsp response correctly signed by "C=xxx, ST=xxxx, L=xxxx, O=xxxx, CN=ocsp.xxxx.tld"
> <30>1 2023-11-15T20:06:08+01:00 zh-fw.xxxx.tld charon 16414 - [meta sequenceId="6416"] 13[CFG] <con4|6>   ocsp response is valid: until Nov 15 20:11:08 2023
> <30>1 2023-11-15T20:06:08+01:00 zh-fw.xxxx.tld charon 16414 - [meta sequenceId="6417"] 13[CFG] <con4|6> certificate status is good

**Comment by fichtner** [comment]
Thanks, will be in 23.7.9 then.

About the dir it's a bit weird:

https://github.com/opnsense/ports/blob/33100dc3340560c22c45599592ab5f453d34c50a/security/strongswan/pkg-plist#L397

But I can test this part and see if enforcing the dir from core makes sense.

**Comment by fichtner** [comment]
@doktornotor hmm for swanctl it should already point to `x509crl` and we do indeed clear all of `ipsec.d` to get rid of legacy configs. nothing should use it so not sure why it's looking there.

 https://github.com/opnsense/ports/blob/33100dc3340560c22c45599592ab5f453d34c50a/security/strongswan/pkg-plist#L413

**Comment by fichtner** [comment]
meh, I'll just push the directory structure back as this has been happening for a while: https://forum.opnsense.org/index.php?topic=33126.0

**Comment by fichtner** [comment]
@doktornotor this should do the trick :) https://github.com/opnsense/core/commit/b7f34d02

**Comment by doktornotor** [comment]
> meh, I'll just push the directory structure back as this has been happening for a while: https://forum.opnsense.org/index.php?topic=33126.0

Lol, yes, it's happy now with the empty dirs. 

[image](https://github.com/opnsense/tools/assets/1075960/5c13e446-faf4-4ff9-a9c5-8a8f1cf037e1)

There's really no way to make the noise go away otherwise. The excessive logging has been an issue with ipsec since forever, probably. Plus the logs don't help with debugging when it doesn't work anyway - at least not to the 99.99999% of users who did not write the strongswan code. 🤷‍♂️

**Comment by fichtner** [comment]
I skimmed the strongswan docs yesterday looking for a way to disable the ipsec.conf glue but it appears to be hardcoded... I mean we don't even need it. Maybe it can be disabled at build time?

**Comment by doktornotor** [comment]
Heh, AFAICT it'd require recompiling at least, maybe even patching. Not sure whether it's worth it.

**Comment by fichtner** [comment]
not important for now, but we will revisit at some point. cheers!
