### ISSUE TITLE
Add sysutils/bastille

### ISSUE THREAD

**Issue by jakefrancois** [opnsense/tools#396]
There are **no dependencies** since bastille is essentially just a bunch of shell scripts. My use case for this would be to install services into a jail (such as adguard) without having any potentially negative impact on the base opnsense installation. 

I know I can already do this with native jail commands, but bastille is a great tool for jail management!

https://github.com/BastilleBSD/bastille

**Comment by fichtner** [comment]
Sure, why not :)
