### ISSUE TITLE
make core error  code 1

### ISSUE THREAD

**Issue by cvsyun013** [opnsense/tools#40]
Install squid and start 

but error could not find package squide

error  code 1

**Comment by fichtner** [comment]
I'm entirely unsure what this refers to. Can you please be more specific?

**Comment by cvsyun013** [comment]
Hello fichtner, I was using the script make time, the other are make successful, but only make core time there is a bug:"error could not find package squide error code 1"

But I have installed squid

Before handling 16.1 times no mistake, make 16.7 reported the wrong please help me

**Comment by cvsyun013** [comment]
[
![3333](https://cloud.githubusercontent.com/assets/5831248/18575605/38e89b46-7c0c-11e6-9e4e-6cf99de7c986.png)
](url)

**Comment by fichtner** [comment]
Are you sure your tools.git is up to date? I have been away for two weeks so there have been no builds, it may be a problem with a port, but still impossible to tell from the report. I will run a fresh build to see...

**Comment by fichtner** [comment]
Try the latest change :)

**Comment by KhalidAldughayem** [comment]
i tried building it after the changes but make cdrom gives me this error [
![screenshot 1](https://cloud.githubusercontent.com/assets/17356281/18627102/cc99cf7a-7e61-11e6-9133-12c8bd5e0296.png)
](url)

**Comment by fichtner** [comment]
Src building failing is highly unusual. We need more output from these two commands (the screenshot doesn't show the actual error):

# make base
# make kernel
