### ISSUE TITLE
Installed pkg version '1.20' does not match required version '1.19'

### ISSUE THREAD

**Issue by KevinKrueger** [opnsense/tools#401]
>>> Running build step: ports
>>> Passing arguments: (none)
Installed pkg version '1.20' does not match required version '1.19'
*** Error code 1

Fresh version of FreeBSD was installed (13.2)

**Comment by fichtner** [comment]
Yep, install the 1.19 from our ports tree and you're good.

**Comment by KevinKrueger** [comment]
> Yep, install the 1.19 from our ports tree and you're good.

Thanks for your quick reply, but how can I do this for this specific version?

**Comment by fichtner** [comment]
It's under /usr/ports/ports-mgmt/pkg and just run "make package" followed by "make reinstall"

**Comment by KevinKrueger** [comment]
> It's under /usr/ports/ports-mgmt/pkg and just run "make package" followed by "make reinstall"

go: github.com/PuerkitoBio/goquery@v1.8.0: Get "https://proxy.golang.org/github.com/%21puerkito%21bio/goquery/@v/v1.8.0.mod": net/http: TLS handshake timeout
go: github.com/andybalholm/cascadia@v1.3.1: Get "https://proxy.golang.org/github.com/andybalholm/cascadia/@v/v1.3.1.mod": net/http: TLS handshake timeout
go: github.com/antchfx/htmlquery@v1.2.5: Get "https://proxy.golang.org/github.com/antchfx/htmlquery/@v/v1.2.5.mod": net/http: TLS handshake timeout
go: github.com/antchfx/xmlquery@v1.3.11: Get "https://proxy.golang.org/github.com/antchfx/xmlquery/@v/v1.3.11.mod": net/http: TLS handshake timeout
go: github.com/antchfx/xpath@v1.2.1: Get "https://proxy.golang.org/github.com/antchfx/xpath/@v/v1.2.1.mod": net/http: TLS handshake timeout
*** Error code 1

Stop.
make[2]: stopped in /usr/ports/ports-mgmt/fallout
*** Error code 1

Stop.
make[1]: stopped in /usr/ports/ports-mgmt/fallout
*** Error code 1

Stop.
make: stopped in /usr/ports/ports-mgmt

**Comment by fichtner** [comment]
What’s ports-mgmt/fallout? 🤨 you just need ports-mgmt/pkg

**Comment by KevinKrueger** [comment]
Okay wait ...

**Comment by KevinKrueger** [comment]
Ok. got it 😂

**Comment by fichtner** [comment]
👍

**Comment by KevinKrueger** [comment]
2024/04/04 19:57:13 [INFO] Cleaning up temporary folder: /tmp/buildenv_2024-04-04-1834.3027235153
2024/04/04 19:57:13 [FATAL] exit status 1
*** Error code 1

Stop.
make: stopped in /usr/ports/www/caddy-custom
[20240404195718] ===> Cleaning for xcaddy-0.3.5_3
[20240404195718] ===> Cleaning for caddy-custom-2.7.6.3.0.3.5.3_14
Updating database digests format: 100%
Checking integrity... done (0 conflicting)
Deinstallation has been requested for the following 3 packages:

Installed packages to be REMOVED:
	go120: 1.20.14
	pkg: 1.19.2_1
	xcaddy: 0.3.5_3

Number of packages to be removed: 3

The operation will free 218 MiB.
[1/3] Deinstalling pkg-1.19.2_1...
[1/3] Deleting files for pkg-1.19.2_1: 100%
[2/3] Deinstalling go120-1.20.14...
[2/3] Deleting files for go120-1.20.14: 100%
[3/3] Deinstalling xcaddy-0.3.5_3...
[3/3] Deleting files for xcaddy-0.3.5_3: 100%
Creating repository in /usr/obj/usr/tools/config/24.1/amd64/.pkg-new/: 100%
Packing files for repository: 100%
>>> Removing packages set
>>> Creating package mirror set for 24.1.4_52-amd64... done
-rw-r--r--  1 root  wheel   842M Apr  4 22:02 packages-24.1.4_52-amd64.tar
>>> ERROR: The build encountered fatal issues!
>>> Aborted version 2.7.6.3.0.3.5.3_14 for www/caddy-custom (caddy-custom)
*** Error code 1

Stop.
make: stopped in /usr/tools


After "make dvd"

**Comment by KevinKrueger** [comment]
Okay my first intuition was "make update" for both, but the result is still the same.
How do you do that?

**Comment by fichtner** [comment]
Our nightly build was fixed as expected. Make sure you have https://github.com/opnsense/tools/commit/efd30ee99 in your tools when you rebuild as that will fix caddy-custom random dependency switching...

**Comment by KevinKrueger** [comment]
So I have the commit but it still doesn't work. What can I do now?

**Comment by fichtner** [comment]
Provide more details :) Perhaps "make info" output can help. If you are doing local modifications that will be a source of error too. I don't know much about your particular build quest.


Cheers,
Franco

**Comment by KevinKrueger** [comment]
tools /usr/tools 24.1.4_1 efd30ee99 HEAD
src /usr/src 24.1.2_19 7efda340f stable/24.1
ports /usr/ports 24.1.4_130 292e9fabc master
plugins /usr/plugins 24.1.4 1cccb8b94 stable/24.1
core /usr/core 24.1.4_2 51a4f0a3a stable/24.1

I actually just want to create an ISO first.

**Comment by KevinKrueger** [comment]
Ok. Now I have an ISO :)

**Comment by fichtner** [comment]
What happened? :) I guess case closed (for now)?


Cheers,
Franco

**Comment by KevinKrueger** [comment]
> What happened? :) I guess case closed (for now)?
> 
> 
> 
> 
> 
> Cheers,
> 
> Franco

No, actually that's not it yet 🤣

I still have a bunch of questions:

- Where are libraries for the core stored?
- How is the data stored?
- Where is the data stored?
- What do I need to consider when creating modifications?

**Comment by fichtner** [comment]
To be fair, my willingness to give free community support for documented and open source code ends here.


Cheers,
Franco

**Comment by 459below** [comment]
> It's under /usr/ports/ports-mgmt/pkg and just run "make package" followed by "make reinstall"

Worked for me exactly like suggested by @fichtner . i.e.

```
pkg install portconfig
cd /usr/ports/ports-mgmt/pkg
make package
make reinstall
```

But I needed to make sure to *not* use `-j 4` like suggested here:

https://yrzr.github.io/tutorial-build-opnsense-arm64-on-a-rpi4/#6-tricks-to-accelerate-the-build

Or else it would fail like this

```
root@freebsd:/usr/ports/ports-mgmt/pkg # make -j4 package
--- package ---
--- check-license ---
===>  License BSD2CLAUSE accepted by the user
--- do-fetch ---
--- fetch-specials ---
===> Fetching all distfiles required by pkg-1.19.2_1 for building
--- /usr/ports/ports-mgmt/pkg/work/.extract_done.pkg._usr_local ---
`check-build-conflicts' was not built (deferred, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `check-build-conflicts' has .ORDER dependency against fetch (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT)
`extract-message' was not built (deferred, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `extract-message' has .ORDER dependency against check-build-conflicts (deferred, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)
`check-categories' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
`check-deprecated' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `check-deprecated' has .ORDER dependency against check-categories (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)
`check-vulnerable' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `check-vulnerable' has .ORDER dependency against check-deprecated (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)
`check-license' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `check-license' has .ORDER dependency against check-vulnerable (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)
`pre-check-config' was not built (unmade, type OP_DEPENDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
`pkg-depends' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `pkg-depends' has .ORDER dependency against check-sanity (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|CYCLE|DONECYCLE)
`fetch-depends' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `fetch-depends' has .ORDER dependency against pkg (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|CYCLE|DONECYCLE)
`do-fetch' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `do-fetch' has .ORDER dependency against fetch-depends (unmade, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)
`fetch-specials' was not built (unmade, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `fetch-specials' has .ORDER dependency against do-fetch (unmade, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)
`extract-depends' was not built (deferred, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `extract-depends' has .ORDER dependency against checksum (deferred, type OP_DEPENDS|OP_PHONY|OP_SUBMAKE|OP_HAS_COMMANDS|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|CYCLE|DONECYCLE)
`clean-wrkdir' was not built (deferred, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `clean-wrkdir' has .ORDER dependency against extract-depends (deferred, type OP_DEPENDS|OP_PHONY|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)
`/usr/ports/ports-mgmt/pkg/work' was not built (deferred, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND|OP_MARK, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `/usr/ports/ports-mgmt/pkg/work' has .ORDER dependency against clean-wrkdir (deferred, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)
`extract-fixup-modes' was not built (deferred, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|DONECYCLE)!
    `extract-fixup-modes' has .ORDER dependency against do-extract (deferred, type OP_DEPENDS|OP_PHONY|OP_HAS_COMMANDS|OP_DEPS_FOUND, flags REMAKE|DONE_WAIT|CYCLE|DONECYCLE)
*** [/usr/ports/ports-mgmt/pkg/work/.extract_done.pkg._usr_local] Error code 1

make[1]: stopped in /usr/ports/ports-mgmt/pkg
1 error

make[1]: stopped in /usr/ports/ports-mgmt/pkg
*** [package] Error code 2

make: stopped in /usr/ports/ports-mgmt/pkg
1 error

make: stopped in /usr/ports/ports-mgmt/pkg
```
