### ISSUE TITLE
No plug-ins while building R4S

### ISSUE THREAD

**Issue by turboproc** [opnsense/tools#402]
Building an image for R4S which runs fine apartt of the fact that none of the plug-ins (os-*) are being created in the packages archive. Any idea what might block this? Kernel and Base have been created without issues.

**Comment by fichtner** [comment]
Not enough info to make even a guess. How big is the packages set? Plugins step finished? Image built?

**Comment by turboproc** [comment]
Sorry, just discovered the following. ``www/caddy-custom`` fails to build and consequently the plugins are not being build.

Adding ``www/caddy-custom                                arm,aarch64`` to ports.conf avoids this port being build and solves the problem for now. Question is why the build of caddy-custom fails.

**Comment by fichtner** [comment]
We are working on it 😊
