### ISSUE TITLE
Building plugins aarch64 throws an error while parsing unknown

### ISSUE THREAD

**Issue by javierckr** [opnsense/tools#425]
Command:
` make -j6 VERSION=24.7 DEVICE=R4S plugins`

error: 
```
Packaging files for os-iperf-1.0_1:
pkg: manifest parsing error: error while parsing <unknown>: line: 1, column: 0 - 'key must begin with a letter', character: '-'
*** [package] Error code 1
```

**Comment by javierckr** [comment]
It builds without -j6 option
` make VERSION=24.7 DEVICE=R4S plugins`

**Comment by 459below** [comment]
There has been talk about the _-j_ option and how one should probably avoid it here https://github.com/opnsense/tools/issues/401

I think multi threading is taken care of somewhere else. So I do not really think there is an issue here.
