### ISSUE TITLE
Readme update to point to FreeBSD 14.1 instead 13.2

### ISSUE THREAD

**Issue by 459below** [opnsense/tools#427]
As I currently understand the build system expects 14.1 as seen here
https://github.com/opnsense/tools/blob/master/config/24.7/build.conf#L2

And in the error here:
```
make: "/usr/tools/Makefile" line 81: Found no configuration matching OS version "13.2"
```

If I am not mistaken on this, we should probably update the README.md here
https://github.com/opnsense/tools/blob/master/README.md?plain=1#L10

If someone else is not faster, I will propose a MR for this.

**Comment by fichtner** [comment]
Thanks, I changed it a bit 371a8cdb09 to reflect reality. The OS check is much newer than the README. It sort of looks like we could support multiple FreeBSD versions but the build code eventually has breaking changes so we delete configs related to older FreeBSD versions when they are EoL and we no longer use them.


Cheers,
Franco
