### ISSUE TITLE
Add net-mgmt/xymon-client

### ISSUE THREAD

**Issue by kumy** [opnsense/tools#434]
Could we please add `net-mgmt/xymon-client`
https://freebsd.pkgs.org/14/freebsd-amd64/xymon-client-4.3.30.pkg.html
https://www.freshports.org/net-mgmt/xymon-client

Relates to opnsense/plugins#4259

> Xymon is a system for monitoring servers and networks. It has a great deal
of inspiration from the Big Brother monitor, but unlike Big Brother it is
designed to work well whether you need to monitor small network with just
a handful of hosts, or large networks with thousands of hosts.
Xymon is the successor to the bbgen toolkit, which has been available as
an add-on to Big Brother since late 2002. The name change was decided upon
when Xymon acquired enough functionality to be a stand-alone product.
The tools that formed the bbgen toolkit are still present in Xymon
and are quite important for it, so if you have used bbgen before,
Xymon will seem quite familiar.
This is the client.
LICENSE: GPL2 or later
Groups: xymon

**Comment by kumy** [comment]
Thanks.
There was already a PR #435, closing it then :smile:

**Comment by AdSchellevis** [comment]
@kumy sorry about that, totally missed it

**Comment by kumy** [comment]
@AdSchellevis I'm not yet seeing package `xymon-client` on `24.7.8-amd64`, do I miss something? thx

```
# pkg update
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.

# pkg info net-mgmt/*
choparp-20150613_1
easy-rsa-3.2.1_1,1
flowd-0.9.1_5
iftop-1.0.p4_1
p5-Data-Validate-IP-0.27
p5-NetAddr-IP-4.079

# pkg info xymon-client
pkg: No package(s) matching xymon-client
```

Looking at the file https://github.com/opnsense/tools/commit/88e547d70eefde02137660f313ba079db4aeae68#diff-dd794f451924f38805651a796fdb64fd6eb3d80517f68bfaf6c89ddc4a73764bR108 I see many packages there which I don't see with `pkg info net-mgmt/*`

**Comment by fichtner** [comment]
You need to install first, pkg-info is for local queries...

https://pkg.opnsense.org/FreeBSD:14:amd64/24.7/latest/All/xymon-client-4.3.30.pkg

    # pkg install xymon-client

**Comment by kumy** [comment]
I'm not used to `pkg`, sorry for my ignorance :)
Working fine! Thanks!
```
# pkg install xymon-client
Updating OPNsense repository catalogue...
OPNsense repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	xymon-client: 4.3.30

Number of packages to be installed: 1

The process will require 3 MiB more space.
435 KiB to be downloaded.

Proceed with this action? [y/N]: 
[…]
```

**Comment by fichtner** [comment]
No worries. Step by step. 😊
