### ISSUE TITLE
Missing installation menu from vga image

### ISSUE THREAD

**Issue by oparoz** [opnsense/tools#44]
After managing to burn the image, which is only possible from Linux, the USB stick boots, but there is no installation menu, so it's impossible to use this image as an installer.

**Comment by fichtner** [comment]
Do you have a login prompt?

If yes, try: "installer" + "opnsense"

**Comment by oparoz** [comment]
Press 8 in the menu, logged in using the default u/p.
```
root@OPNsense # installer
installer: Command not found
```

**Comment by oparoz** [comment]
Got it. Logging in with intaller/opnsense brought up the installation menu.

**Comment by oparoz** [comment]
Is it purely a documentation issue then?

**Comment by fichtner** [comment]
/usr/local/etc/rc.installer is the command, no shortcut.

Yes, it's a new feature. We will document it.

I specifically recall you arguing we should not boot the installer by default. Is that true? ;)

**Comment by oparoz** [comment]
>I specifically recall you arguing we should not boot the installer by default. Is that true? ;)

That rings a bell :). It would automatically install after a timeout IIRC, thus overwriting the current setup.

**Comment by fichtner** [comment]
Ok, so you still have the opportunity to run the early installer, but it times out now instead of loading the installer. The system boots up in order to be able to run the installer via SSH using the same combo. We'll document this soon, and this issue is closed. :)

**Comment by oparoz** [comment]
Thank you Franco
