### ISSUE TITLE
Update `pkg` port

### ISSUE THREAD

**Issue by 0xThiebaut** [opnsense/tools#442]
On a stock `14.1-RELEASE`, `make ports` fails due to a mismatch of the installed `pkg` version.

```
>>> Running build step: ports
>>> Passing arguments: (none)
Installed pkg version '1.21' does not match required version '1.19'
*** Error code 1
```

``` 
# pkg --version
1.21.3
# freebsd-version
14.1-RELEASE
```

On a side-note, where could I find the documentation to bump the package myself?

**Comment by fichtner** [comment]
fa856d166fb4 should do the trick :)
