### ISSUE TITLE
basic cdrom build needs manual changes

### ISSUE THREAD

**Issue by wevcode** [opnsense/tools#46]
I have created a virtual machine running FreeBSD 11 and followed all instructions from the readme but I cloned my own `core` repository and checked out my own branch which is based on master (important).

If I run `make cdrom` it answered with branches which does not match. I have to checkout `stable/17.1` in `plugins` and `src` and then I am able to run `make cdrom`.

But I want to use master, because I am working on a new feature.

***One may have to modify the `Makefile` so you can use your own branch without these workarounds.***

**Comment by fichtner** [comment]
You just need to follow the onscreen instructions and append this to the make call:

    make cdrom SRCBRANCH=master

But in your case I think the build is overkill, you can test local changes within a running OPNsense. I will post the instructions in the other thread.


Cheers,
Franco
