### ISSUE TITLE
Missing packages (i386)

### ISSUE THREAD

**Issue by Beeblebrox-BSD** [opnsense/tools#51]
IDK how long i386 will be supported, so this may be an irrelevant issue.

pkg repo for 17.1 does not have following binaries:
www/py-searx -> Anonymous, self-hosted meta search engine
security/obfsclient -> Packet obfuscator for SOCKS
security/tcpcrypt: Alternatively, www/privoxy as plugin upstream to squid could be a better option due to TLS support soon to embedded into privoxy.

Personally, I would place all above in jails, and I'm sure that feature is under consideration...
Regards.

**Comment by fichtner** [comment]
Hi beeblebrox,

Just quickly, i386 will be supported as long as we stay on FreeBSD 11. When 12 is out we migrate to HardenedBSD, but that could be anywhere between 2019-2020.

Privoxy should already be there?

I'll follow up on the rest on Monday.


Cheers,
Franco

**Comment by Beeblebrox-BSD** [comment]
Hi Franco,

My Privoxy comment was perhaps misunderstood. I meant that security/tcpcrypt may soon loose importance with upcoming TLS transport support in Privoxy. So, not sure about tcpcrypt...

I installed www/py-searx from the FreeBSD repo and already have it running in a jail as well as [unbound + dnscrypt-proxy]

My desktop is already on HBSD-12, btw :)
Regards.

**Comment by fichtner** [comment]
I'll add obfsclient and tcpcrypt, but py-searx is far too stressful for the build with a heavy dependency list. I need to ask you to build this one from ports.

HBSD-12 is missing a few minor patches, but we'll work on this in the coming months. Nice! :)
