### ISSUE TITLE
Add ldap support to freeradius

### ISSUE THREAD

**Issue by mimugmail** [opnsense/tools#58]
Only if possible ... 
https://forum.opnsense.org/index.php?topic=6357.0

```
/usr/local/etc/raddb/mods-enabled/ldap[8]: Failed to link to module 'rlm_ldap': Cannot open "/usr/local/lib/freeradius-3.0.15/rlm_ldap.so"
root@OPNsense:/usr/local/etc/raddb/mods-enabled # ls /usr/local/lib/freeradius-3.0.15/rlm_ldap.so

```

**Comment by terdinatore** [comment]
+1 - since this way you can have both, a router and a "fully" working RADIUS-Server, at the same time!

**Comment by fichtner** [comment]
LDAP is an option, let‘s try that then. 😊

**Comment by fichtner** [comment]
Done via https://github.com/opnsense/tools/commit/7b1409e202

**Comment by mimugmail** [comment]
Merci :)
