### ISSUE TITLE
Plugin dependencies with versions

### ISSUE THREAD

**Issue by AdSchellevis** [opnsense/tools#61]
As discussed via mail,  in some cases plugins require php (or python) modules, which could lead to dependency lists like:

`PLUGIN_DEPENDS=         php70-mbstring php70-bcmath
`

When changing versions (for in this case php), the plugin breaks due to version conflicts.

It would be practical if we could depend on a non specified version of the package, like `php-mbstring` for example

**Comment by fichtner** [comment]
Use:

    PLUGIN_DEPENDS= php${PRODUCT_PHP}-mbstring php${PRODUCT_PHP}-bcmath

This, however, only works in a development environment if the latest /usr/tools is cloned *and* a symlink exists from /etc/make.conf to /usr/tools/17.7/make.conf which is automatically taken care of by:

    # opnsense-code tools

The build system should cope with this automatically.

**Comment by AdSchellevis** [comment]
Thanks, one question, what happens if I try to install a package build on php7.1 on a machine which has php7.2 installed? (the manifest file seems to have the version in it)

**Comment by fichtner** [comment]
Until PHP is flavoured on FreeBSD, nothing good can happen. There is also a latent bug in pkg, e.g. we can't have two php versions at the same time and the core gets confused trying to update "both" php versions, which install files in the same place.

I would assume the package cannot be installed, but it should not make the system unusable as there is only one php available at all times for us due to the above reasons.

**Comment by AdSchellevis** [comment]
ok, bummer, maybe in time the situation improves, for now I have to make sure to build new versions for every version bump then.

**Comment by fichtner** [comment]
you could also make sure the php version is inside the package e.g. create a new one like "myplugin72"

**Comment by AdSchellevis** [comment]
or drop the dependency and manage it manually :) no problem, just something to remember when plugins containing only scripts should depend on something... dependency management in pkg unfortunately isn't flawless...
