### ISSUE TITLE
Poudriere

### ISSUE THREAD

**Issue by lattera** [opnsense/tools#7]
It'd be nice to use Poudriere rather than the custom ports build script that's being used. Using poudriere would also let us keep track of which ports built and which didn't.

**Comment by fichtner** [comment]
I'm going to close this: Building in poudriere is a possibility, but I don't feel comfortable increasing tools.git complexity for it as the old method will remain in there.

Theoretically, only the ports build is the improvement target here, it would be possible to have a separate "poudriere.sh" script that does the analogous amount of work by interfacing with poudriere and wrapping up the packages set.

Benefits would be: better progress report, bulk builds for large sets, parallel operation.

With that being said, a maintainer is required for it to happen.
