### ISSUE TITLE
"make dvd" don`t add changes of menu.xml in ISO

### ISSUE THREAD

**Issue by teliz** [opnsense/tools#73]
I generated an opnsense ISO without modifying anything. I changed /Base/Menu/Menu.xml by adding another item in the menu, and re-executed make dvd but these changes in the menu were not added to ISO
I tried:
```
make dvd
make dvd-again
make clean-core && make dvd
```
but not work

**Comment by fichtner** [comment]
clean-core should do the trick, but you will need to remove dvd as well in that order:

make clean-core && make dvd-again
