### ISSUE TITLE
haproxy/haproxy-devel

### ISSUE THREAD

**Issue by evbevz** [opnsense/tools#75]
https://github.com/opnsense/tools/blob/17ac7bc46263a80e126046f40b25ed8eb5904cf5/config/18.1/ports.conf#L92

Is it needed (haproxy)?
Plugin depends on haproxy-devel.
haproxy-devel rebuilds each time on ports builds.

**Comment by fichtner** [comment]
I think something is broken in FreeBSD ports, but you are right, at this point we don't need it. I'll remove.
