### ISSUE TITLE
help for raspberry pi 3 supported steps

### ISSUE THREAD

**Issue by dipenpatel235** [opnsense/tools#76]
hello...
can we cross compile it for any other arm board like
raspberry pi 3 or Rock64 
because thoes are cheapest now
https://www.pine64.org/?product=rock64-media-board-computer 

If you have knowledge on it so help me how to cross compile for other boards.

Thanks
Dipen

**Comment by fichtner** [comment]
Hi Dipen,

Sure, that's what this doc is for: https://github.com/opnsense/tools#cross-building-for-other-architecures

:)

Cheers,
Franco

**Comment by dipenpatel235** [comment]
ok..so using that i can did for cross compile any arm board ?
like
raspberry pi 3 or Rock64 ?

Thanks

**Comment by fichtner** [comment]
sure, but you need the proper freebsd sources for arm64, different u-boot port I presume

**Comment by fichtner** [comment]
I don't know. It changes with each FreeBSD version. 11.1 which we have has no proper arm64 support, but you can use a FreeBSD 12-CURRENT tree. Arguments like ARCH, KERNEL etc. are used always, you can mix them with "dvd", too.

**Comment by dipenpatel235** [comment]
ok

**Comment by nielsenlegal** [comment]
Have a tutorial ?

**Comment by fichtner** [comment]
https://github.com/opnsense/tools#cross-building-for-other-architecures
