### ISSUE TITLE
how to generate .sig in package files

### ISSUE THREAD

**Issue by teliz** [opnsense/tools#78]
Good morning guys, 
does anyone know why when I generate a "make dvd" build the .tar generated in my SETSDIR directory the files inside this .tar do not have .sig?!

1 - how can I generate this .sig just as it exists in pkg.opnsense.org?

2 - inside of my packagesite.txz  after "make dvd" exist only  

- packagesite.yaml

 but in pkg.opnsense.org the packagesite.txz have: 

- packagesite.yaml 
- packagesite.yaml.sig
- packagesite.yaml.pub

how can I generate this .sig and .pub ?

thanks  :)

**Comment by fichtner** [comment]
Hi @teliz,

You will have to give the build process your own public and private key for signing via the PRIVKEY and PUBKEY arguments.


Cheers,
Franco

**Comment by teliz** [comment]
thanks @fichtner

then after I generate my keys I make :
`make  step PRIVKEY="~/.ssh/id_rsa" PUBKEY="~/.ssh/id_rsa.pub" dvd`

<3  OPNsense

**Comment by fichtner** [comment]
purrfect :)

**Comment by fichtner** [comment]
PS: "make sign PRIVKEY=...." let's you regenerate signatures without requiring a set rebuild

**Comment by teliz** [comment]
@fichtner hello
I'm having a problem, 
I again generated an ISO using my RSA keys:
`make PRIVKEY="/root/.ssh/id_rsa" PUBKEY="/root/.ssh/id_rsa.pub" dvd
`
 and after that I copied the 

> packages-b643bff1f5c999932cca39e362c5a69c5c2c5dd8-OpenSSL-amd64.tar 

that is in **SETSDIR** to my test server and extracts, I made the hierarchy equal to the latest one of pkg.opnsense.org.

when I access the system / firmware / update and click on update it returns "There are no updates available on the selected mirror."
but when I copy the packagesite.txz from the latest of pkg.opnsense.org it displays the updates, I think something has happened in the signature of my build.
the build should not accept packagesite.txz from opnsense because you sign with another key.

thanks :)

**Comment by teliz** [comment]
@fichtner hello
I changed my file `src/etc/pkg/fingerprints/OPNsense/trusted/pkg.opnsense.org.20171219` with my fingerprint :
`0FKqQTZtyYyI5ikfrt4Nx+5zEpVKsC0qy4QVuqTUCY4
`

But it did not work.
I noticed one thing, it has a different size than the opnsense.

**opnsense fingerprint:**
`fingerprint: "9a2c4fd9fa68b91c0dc5564a31b8b3d96f9aaf2ca07075f83433c96741bf681a"
`
**my fingerprint:**
`fingerprint: "0FKqQTZtyYyI5ikfrt4Nx+5zEpVKsC0qy4QVuqTUCY4"
`

I generated my rsa key and fingerprint like this: (I use passphrase empty)

`ssh-keygen -t rsa -b 4096 
`
` ssh-keygen -lf /root/.ssh/id_rsa.pub`

> 4096 SHA256:0FKqQTZtyYyI5ikfrt4Nx+5zEpVKsC0qy4QVuqTUCY4 root@telizze (RSA)

should the fingerprint be generated in this way?

I do not know if you can help, but this is my public key:
"`ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCa5LlbiMg4rG8KUoMISx1gAIU+9c8Y+DVqQ7OFblT/FDLZQ3ozSZrI5JKIUW39ZaYoAoPpKKtRNzroRdJNr4Nr5lYRDrqgTB8Ggp6bo66mUX1lCA85yIJN/2rItaBfhUdWEC/GfrWWzHqjb4SUyjcCVhdTd/FHMp7wwmBI3a19sklkZ9VorYxbMX9mOXyU1sx9Wj31JGF2llyrnee2vmcO+OAgHaS5jrBBz7W5y/O18tfXknjLZmI3qqF2iqxF+pjPbHD1syocb2wPIVoh+mYwhxPc8UmEaQIeolcLGXUVrH1bfjqvRiur3YM+TW1KVf/W4qeMbecJeFS4OQXrlhupqAKI0pcVtEAvawcE8G/u+ra52cXzjSBeyW05uMwsSDhxj0ipuHNTCLKRfvhPoyOgQALEi2XqRxPYy7+mxXF/nnNjwVL9jeT6f0s0PXDX4ap1y6QnmnjvL9P9CiYOa7ksQbb8BJGpxy6FPvtXHuOWplq2ZhXfIMF3hPsGLjRf2QiyD8WVDQFirViXE+qqWX07YJuG3cKmiJ00KdEYIs79BxYIp9wAJ/z5PRyMlQPd1VAP9/RmXpyUeoEk/34COBD1SZph22+jMq8lu1PU48zTBTL/2TrBRTd+jFzovkDjO0Dlu5dEQSz2ZeVIxjCx5+T0TAkmWuJw8+0GxFKbmil3NQ== root@telizze` "

thanks :)

**Comment by fichtner** [comment]
No, wrong fingerprint. That's what this script is for: https://github.com/opnsense/tools/blob/master/scripts/pkg_fingerprint.sh

**Comment by teliz** [comment]
work fine the "pkg_fingerprint" 👍 
```
root@telizze:/usr/core # /usr/tools/scripts/pkg_fingerprint.sh /usr/rsa-key/root/.ssh/rsa_4096_pub.pem
function: "sha256"
fingerprint: "1468e239851dd684f4e8465e9feaf29afb8264378bf8914582ab1ebf00989690"
```
but , I replace the file "fingerprints/OPNsense/trusted/pkg.opnsense.org.20171219" with my fingerprint and run: 
`make PRIVKEY="/usr/rsa-key/root/.ssh/rsa_4096_priv.pem" PUBKEY="/usr/rsakey/root/.ssh/rsa_4096_pub.pem" dvd`

but in my ISO running in a VM (virtualbox) the file "pkg.opnsense.org.20171219" be equal of opnsense fingerprint

I'm forgetting something?
Thanks :)

ps: if I change my packagesite for the opnsense packagesite and  "check for update" (interface), works

**Comment by teliz** [comment]
@fichtner How are you? sorry for the insistence
But I still can not figure out how to change the fingerprint.
I edited the file:
`src/etc/pkg/fingerprints/OPNsense/trusted/pkg.opnsense.org.20171219
`
and generated a dvd again, but it still continues using the opnsense fingerprint. 
thanks

**Comment by teliz** [comment]
hello @fichtner , this is working, I fixed the problem in my vm, sorry to bother, but still thank you very much,
you guys are awesome 🤘

**Comment by fichtner** [comment]
Hi @teliz,

Sorry for the delay.

You should create your own fingerprint file under src/etc/pkg/fingerprints/OPNsense/trusted and then *commit* the change, because otherwise it won't be added.

Afterwards, rebuild the core packages and the dvd...

    # make core-opnsense,opnsense-devel dvd-again


Cheers,
Franco
