### ISSUE TITLE
RPI2 Make Error

### ISSUE THREAD

**Issue by peylight** [opnsense/tools#79]
`# make base kernel ARCH=arm:armv6 KERNEL=SMP-RPI2`

```
===> usr.sbin/timed/timed (all)
===> usr.sbin/timed/timedc (all)
===> usr.bin/finger (all)
===> usr.sbin/config (all)
===> usr.bin/ftp (all)
===> usr.sbin/crunch (all)
===> usr.sbin/crunch/crunchgen (all)
c++: error: linker command failed with exit code 1 (use -v to see invocation)
--- clang ---
*** [clang] Error code 1

make[5]: stopped in /usr/src/usr.bin/clang/clang
1 error

make[5]: stopped in /usr/src/usr.bin/clang/clang
--- all_subdir_usr.bin/clang/clang ---
*** [all_subdir_usr.bin/clang/clang] Error code 2

make[4]: stopped in /usr/src/usr.bin/clang
A failure has been detected in another branch of the parallel make

make[5]: stopped in /usr/src/usr.sbin/crunch/crunchgen

```
What's happened?

**Comment by peylight** [comment]
Who can accept Cross-building is working?
I'm testing but it is not working!
What is the problem?

**Comment by fichtner** [comment]
I'll provide a new armv6 build in a few weeks based on bananapi...

**Comment by fichtner** [comment]
PS: are you cross-building on 32 or 64 bit?

**Comment by peylight** [comment]
@fichtner FreeBSD 11.1 amd64

**Comment by fichtner** [comment]
you need a i386 for a seamless cross-build of armv6, see

**Comment by peylight** [comment]
@fichtner Ok i will be check it as soon as possible
Can i use FreeBSD 11.2?

**Comment by peylight** [comment]
@fichtner 
qemu-user-static is only for amd64! not i386

**Comment by fichtner** [comment]
I know, it's not my fault. The maintainer disabled that useful port. ;)

**Comment by peylight** [comment]
@fichtner 
Maybe adding the feature to make opensense in freebsd amd64 be better.
What is the issue about amd64 to making opensense for RPI2?

**Comment by fichtner** [comment]
It's a BSD issue: kernel struct size in 32 vs. 64 bit breaks networking in chroot. You cannot fetch packages / patches in a 32 bit chroot inside 64 bit and some fetches are not worked around like with pecl I think...

**Comment by nekoprog** [comment]
Is there any way to enable installing from a broken port? Only i386 qemu-user-static port is marked as broken. While amd64 cannot successfully cross build opnsense.

**Comment by fichtner** [comment]
https://github.com/freebsd/freebsd-ports/commit/dfb629981d6161 disabled i386 and you can reenable build by undoing the BROKEN annotation for i386

**Comment by fichtner** [comment]
we're tracking this via #79 now, I've added a nightly build for armv6: https://nightly.opnsense.org/

**Comment by fichtner** [comment]
Sorry, I meant #113

**Comment by nekoprog** [comment]
Thanks for the fix.
