### ISSUE TITLE
perl module for SIP and database access

### ISSUE THREAD

**Issue by fbrendel** [opnsense/tools#84]
In order to make SIP calls triggered from database events following packages are needed.

net/p5-Net-SIP
dns/p5-Net-DNS
databases/p5-DBI
databases/p5-DBD-Sybase
databases/p5-DBD-Pg

**Comment by fichtner** [comment]
net/p5-Net-SIP includes dns/p5-Net-DNS
databases/p5-DBD-Sybase and databases/p5-DBD-Pg both include databases/p5-DBI

Unfortunately  for the moment, build of databases/p5-DBI fails with a vague error so I need to look into it later, but from the dependency perspective adding these packages is no problem. :)

**Comment by fbrendel** [comment]
Thank you! 
No rush. :smiley:

**Comment by fichtner** [comment]
@fbrendel hello there, are you still interested in this? :)

**Comment by fbrendel** [comment]
Hi @fichtner :smiley: 
yes, I'm still interested.
But if you have still trouble with databases/p5-DBI, let it be.

**Comment by fichtner** [comment]
Looks good, will be part of 21.1.5...

**Comment by fbrendel** [comment]
Thank you! :smiley:

**Comment by fichtner** [comment]
Sure, no problem :)
