### ISSUE TITLE
Request adding the `autossh` package to the OPNsense repo

### ISSUE THREAD

**Issue by ndejong** [opnsense/tools#87]
Hi,

Was directed here through a [forum post](https://forum.opnsense.org/index.php?topic=9388.0)

I'd like to request for the addition of the `autossh` package from the main FreeBSD repo into the OPNsense repo - from the forum post:-
> We are in the process of writing another OPNsense plugin that requires an additional standard FreeBSD distribution package, namely autossh.
>
> Have done dirty hacks in the past by manually pulling in packages from the FreeBSD repo and installing manually when those packages are not available via the opnsense repo but this is surely not the right thing to be doing.

Even without a fancy-clicky plugin front end, the `autossh` tool is enormously useful and helpful in establishing and keeping ssh-tunnels alive - it would seem to be an appropriate inclusion anyway.

For reference:-
https://www.freshports.org/security/autossh/

**Comment by fichtner** [comment]
@ndejong can you try "pkg install" prior to opening tickets... because... it's available since 2015 :D see 22f90aaa713
