### ISSUE TITLE
Request for py27-xmltodict package into the OPNsense ports tree

### ISSUE THREAD

**Issue by ndejong** [opnsense/tools#88]
I've landed myself back here again to request two new packages to be considered for inclusion into the OPNsense ports tree - breaking these requests into two separate github-issues that originate from the same place https://github.com/opnsense/plugins/pull/777#discussion_r210179219 since each package ought to be addressed on its own merits.

Package request **`py27-xmltodict`**
 - As best I can tell there is nothing comparable among the current set of available Python modules that provides such straight forward functionality.
 - I've grepped the OPNsense `core` and `plugins` repos for examples that are using `xmllib` or `HTMLParser` nothing appears to exist
 - The `xmltodict` Python module is [referenced](https://docs.python-guide.org/scenarios/xml/) in a number of places as an appropriate choice for the really straight forward task.
 - I note the functionality that exists in `src/opnsense/service/modules/config.py` which is close however it does not accept an XML string as input and the use case I have is to parsing XML response data from an external web-service, in my case a call to an AWS api endpoint for their S3 service.

```
opnsense-plugins$ grep -r HTMLParser *
opnsense-plugins$ grep -r xmllib *
opnsense-plugins$ cd ../opnsense-core
opnsense-core$ grep -r HTMLParser *
opnsense-core$ grep -r xmllib *
```

All of this said, if there is indeed an existing equivalent module or straight forward code snippet that has been missed please do assist by pointing it out - certainly trying to avoid making an embarrassing mistake as in the other week with this request https://github.com/opnsense/tools/issues/87

**Comment by AdSchellevis** [comment]
added in https://github.com/opnsense/tools/commit/e4c693ece9aeb5f5d48e419b3277aca789592c25
