### ISSUE TITLE
After building dvd it run only on one system

### ISSUE THREAD

**Issue by Kha13d** [opnsense/tools#92]
Hi, I have problem with the building.

I make an ISO file with make dvd inside a virtual machine system.
When i run the ISO on the same VMbox in the same system it work fine.

But if i move the ISO to new PC and try to run it, it fail to boot.

From my understanding the DVD should be universal and work in any system, please correct me if i'm wrong.

and how i can start to fix this problem?

**Comment by fichtner** [comment]
It heavily depends on what that PC hardware is. Can you elaborate on cpu and mainboard?

**Comment by Kha13d** [comment]
I built the system on Virtual box machine running OPNsense 18.7, i'm using Ubuntu as OS, and HP laptop as hardware with i7-5500U cpu.

I test the build on Virtual box machine with the same specific that i built with, and the cpu of the PC is i7 8th gen and gigabit motherboard. 

Is it depend on the type of hardware i build the image with? and should I use non-virtual machine for the building?

**Comment by fichtner** [comment]
No, the hardware this was built on doesn't matter. But if you can't boot a FreeBSD ISO on that PC OPNsense will fail to boot as well for generic hardware compatibility reasons.

**Comment by Kha13d** [comment]
I can run FreeBSD on that PC.

What confused me that I can run the build version on my PC it run perfectly!, but the other PC's while it's booting it show that some files can be read-only and other not writable is it a files permissions problems?

Also when i try to login it say: can find /sbin/opnsense-shell! so i can not login in to the system.

**Comment by fichtner** [comment]
I'm sorry, this is way beyond my support capabilities. If you burn a DVD/CD and files are missing something is wrong during burning of the image.

**Comment by Kha13d** [comment]
Thank you! I will see what I can do if there any update I will post it.

**Comment by Kha13d** [comment]
It seem that the problem from a corrupted storage that i used to copy the ISO from device to another.
Sorry for that xD!

**Comment by fichtner** [comment]
No worries, thanks for letting me know. :)
