### ISSUE TITLE
port request

### ISSUE THREAD

**Issue by fabianfrz** [opnsense/tools#96]
Please add:

* databases/postgresql10-server (enterprise grade database server for local PHP via nginx, PowerDNS backend)
* databases/rubygem-pg (background task scripting which need a binding for PostgreSQL etc.)
* dns/pdns (disable the MYSQL build option, it is not needed and pulls not required dependencies)
* php71-pdo_pgsql as well as PDO itself (DB access from PHP) - unless we are switching to PHP72, then the newer one ;)

**Comment by WithoutCaps** [comment]
I realize that nobody viewed this issue, but if you are running a web server on opnsense - may I recommend not doing that? Its a horrible practice from a security perspective

**Comment by fabianfrz** [comment]
@WithoutCaps I know that it is and I would not recommend it but fact is that I support serving websites in the nginx plugin if desired (would make sense in some home setups) where you want to power as less as possible devices. PHP can be enabled but without a database it will be quite useless.
